Repository kumahq/kuma, pull requests merged in 2019-10, with the labels that each got.

#303 ci: make Bintray release repositories configurable
  tools/releases/distros.sh
  tools/releases/docker.sh
Labels: ci

#298 kuma-cp: use Controller to create default Mesh on k8s
  app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml
  app/kumactl/data/install/k8s/control-plane/kuma-cp/rbac.yaml
  app/kumactl/pkg/install/k8s/control-plane/templates_vfsdata.go
  pkg/config/app/kuma-cp/config.go
  pkg/core/bootstrap/bootstrap.go
  pkg/core/bootstrap/bootstrap_test.go
  pkg/core/bootstrap/plugins.go
  pkg/core/managers/apis/mesh/mesh_helpers.go
  pkg/plugins/runtime/k8s/controllers/namespace_controller.go
  pkg/plugins/runtime/k8s/plugin.go
Labels: kuma-cp

#299 kuma-cp: use Controller to create Builtin CA on k8s
  pkg/core/ca/builtin/manager.go
  pkg/core/resources/apis/mesh/mesh_helpers.go
  pkg/plugins/runtime/k8s/controllers/mesh_controller.go
  pkg/plugins/runtime/k8s/plugin.go
Labels: kuma-cp

#304 kuma-injector: make ReadinesProbe, LivenessProbe and Resources settings of a side-car container configurable
  app/kuma-injector/pkg/injector/injector.go
  app/kuma-injector/pkg/injector/testdata/inject.01.golden.yaml
  app/kuma-injector/pkg/injector/testdata/inject.02.golden.yaml
  app/kuma-injector/pkg/injector/testdata/inject.03.golden.yaml
  app/kuma-injector/pkg/injector/testdata/inject.04.golden.yaml
  app/kuma-injector/pkg/injector/testdata/inject.config.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml
  app/kumactl/data/install/k8s/control-plane/kuma-injector/app.yaml
  app/kumactl/pkg/install/k8s/control-plane/templates_vfsdata.go
  pkg/config/app/kuma-injector/config.go
  pkg/config/app/kuma-injector/config_test.go
  pkg/config/app/kuma-injector/testdata/default-config.golden.yaml
  pkg/config/app/kuma-injector/testdata/valid-config.input.yaml
Labels: kuma-injector

#305 docs: update CHANGELOG for 0.2.0
  CHANGELOG.md
Labels: docs

#306 kuma-cp: fix an issue with Access Log Server on Kubernetes by replacing Google gRPC client with Envoy gRPC client
  CHANGELOG.md
  pkg/xds/bootstrap/generator.go
  pkg/xds/bootstrap/template.go
  pkg/xds/bootstrap/testdata/bootstrap.golden.yaml
  pkg/xds/bootstrap/testdata/bootstrap.overridden.golden.yaml
  pkg/xds/envoy/access_logs.go
  pkg/xds/envoy/envoy_test.go
Labels: kuma-cp, kuma-dp

#310 kuma-dp: make drain time of Envoy Listeners configurable
  app/kuma-dp/pkg/dataplane/envoy/envoy.go
  app/kuma-dp/pkg/dataplane/envoy/envoy_test.go
  app/kuma-injector/pkg/injector/injector.go
  app/kuma-injector/pkg/injector/testdata/inject.01.golden.yaml
  app/kuma-injector/pkg/injector/testdata/inject.02.golden.yaml
  app/kuma-injector/pkg/injector/testdata/inject.03.golden.yaml
  app/kuma-injector/pkg/injector/testdata/inject.04.golden.yaml
  app/kuma-injector/pkg/injector/testdata/inject.config.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml
  app/kumactl/data/install/k8s/control-plane/kuma-injector/app.yaml
  app/kumactl/pkg/install/k8s/control-plane/templates_vfsdata.go
  pkg/config/app/kuma-dp/config.go
  pkg/config/app/kuma-dp/config_test.go
  pkg/config/app/kuma-dp/testdata/default-config.golden.yaml
  pkg/config/app/kuma-dp/testdata/invalid-config.input.yaml
  pkg/config/app/kuma-dp/testdata/valid-config.input.yaml
  pkg/config/app/kuma-injector/config.go
  pkg/config/app/kuma-injector/config_test.go
  pkg/config/app/kuma-injector/testdata/default-config.golden.yaml
  pkg/config/app/kuma-injector/testdata/invalid-config.input.yaml
  pkg/config/app/kuma-injector/testdata/valid-config.input.yaml
Labels: kuma-dp, kuma-injector

#309 feat(kumactl) validate that the control plane is running
  app/kumactl/cmd/config/config_control_planes_add.go
  app/kumactl/cmd/config/config_control_planes_add_test.go
  app/kumactl/cmd/config/testdata/config-control-planes-add.01.golden.yaml
  app/kumactl/cmd/config/testdata/config-control-planes-add.02.golden.yaml
  app/kumactl/pkg/config/validate.go
  pkg/api-server/index_ws.go
  pkg/api-server/types/index.go
Labels: kumactl

#329 chore: upgrade version of `go-control-plane`
  api/go.mod
  api/go.sum
  go.mod
  go.sum
  pkg/plugins/resources/k8s/native/go.mod
  pkg/plugins/resources/k8s/native/go.sum
  pkg/sds/server/sds.go
  pkg/util/cache/cache.go
  pkg/xds/envoy/envoy.go
  pkg/xds/generator/resource_generator.go
  pkg/xds/server/dataplane_status_tracker_test.go
Labels: chore

#330 kuma-cp: copy xDS server implementation from `go-control-plane` for further customization
  pkg/xds/server/components.go
  pkg/xds/server/server.go
  pkg/xds/server/server_test.go
Labels: kuma-cp

#331 kuma-cp: modify generic `go-control-plane` to always respond to EDS requests that are happening at cluster warming stage
  pkg/xds/server/server.go
  pkg/xds/server/server_test.go
Labels: kuma-cp

#338 ci: make `clang-format` an optional tool
  .circleci/config.yml
  Makefile
Labels: ci

#337 kuma-cp: SDS server should support DiscoveryRequests with an empty list of resource names
  pkg/sds/server/sds.go
  pkg/sds/server/sds_test.go
Labels: kuma-cp, mTLS

#346 docs: update DEVELOPER.md
  DEVELOPER.md
Labels: docs

#350 ci: optimize caching of Golang dependencies on CircleCI
  .circleci/config.yml
Labels: ci

#352 ci: refactor Minikube example to reuse Docker images
  .circleci/config.yml
  Dockerfile.kuma-cp
  Dockerfile.kuma-dp
  Dockerfile.kuma-injector
  Dockerfile.kuma-tcp-echo
  Dockerfile.kumactl
  Makefile
  tools/ci/dockerfiles/Dockerfile.kumactl
Labels: ci

#353 ci: test Minikube example on different versions of Kubernetes
  .circleci/config.yml
  Makefile
Labels: ci

#355 ci: refactor kumactl workflow script
  examples/minikube/kumactl_workflow.sh
Labels: ci, kubernetes

#354 ci: test mTLS on Kubernetes
  .circleci/config.yml
  Makefile
  examples/minikube/README.md
  examples/minikube/kuma-demo/kuma-demo.yaml
  examples/minikube/kumactl_workflow.sh
  examples/minikube/policies/mtls.yaml
Labels: ci, kubernetes

#349 Expose initial token server with TLS on public interface
  app/kuma-cp/cmd/cmd_standalone_postgres_test.go
  app/kuma-cp/cmd/cmd_universal_memory_test.go
  pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
  pkg/config/loader_test.go
  pkg/config/token-server/config.go
  pkg/tokens/builtin/server/dataplane_token_server.go
  pkg/tokens/builtin/server/dataplane_token_server_test.go
  pkg/tokens/builtin/server/testdata/authorized-client-cert.pem
  pkg/tokens/builtin/server/testdata/authorized-client-key.pem
  pkg/tokens/builtin/server/testdata/server-cert.pem
  pkg/tokens/builtin/server/testdata/server-key.pem
  pkg/tokens/builtin/server/testdata/unauthorized-client-cert.pem
  pkg/tokens/builtin/server/testdata/unauthorized-client-key.pem
Labels: kuma-cp, mTLS, universal

#361 kumactl: add unit tests for JSON and YAML output
  app/kumactl/pkg/output/json/json_suite_test.go
  app/kumactl/pkg/output/json/json_test.go
  app/kumactl/pkg/output/json/testdata/mesh.golden.json
  app/kumactl/pkg/output/json/testdata/nil.golden.json
  app/kumactl/pkg/output/table/printer_test.go
  app/kumactl/pkg/output/table/testdata/empty.golden.txt
  app/kumactl/pkg/output/table/testdata/header-and-1-row.golden.txt
  app/kumactl/pkg/output/table/testdata/header-and-2-rows.golden.txt
  app/kumactl/pkg/output/table/testdata/header.golden.txt
  app/kumactl/pkg/output/yaml/testdata/mesh.golden.yaml
  app/kumactl/pkg/output/yaml/testdata/nil.golden.yaml
  app/kumactl/pkg/output/yaml/yaml_suite_test.go
  app/kumactl/pkg/output/yaml/yaml_test.go
Labels: kumactl

#343 add kumactl delete command
  app/kumactl/cmd/delete/delete.go
  app/kumactl/cmd/delete/delete_dataplane_test.go
  app/kumactl/cmd/delete/delete_meshes_test.go
  app/kumactl/cmd/delete/delete_proxytemplate_test.go
  app/kumactl/cmd/delete/delete_suite_test.go
  app/kumactl/cmd/delete/delete_test.go
  app/kumactl/cmd/delete/delete_trafficlog_test.go
  app/kumactl/cmd/delete/delete_trafficpermission_test.go
  app/kumactl/cmd/root.go
  docs/cmd/kumactl/HELP.md
Labels: kumactl

#363 chore: update version of Golang
  .circleci/config.yml
  DEVELOPER.md
  Makefile
  api/DEVELOPER.md
  pkg/plugins/resources/k8s/native/Dockerfile
Labels: chore

#360 Pretty print json for kumactl pkg
  app/kumactl/pkg/output/json/printer.go
  app/kumactl/pkg/output/json/testdata/mesh.golden.json
  app/kumactl/pkg/output/json/testdata/nil.golden.json
Labels: kumactl

#379 Corrected Grammer Mistake and Errors in RELEASE.md file
  RELEASE.md
Labels: docs

#382 chore: remove outdated Docker Compose example
  Makefile
  examples/docker-compose/Dockerfile.envoy-sidecar
  examples/docker-compose/README.md
  examples/docker-compose/docker-compose.yaml
  examples/docker-compose/envoy-sidecar-startup.sh
  examples/docker-compose/envoy.yaml
  examples/docker-compose/istio-iptables.sh
  examples/docker-compose/kubeconfig
Labels: chore

#384 ci: split e2e test for kubernetes into a dedicated Makefile
  Makefile
  Makefile.e2e.mk
Labels: ci

#385 ci: move e2e test for kubernetes mode out of `examples` folder meant for the end-users
  Makefile
  Makefile.e2e.mk
  dev/examples/k8s/example-app/example-app.yaml
  tools/e2e/examples/minikube/README.md
  tools/e2e/examples/minikube/kuma-demo/kuma-demo.yaml
  tools/e2e/examples/minikube/kumactl_workflow.sh
  tools/e2e/examples/minikube/policies/mtls.yaml
Labels: ci

#369 feat(kuma-cp) coordinates webservice
  Makefile
  app/kumactl/cmd/generate/generate_dataplane_token_test.go
  app/kumactl/pkg/cmd/root_context.go
  pkg/api-server/catalogue_ws.go
  pkg/api-server/catalogue_ws_test.go
  pkg/api-server/dataplane_overview_ws_test.go
  pkg/api-server/index_ws_test.go
  pkg/api-server/mesh_ws_test.go
  pkg/api-server/read_only_resource_ws_test.go
  pkg/api-server/resource_api_client_test.go
  pkg/api-server/resource_ws_test.go
  pkg/api-server/server.go
  pkg/catalogue/catalogue_suite_test.go
  pkg/catalogue/client/client.go
  pkg/catalogue/client_test.go
  pkg/catalogue/types.go
  pkg/config/api-server/catalogue/config.go
  pkg/config/api-server/config.go
  pkg/config/app/kuma-cp/config.go
  pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
  pkg/config/loader_test.go
  pkg/core/bootstrap/autoconfig.go
  pkg/core/bootstrap/autoconfig_test.go
Labels: kuma-cp

#386 chore: split commands that setup dev environment into a dedicated Makefile
  Makefile
  Makefile.dev.mk
Labels: chore

#399 kumactl: add column MESH for get proxytemplates
  app/kumactl/cmd/get/get_proxytemplates.go
  app/kumactl/cmd/get/testdata/get-proxytemplates.golden.txt
Labels: kumactl
