Repository kumahq/kuma, pull requests merged in 2020-06, with the labels that each got.

#781 feat(kuma-cp): circuit breaker
  api/mesh/v1alpha1/circuit_breaker.pb.go
  api/mesh/v1alpha1/circuit_breaker.proto
  app/kumactl/cmd/completion/testdata/bash.golden
  app/kumactl/cmd/completion/testdata/zsh.golden
  app/kumactl/cmd/delete/delete.go
  app/kumactl/cmd/delete/delete_test.go
  app/kumactl/cmd/get/get.go
  app/kumactl/cmd/get/get_circuit_breaker.go
  app/kumactl/cmd/get/get_circuit_breakers.go
  app/kumactl/cmd/get/get_circuit_breakers_test.go
  app/kumactl/cmd/get/get_single_resource_test.go
  app/kumactl/cmd/get/testdata/get-circuit-breaker.golden.json
  app/kumactl/cmd/get/testdata/get-circuit-breaker.golden.txt
  app/kumactl/cmd/get/testdata/get-circuit-breaker.golden.yaml
  app/kumactl/cmd/get/testdata/get-circuit-breakers.golden.json
  app/kumactl/cmd/get/testdata/get-circuit-breakers.golden.txt
  app/kumactl/cmd/get/testdata/get-circuit-breakers.golden.yaml
  app/kumactl/cmd/get/testdata/get-circuit-breakers.pagination.golden.txt
  app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml
  app/kumactl/data/install/k8s/control-plane/crds/kuma.io_circuitbreaker.yaml
  app/kumactl/data/install/k8s/control-plane/kuma-cp/app.yaml
  app/kumactl/data/install/k8s/control-plane/kuma-cp/rbac.yaml
  app/kumactl/pkg/install/k8s/control-plane/templates_vfsdata.go
  docs/cmd/kumactl/HELP.md
  go.mod
  go.sum
  pkg/api-server/circuit_breaker_endpoints_test.go
  pkg/api-server/definitions/all.go
  pkg/api-server/definitions/circuit_breaker.go
  pkg/core/resources/apis/mesh/circuit_breaker.go
  pkg/core/resources/apis/mesh/circuit_breaker_validator.go
  pkg/core/resources/apis/mesh/circuit_breaker_validator_test.go
  pkg/core/xds/types.go
  pkg/plugins/resources/k8s/native/api/v1alpha1/circuitbreaker_types.go
  pkg/plugins/resources/k8s/native/api/v1alpha1/circuitbreaker_types_deepcopy.go
  pkg/plugins/resources/k8s/native/api/v1alpha1/circuitbreaker_types_helpers.go
  pkg/plugins/resources/k8s/native/api/v1alpha1/circuitbreaker_types_test.go
  pkg/plugins/resources/k8s/native/config/crd/bases/kuma.io_circuitbreaker.yaml
  pkg/xds/envoy/clusters/circuit_breaker_configurer.go
  pkg/xds/envoy/clusters/circuit_breaker_configurer_test.go
  pkg/xds/generator/outbound_proxy_generator.go
  pkg/xds/generator/outbound_proxy_generator_test.go
  pkg/xds/generator/testdata/outbound-proxy/03.envoy.golden.yaml
  pkg/xds/generator/testdata/outbound-proxy/04.envoy.golden.yaml
  pkg/xds/server/components.go
  pkg/xds/topology/circuitbreakers.go
Labels: enhancement, envoy, improvement

#751 feat(kuma-cp): CircuitBreaker proposal
  docs/proposals/circuit-breaker.md
Labels: design-proposal, envoy

#788 Multicluster config infrastructure
  app/kuma-cp/cmd/run.go
  app/kuma-cp/cmd/run_test.go
  app/kumactl/cmd/completion/testdata/bash.golden
  app/kumactl/cmd/completion/testdata/zsh.golden
  app/kumactl/cmd/install/install_control_plane.go
  app/kumactl/cmd/install/install_control_plane_test.go
  app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml
  app/kumactl/data/install/k8s/control-plane/kuma-cp/app.yaml
  app/kumactl/pkg/install/k8s/control-plane/templates_vfsdata.go
  docs/cmd/kumactl/HELP.md
  pkg/api-server/config_ws_test.go
  pkg/config/app/kuma-cp/config.go
  pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
  pkg/config/core/config.go
  pkg/config/loader_test.go
Labels: multicluster

#784 feat(test) E2E testing framework
  .circleci/config.yml
  Makefile
  Makefile.e2e.new.mk
  Makefile.kind.mk
  app/kumactl/pkg/cmd/root_context.go
  go.mod
  go.sum
  test/e2e/e2e_suite_test.go
  test/e2e/foo.go
  test/e2e/kuma_deploy_global_local_test.go
  test/e2e/kuma_deploy_kubernetes_test.go
  test/e2e/testdata/example-app.yaml
  test/framework/constants.go
  test/framework/interface.go
  test/framework/k8s_cluster.go
  test/framework/k8s_clusters.go
  test/framework/kumactl.go
  test/framework/testing.go
  tools/releases/dockerfiles/Dockerfile.kuma-cp.dockerignore
  tools/releases/dockerfiles/Dockerfile.kuma-dp.dockerignore
  tools/releases/dockerfiles/Dockerfile.kuma-init.dockerignore
  tools/releases/dockerfiles/Dockerfile.kuma-prometheus-sd.dockerignore
  tools/releases/dockerfiles/Dockerfile.kumactl.dockerignore
Labels: multicluster

#812 (feat-multi-cluster):block resources based on kuma-cp mode
  app/kuma-cp/cmd/run.go
  pkg/api-server/definitions/definition.go
  pkg/api-server/sample_resource_definition_test.go
  pkg/api-server/server.go
  test/e2e/kuma_deploy_two_clusters_test.go
Labels: multicluster

#821 feat(kumactl) add install dns command
  app/kumactl/cmd/completion/testdata/bash.golden
  app/kumactl/cmd/completion/testdata/zsh.golden
  app/kumactl/cmd/install/install.go
  app/kumactl/cmd/install/install_dns.go
  docs/cmd/kumactl/HELP.md
Labels: multicluster

#798 feat(kuma-cp) add DNS resolver
  app/kuma-cp/cmd/cmd_k8s_test.go
  app/kuma-cp/cmd/cmd_standalone_postgres_test.go
  app/kuma-cp/cmd/cmd_universal_memory_test.go
  app/kuma-cp/cmd/run.go
  app/kumactl/cmd/install/install_dns.go
  app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.local.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml
  app/kumactl/data/install/k8s/control-plane/kuma-cp/app.yaml
  app/kumactl/pkg/install/k8s/control-plane/templates_vfsdata.go
  go.mod
  go.sum
  pkg/api-server/config_ws_test.go
  pkg/config/app/kuma-cp/config.go
  pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
  pkg/config/dns-server/config.go
  pkg/config/loader_test.go
  pkg/core/bootstrap/bootstrap.go
  pkg/core/runtime/builder.go
  pkg/core/runtime/runtime.go
  pkg/dns-server/components.go
  pkg/dns-server/resolver/handler.go
  pkg/dns-server/resolver/interface.go
  pkg/dns-server/resolver/ip.go
  pkg/dns-server/resolver/ip_test.go
  pkg/dns-server/resolver/server.go
  pkg/dns-server/resolver/server_test.go
  pkg/dns-server/resolver/suite_test.go
  pkg/dns-server/synchronizer/synchronizer.go
  pkg/test/runtime/runtime.go
  test/e2e/kuma_deploy_dns_test.go
  test/e2e/kuma_deploy_two_clusters_test.go
  test/framework/interface.go
  test/framework/k8s_cluster.go
  test/framework/k8s_clusters.go
  test/framework/kumactl.go
Labels: multicluster

#818 feat: ingress
  Makefile
  api/go.sum
  api/mesh/v1alpha1/dataplane.pb.go
  api/mesh/v1alpha1/dataplane.pb.validate.go
  api/mesh/v1alpha1/dataplane.proto
  api/mesh/v1alpha1/dataplane_helpers.go
  app/kumactl/cmd/completion/testdata/bash.golden
  app/kumactl/cmd/completion/testdata/zsh.golden
  app/kumactl/cmd/install/install.go
  app/kumactl/cmd/install/install_ingress.go
  app/kumactl/cmd/install/install_ingress_test.go
  app/kumactl/cmd/install/testdata/install-ingress.defaults.golden.yaml
  app/kumactl/cmd/install/testdata/install-ingress.overrides.golden.yaml
  app/kumactl/data/install/k8s/ingress/app.yaml
  app/kumactl/pkg/install/k8s/ingress/ingress_suite_test.go
  app/kumactl/pkg/install/k8s/ingress/templates.go
  app/kumactl/pkg/install/k8s/ingress/templates_dev.go
  app/kumactl/pkg/install/k8s/ingress/templates_vfsdata.go
  app/kumactl/pkg/install/k8s/ingress/templates_vfsdata_test.go
  docs/cmd/kumactl/HELP.md
  go.sum
  pkg/core/resources/apis/mesh/dataplane_validator.go
  pkg/core/resources/apis/mesh/dataplane_validator_test.go
  pkg/core/xds/types.go
  pkg/plugins/discovery/k8s/controllers/endpoints.go
  pkg/plugins/discovery/k8s/controllers/pod_controller.go
  pkg/plugins/discovery/k8s/controllers/pod_converter.go
  pkg/plugins/resources/k8s/native/go.sum
  pkg/plugins/runtime/k8s/webhooks/injector/metadata/annotations.go
  pkg/xds/envoy/clusters/client_side_mtls_configurer.go
  pkg/xds/envoy/listeners/filter_chain_match_configurer.go
  pkg/xds/envoy/listeners/tcp_proxy_configurer.go
  pkg/xds/envoy/listeners/tls_inspector_configurer.go
  pkg/xds/envoy/tls.go
  pkg/xds/envoy/tls_test.go
  pkg/xds/generator/ingress_generator.go
  pkg/xds/generator/ingress_generator_test.go
  pkg/xds/generator/outbound_proxy_generator.go
  pkg/xds/generator/permutation.go
  pkg/xds/generator/permutation_test.go
  pkg/xds/generator/proxy_template.go
  pkg/xds/generator/testdata/ingress/01.envoy.golden.yaml
  pkg/xds/generator/testdata/ingress/02.envoy.golden.yaml
  pkg/xds/generator/testdata/outbound-proxy/04.envoy.golden.yaml
  pkg/xds/generator/testdata/profile-source/1-envoy-config.golden.yaml
  pkg/xds/generator/testdata/profile-source/2-envoy-config.golden.yaml
  pkg/xds/generator/testdata/profile-source/3-envoy-config.golden.yaml
  pkg/xds/generator/testdata/profile-source/4-envoy-config.golden.yaml
  pkg/xds/ingress/dataplane.go
  pkg/xds/ingress/dataplane_test.go
  pkg/xds/ingress/ingress_suite_test.go
  pkg/xds/ingress/router.go
  pkg/xds/ingress/router_test.go
  pkg/xds/server/components.go
  pkg/xds/server/components_test.go
  pkg/xds/server/proxy_template_resolver.go
  pkg/xds/template/proxy_template.go
  pkg/xds/topology/outbound.go
  pkg/xds/topology/outbound_test.go
Labels: multicluster

#825 feat(kuma-cp): ingress integration test
  Makefile
  Makefile.e2e.new.mk
  app/kumactl/pkg/install/k8s/ingress/templates_vfsdata.go
  test/e2e/kuma_deploy_ingress_test.go
  test/e2e/testdata/demo-client.yaml
  test/e2e/testdata/echo-server.yaml
  test/framework/constants.go
  test/framework/exec_util.go
  test/framework/interface.go
  test/framework/k8s_cluster.go
  test/framework/k8s_clusters.go
  test/framework/kumactl.go
  test/framework/setup.go
Labels: multicluster

#831 feat(kuma-cp) multiple outbound tags
  Makefile.e2e.mk
  api/go.sum
  api/mesh/v1alpha1/dataplane.pb.go
  api/mesh/v1alpha1/dataplane.pb.validate.go
  api/mesh/v1alpha1/dataplane.proto
  api/mesh/v1alpha1/dataplane_helpers.go
  go.sum
  pkg/core/policy/connection_matcher.go
  pkg/core/resources/apis/mesh/dataplane_validator.go
  pkg/core/resources/apis/mesh/dataplane_validator_test.go
  pkg/core/xds/resource.go
  pkg/core/xds/types.go
  pkg/plugins/discovery/k8s/controllers/outbound_converter.go
  pkg/plugins/discovery/k8s/controllers/testdata/02.dataplane.yaml
  pkg/plugins/discovery/k8s/controllers/testdata/04.dataplane.yaml
  pkg/plugins/discovery/k8s/controllers/testdata/05.dataplane.yaml
  pkg/plugins/discovery/k8s/controllers/testdata/06.dataplane.yaml
  pkg/plugins/resources/k8s/native/go.sum
  pkg/xds/envoy/clusters/lb_subset_configurer.go
  pkg/xds/envoy/clusters/lb_subset_configurer_test.go
  pkg/xds/envoy/endpoints/endpoints.go
  pkg/xds/envoy/endpoints/endpoints_test.go
  pkg/xds/envoy/listeners/http_inbound_route_configurer.go
  pkg/xds/envoy/listeners/http_inbound_route_configurer_test.go
  pkg/xds/envoy/listeners/network_access_log_configurer_test.go
  pkg/xds/envoy/listeners/network_rbac_configurer_test.go
  pkg/xds/envoy/listeners/original_dst_forwarder_configurer_test.go
  pkg/xds/envoy/listeners/server_mtls_configurer_test.go
  pkg/xds/envoy/listeners/tcp_proxy_configurer.go
  pkg/xds/envoy/listeners/tcp_proxy_configurer_test.go
  pkg/xds/envoy/metadata.go
  pkg/xds/envoy/metadata_test.go
  pkg/xds/envoy/names/resource_names.go
  pkg/xds/envoy/routes/default_route_configurer.go
  pkg/xds/envoy/routes/default_route_configurer_test.go
  pkg/xds/envoy/types.go
  pkg/xds/generator/direct_access_proxy_generator.go
  pkg/xds/generator/inbound_proxy_generator.go
  pkg/xds/generator/ingress_generator.go
  pkg/xds/generator/outbound_proxy_generator.go
  pkg/xds/generator/outbound_proxy_generator_test.go
  pkg/xds/generator/proxy_template_profile_source_test.go
  pkg/xds/generator/testdata/ingress/01.envoy.golden.yaml
  pkg/xds/generator/testdata/outbound-proxy/03.envoy.golden.yaml
  pkg/xds/generator/testdata/outbound-proxy/04.envoy.golden.yaml
  pkg/xds/generator/testdata/outbound-proxy/cluster-dots.envoy.golden.yaml
  pkg/xds/generator/testdata/profile-source/1-envoy-config.golden.yaml
  pkg/xds/generator/testdata/profile-source/2-envoy-config.golden.yaml
  pkg/xds/generator/testdata/profile-source/3-envoy-config.golden.yaml
  pkg/xds/generator/testdata/profile-source/4-envoy-config.golden.yaml
  pkg/xds/generator/transparent_proxy_generator.go
  pkg/xds/topology/router.go
  pkg/xds/topology/router_test.go
Labels: multicluster

#830 Feat(kuma-cp) register Local CPs to Global CP
  app/kuma-cp/cmd/run.go
  app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.local.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml
  app/kumactl/data/install/k8s/control-plane/kuma-cp/app.yaml
  app/kumactl/pkg/install/k8s/control-plane/templates_vfsdata.go
  pkg/api-server/clusters_ws.go
  pkg/api-server/config_ws_test.go
  pkg/api-server/resource_api_client_test.go
  pkg/api-server/server.go
  pkg/clusters/components.go
  pkg/clusters/poller/poller.go
  pkg/config/app/kuma-cp/config.go
  pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
  pkg/config/clusters/clusters.go
  pkg/core/bootstrap/bootstrap.go
  pkg/core/runtime/builder.go
  pkg/core/runtime/runtime.go
  test/e2e/kuma_deploy_dns_test.go
  test/e2e/kuma_deploy_global_local_test.go
  test/e2e/kuma_deploy_multi_apps_test.go
  test/e2e/kuma_deploy_sidecar_test.go
  test/e2e/kuma_deploy_two_clusters_test.go
  test/framework/constants.go
  test/framework/interface.go
  test/framework/k8s_cluster.go
  test/framework/k8s_clusters.go
  test/framework/k8s_controlplane.go
  test/framework/setup.go
Labels: multicluster

#833 feat(kuma-cp) Leader election
  app/kuma-cp/cmd/run.go
  app/kuma-dp/cmd/run.go
  app/kuma-dp/pkg/dataplane/accesslogs/server.go
  app/kuma-dp/pkg/dataplane/envoy/envoy.go
  app/kuma-ui/pkg/server/server.go
  app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.local.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml
  app/kumactl/data/install/k8s/control-plane/kuma-cp/rbac.yaml
  app/kumactl/pkg/install/k8s/control-plane/templates_vfsdata.go
  go.mod
  go.sum
  pkg/admin-server/server.go
  pkg/api-server/server.go
  pkg/clusters/poller/poller.go
  pkg/core/runtime/builder.go
  pkg/core/runtime/component/component.go
  pkg/core/runtime/component/leader.go
  pkg/dns-server/resolver/interface.go
  pkg/dns-server/resolver/server.go
  pkg/dns-server/synchronizer/synchronizer.go
  pkg/mads/server/grpc.go
  pkg/plugins/bootstrap/k8s/plugin.go
  pkg/plugins/bootstrap/universal/plugin.go
  pkg/plugins/common/postgres/connection.go
  pkg/plugins/common/postgres/test_random_db.go
  pkg/plugins/leader/memory/leader_elector.go
  pkg/plugins/leader/plugin.go
  pkg/plugins/leader/postgres/leader_elector.go
  pkg/plugins/leader/postgres/leader_elector_test.go
  pkg/plugins/leader/postgres/postgres_suite_test.go
  pkg/plugins/resources/postgres/migrate.go
  pkg/plugins/resources/postgres/migrate_test.go
  pkg/plugins/resources/postgres/migrations/data/1592232449_add_leader_table.up.sql
  pkg/plugins/resources/postgres/migrations/migrations_vfsdata.go
  pkg/plugins/resources/postgres/store.go
  pkg/plugins/resources/postgres/store_template_test.go
  pkg/sds/server/grpc.go
  pkg/test/runtime/runtime.go
  pkg/util/channels/closed.go
  pkg/xds/bootstrap/server.go
  pkg/xds/server/diagnostics.go
  pkg/xds/server/grpc.go
Labels: kuma-cp, multicluster

#845 chore(*) rename Local CP to Remote CP
  app/kuma-cp/cmd/run.go
  app/kumactl/cmd/completion/testdata/zsh.golden
  app/kumactl/cmd/install/install_control_plane.go
  app/kumactl/cmd/install/install_control_plane_test.go
  app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.remote.golden.yaml
  app/kumactl/data/install/k8s/control-plane/kuma-cp/app.yaml
  app/kumactl/pkg/install/k8s/control-plane/templates_vfsdata.go
  docs/cmd/kumactl/HELP.md
  docs/proposals/multicluster.md
  pkg/api-server/server.go
  pkg/clusters/poller/poller.go
  pkg/config/app/kuma-cp/config.go
  pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
  pkg/config/clusters/clusters.go
  pkg/config/core/config.go
  test/e2e/kuma_deploy_global_remote_test.go
  test/framework/k8s_controlplane.go
  test/framework/kumactl.go
Labels: multicluster

#850 feat(kuma-cp) DNS resolver persistence
  api/system/v1alpha1/config.pb.go
  api/system/v1alpha1/config.pb.validate.go
  api/system/v1alpha1/config.proto
  app/kuma-cp/cmd/run.go
  pkg/core/bootstrap/bootstrap.go
  pkg/core/bootstrap/plugins.go
  pkg/core/config/config.go
  pkg/core/config/manager/manager.go
  pkg/core/config/manager/manager_suite_test.go
  pkg/core/config/store/adapter.go
  pkg/core/config/store/store.go
  pkg/core/plugins/interfaces.go
  pkg/core/plugins/registry.go
  pkg/core/resources/apis/system/config.go
  pkg/core/runtime/builder.go
  pkg/core/runtime/component/leader.go
  pkg/core/runtime/runtime.go
  pkg/dns-server/components.go
  pkg/dns-server/resolver/handler.go
  pkg/dns-server/resolver/interface.go
  pkg/dns-server/resolver/server.go
  pkg/dns-server/resolver/server_test.go
  pkg/dns-server/synchronizer/synchronizer.go
  pkg/dns/components/components.go
  pkg/dns/ip.go
  pkg/dns/ip_test.go
  pkg/dns/persistence.go
  pkg/dns/resolver.go
  pkg/dns/server.go
  pkg/dns/server_test.go
  pkg/dns/suite_test.go
  pkg/dns/sync_test.go
  pkg/dns/vips_allocator.go
  pkg/dns/vips_synchronizer.go
  pkg/plugins/config/k8s/k8s_suite_test.go
  pkg/plugins/config/k8s/plugin.go
  pkg/plugins/config/k8s/store.go
  pkg/plugins/config/k8s/store_test.go
  pkg/plugins/config/universal/plugin.go
  pkg/plugins/resources/k8s/consistent_kind_type_test.go
  pkg/test/runtime/runtime.go
  pkg/xds/topology/vip_outbounds.go
  pkg/xds/topology/vip_outbounds_test.go
Labels: multicluster
