Repository kumahq/kuma, pull requests merged in 2022-10, with the labels that each got.

#5129 docs(*): update MADR 007
  docs/madr/decisions/007-mesh-traffic-permission.md
Labels: ci/skip-test

#5094 docs(madr): create madr for new timeout policy
  docs/madr/decisions/010-timeout-policy.md
Labels: ci/skip-test

#5158 ci(.circleci): fix has_label to extract PR number correctly
  tools/ci/has_label.sh
Labels: ci/skip-test

#5161 ci(.github): fix pr-comments action
  .github/workflows/pr-comments.yaml
Labels: ci/skip-test

#5164 fix(.github): use github app in pr-comment action
  .github/workflows/pr-comments.yaml
Labels: ci/skip-test

#5169 ci(test): improve reliability of postgres tests
  pkg/plugins/resources/postgres/store_suite_test.go
  pkg/test/store/postgres/test_container.go
Labels: ci/skip-e2e-test

#5095 feat(ebpf): add option to cleanup after ebpf
  app/kumactl/cmd/completion/testdata/bash.golden
  app/kumactl/cmd/install/context/install_control_plane_context.go
  app/kumactl/cmd/install/install_transparent_proxy.go
  app/kumactl/cmd/root.go
  app/kumactl/cmd/uninstall/uninstall.go
  app/kumactl/cmd/uninstall/uninstall_ebpf.go
  app/kumactl/cmd/uninstall/uninstall_transparent_proxy.go
  deployments/charts/kuma/templates/post-delete-cleanup-ebpf-job.yaml
  docs/generated/cmd/kumactl/kumactl_uninstall.md
  docs/generated/cmd/kumactl/kumactl_uninstall_ebpf.md
  docs/generated/cmd/kumactl/kumactl_uninstall_transparent-proxy.md
  go.mod
  go.sum
  mk/k3d.mk
  pkg/transparentproxy/istio/istio.go
  pkg/transparentproxy/transparentproxy.go
  pkg/transparentproxy/transparentproxy_experimental.go
  test/e2e/ebpf/e2e_suite_test.go
  test/e2e/ebpf/ebpf_checker/deployment.go
  test/e2e/ebpf/ebpf_cleanup.go
  test/framework/config.go
  tools/releases/dockerfiles/Dockerfile.kuma-init
Labels: ci/run-full-matrix

#5200 test(e2e): skip gateway API on ARM
  test/e2e_env/kubernetes/gateway/cross-mesh.go
  test/e2e_env/kubernetes/kubernetes_suite_test.go
Labels: ci/run-full-matrix
