Repository kumahq/kuma, pull requests merged in 2022-12, with the labels that each got.

#5407 feat(build): fix docker publish in enterprise project
  tools/releases/docker.sh
Labels: ci/skip-test

#5440 feat(build): fix docker publish for ubi enterprise
  tools/releases/docker.sh
Labels: ci/skip-test

#5292 docs: madr multizone envoy admin operations
  docs/madr/decisions/011-multizone-envoy-admin.md
Labels: ci/skip-test

#5379 docs(MADR): add MeshCircuitBreaker madr
  docs/madr/decisions/014-mesh-circuit-breaker-policy.md
Labels: ci/skip-test, ci/skip-e2e-test

#5449 chore(docs): fix madr numbering
  docs/madr/decisions/013-multizone-envoy-admin.md
Labels: kind/cleanup, kind/docs, ci/skip-test, ci/skip-e2e-test

#5478 docs: create MADR for MeshRetry
  docs/madr/decisions/015-retry-policy.md
Labels: ci/skip-test, ci/skip-e2e-test

#5489 test: fix data race in heatbeat component tests
  pkg/intercp/catalog/heartbeat_component_test.go
Labels: ci/run-full-matrix

#5492 feat(kuma-cp): support IPV6 in intercp
  pkg/intercp/catalog/catalog.go
  pkg/intercp/catalog/catalog_test.go
Labels: ci/run-full-matrix

#5490 docs: follow up for MeshRetry MADR
  docs/madr/decisions/015-retry-policy.md
Labels: ci/skip-test

#5496 docs: madr of policy array merging
  docs/madr/decisions/016-policy-array-merging.md
Labels: ci/skip-test, ci/skip-e2e-test

#5502 chore: graduate debug-fast target
  mk/e2e.new.mk
Labels: ci/skip-test, ci/skip-e2e-test

#5518 chore(deps): upgrade k3d
  mk/dependencies/deps.lock
  mk/dependencies/k3d.sh
Labels: ci/run-full-matrix

#5485 chore(e2e): switch to new transparent proxy engine
  test/dockerfiles/Dockerfile.universal
  test/e2e_env/kubernetes/kubernetes_suite_test.go
  test/framework/interface.go
  test/framework/k8s_cluster.go
  test/framework/universal_app.go
  test/framework/universal_cluster.go
Labels: ci/run-full-matrix

#5531 test(e2e): delay processing request to trigger connection limit
  test/e2e_env/kubernetes/meshcircuitbreaker/meshcircuitbreaker.go
Labels: ci/run-full-matrix

#5536 docs(SECURITY.md): update to use GH's reports
  SECURITY.md
Labels: ci/skip-test

#5538 test(e2e): adjust probes, add delay to graceful test
  test/e2e_env/kubernetes/graceful/graceful.go
  test/framework/deployments/testserver/kubernetes.go
Labels: ci/run-full-matrix

#5537 docs: memo on how to map API to Go struct
  docs/guides/new-policies.md
Labels: ci/skip-test
