Repository kumahq/kuma, pull requests merged in 2022-11, with the labels that each got.

#5253 docs(release): created section 2.0 and upcoming release
  README.md
  UPGRADE.md
Labels: ci/skip-e2e-test

#5266 ci(commitlint): restrict some scopes
  .github/commitlint.config.js
Labels: ci/skip-test

#5271 ci(changelog): add dependabot rollup
  tools/releases/changelog/main.go
  tools/releases/changelog/root.go
Labels: ci/skip-test

#5278 ci(lint): add linter to check we run all tests
  mk/check.mk
  pkg/core/managers/apis/dataplane/dataplane_manager_suite_test.go
  pkg/core/managers/apis/dataplaneinsight/dataplane_insight_manager_suite_test.go
  pkg/core/managers/apis/zoneegressinsight/zoneegressinsight_manager_suite_test.go
  pkg/core/managers/apis/zoneingressinsight/zone_ingress_insight_manager_suite_test.go
  pkg/core/managers/apis/zoneinsight/zone_insight_manager_suite_test.go
  pkg/core/validators/validators_suite_test.go
  pkg/core/xds/inspect/suite_test.go
  pkg/core/xds/xds_suite_test.go
  pkg/plugins/runtime/gateway/match/match_test.go
  pkg/plugins/runtime/gateway/match/suite_test.go
  pkg/xds/envoy/tls/tls_suite_test.go
  pkg/xds/envoy/tls/v3/tls_suite_test.go
  pkg/xds/generator/secrets/generator.go
  pkg/xds/generator/secrets/generator_suite_test.go
  pkg/xds/generator/secrets/generator_test.go
  pkg/xds/generator/secrets/testdata/secrets/envoy-config-dataplane.golden.yaml
  pkg/xds/generator/secrets/testdata/secrets/envoy-config-egress.golden.yaml
  pkg/xds/generator/secrets/testdata/secrets/envoy-config-zipkin.golden.yaml
  pkg/xds/template/proxy_template_resolver_test.go
  pkg/xds/template/proxy_template_suite_test.go
  tools/ci/check_test_files.go
Labels: ci/skip-test

#5238 test(e2e): make k3d a default k8s tool
  .circleci/config.yml
  docs/guides/e2e-test-tips.md
  mk/e2e.new.mk
Labels: ci/run-full-matrix

#5333 docs: added MADR for MeshRateLimit
  docs/madr/decisions/011-rate-limit-policy.md
Labels: ci/skip-test

#5372 fix(kuma-cp): memory store keeps children after owner update
  pkg/plugins/resources/memory/store.go
  pkg/test/store/owner_test_template.go
  test/e2e_env/multizone/sync/sync.go
Labels: ci/run-full-matrix

#5363 ci(changelog): fix changelog script for dependabot rollups
  tools/releases/changelog/github.go
Labels: ci/skip-test

#5369 docs(MADR): mesh health check madr
  docs/madr/decisions/012-health-check-policy.md
Labels: ci/skip-test

#5385 fix(gui): correct index.html with templates
  app/kuma-ui/pkg/resources/data/index.html
  pkg/version/version_test.go
Labels: ci/skip-e2e-test
