Repository kumahq/kuma, pull requests merged in 2022-09, with the labels that each got.

#4954 chore: removes update/gui command
  mk/generate.mk
Labels: kind/cleanup

#4951 fix(*): do not override source address when TP is not enabled
  app/kuma-dp/cmd/run.go
  app/kuma-dp/pkg/dataplane/metrics/server.go
  pkg/core/resources/apis/mesh/dataplane_helpers.go
  pkg/core/resources/apis/mesh/dataplane_helpers_test.go
  pkg/xds/bootstrap/generator.go
  pkg/xds/bootstrap/generator_test.go
  pkg/xds/bootstrap/handler.go
  pkg/xds/bootstrap/parameters.go
  pkg/xds/bootstrap/types/bootstrap_response.go
  pkg/xds/generator/inbound_proxy_generator.go
  pkg/xds/generator/testdata/inbound-proxy/3-envoy-config.golden.yaml
  pkg/xds/generator/testdata/inbound-proxy/5-envoy-config.golden.yaml
  pkg/xds/generator/testdata/profile-source/1-envoy-config.golden.yaml
  pkg/xds/generator/testdata/profile-source/3-envoy-config.golden.yaml
  test/framework/interface.go
  test/framework/setup.go
  test/framework/universal_cluster.go
Labels: ci/run-full-matrix

#4973 ci: ensure makefiles can be inherited in other repos
  mk/api.mk
  mk/build.mk
  mk/dependencies/deps.lock
  mk/dev.mk
  mk/docs.mk
  mk/generate.mk
Labels: ci/run-full-matrix

#5044 ci: add possibility to run less tests
  .circleci/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  labels.yml
Labels: ci/skip-test

#5048 fix(ci): remove extra `fi` typo in circleci conf
  .circleci/config.yml
Labels: ci/skip-test
