Repository kumahq/kuma, pull requests merged in 2023-08, with the labels that each got.

#7408 fix(containerd): only build cgroups on linux
  app/kuma-dp/pkg/dataplane/cgroups/cgroups.go
Labels: ci/skip-e2e-test

#7414 chore(deps): update go from 1.20.5 to 1.20.6
  .circleci/config.yml
  .github/workflows/blackbox-tests.yaml
  .github/workflows/golangci-lint.yml
  .github/workflows/pr-comments.yaml
  .github/workflows/release.yaml
  .github/workflows/update-docs.yaml
  .github/workflows/update-insecure-dependencies.yaml
  go.mod
  go.sum
  mk/dependencies/deps.lock
  mk/dev.mk
Labels: ci/run-full-matrix, backport

#7411 chore(deps): upgrade envoy to 1.27.0
  tools/releases/version.sh
Labels: ci/run-full-matrix

#7429 chore(deps): update to go 1.20.7
  .circleci/config.yml
  .github/workflows/blackbox-tests.yaml
  .github/workflows/golangci-lint.yml
  .github/workflows/pr-comments.yaml
  .github/workflows/release.yaml
  .github/workflows/update-docs.yaml
  .github/workflows/update-insecure-dependencies.yaml
  mk/dependencies/deps.lock
  mk/dev.mk
Labels: ci/run-full-matrix

#7438 chore(logs): switch heartbeat and ping logs to debug
  pkg/intercp/catalog/heartbeat_component.go
  pkg/intercp/catalog/server.go
Labels: ci/skip-test

#7437 build(go.mod): revert containerd changes
  app/kuma-dp/pkg/dataplane/cgroups/cgroups.go
  app/kuma-dp/pkg/dataplane/envoy/memory_limit_linux.go
  go.mod
  go.sum
Labels: release-2.0

#7415 perf(zoneingress): only pick resources from proper mesh
  pkg/core/xds/types.go
  pkg/xds/context/resources.go
  pkg/xds/generator/ingress_generator.go
  pkg/xds/generator/ingress_generator_destinations.go
  pkg/xds/generator/ingress_generator_test.go
  pkg/xds/generator/testdata/ingress/01.envoy.golden.yaml
  pkg/xds/generator/testdata/ingress/03.envoy.golden.yaml
  pkg/xds/generator/testdata/ingress/04.envoy.golden.yaml
  pkg/xds/generator/testdata/ingress/05.envoy.golden.yaml
  pkg/xds/generator/testdata/ingress/meshgateway.envoy.golden.yaml
  pkg/xds/generator/testdata/ingress/with-meshhttproute.envoy.golden.yaml
  pkg/xds/ingress/outbound.go
  pkg/xds/ingress/outbound_test.go
  pkg/xds/sync/ingress_proxy_builder.go
  pkg/xds/sync/proxy_builder_test.go
Labels: ci/run-full-matrix

#7436 build(go.mod): revert containerd changes
  app/kuma-dp/pkg/dataplane/cgroups/cgroups.go
  app/kuma-dp/pkg/dataplane/envoy/memory_limit_linux.go
  go.mod
  go.sum
Labels: release-1.8

#7445 build(go.mod): revert containerd changes
  app/kuma-dp/pkg/dataplane/cgroups/cgroups.go
  app/kuma-dp/pkg/dataplane/envoy/memory_limit_linux.go
  go.mod
  go.sum
Labels: release-2.1

#7460 ci(actions): autolabel needs fetch depth 0 to be able to diff all branches
  .github/workflows/auto-backport.yaml
Labels: ci/skip-test, no-backport-autolabel

#7462 ci(actions): fix autolabel workflow
  .github/workflows/auto-backport.yaml
Labels: ci/skip-test

#7466 build(mk): remove non existent make target dep
  mk/test.mk
Labels: ci/run-full-matrix

#7464 docs(actions): update PULL_REQUEST_TEMPLATE with autolabel docs
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ci/skip-test, no-backport-autolabel

#7494 build(coredns): fix build after upstream update
  mk/build.mk
Labels: ci/run-full-matrix, release-2.1

#7490 build: fix GOENV usage
  mk/build.mk
Labels: release-2.1

#7493 chore(deps): update CoreDNS to v1.11.0
  mk/build.mk
Labels: ci/run-full-matrix

#7491 feat(insights): change metrics to milliseconds
  pkg/insights/resyncer.go
Labels: ci/skip-e2e-test

#7501 feat(rest): add service unavailable error
  pkg/core/rest/errors/error_handler.go
  pkg/core/rest/errors/errors.go
Labels: ci/skip-test

#7505 build(coredns): fix build after upstream update
  mk/build.mk
Labels: release-2.0

#7520 test(e2e): use newest gateway-api CRDs
  test/framework/k8s.go
Labels: ci/run-full-matrix

#7525 ci(lint): fail instead of fixing linter errors
  .github/workflows/golangci-lint.yml
Labels: ci/skip-test

#7526 ci(.github): more strict bash in autobackporting workflow
  tools/ci/needs_backporting.sh
Labels: ci/skip-test

#7533 chore(deps): bump go from 1.18 to 1.20
  .circleci/config.yml
  .github/workflows/pr-comments.yaml
  api/mesh/v1alpha1/gateway_route.pb.go
  api/mesh/v1alpha1/health_check.pb.go
  api/mesh/v1alpha1/kds.pb.go
  api/mesh/v1alpha1/mux.pb.go
  api/mesh/v1alpha1/proxy_template.pb.go
  api/mesh/v1alpha1/retry.pb.go
  api/mesh/v1alpha1/traffic_route.pb.go
  api/observability/v1/mads.pb.go
  api/system/v1alpha1/datasource.pb.go
  app/kumactl/cmd/install/testdata/install-transparent-proxy.excludedports.txt
  go.mod
  go.sum
  mk/build.mk
  mk/check.mk
  mk/dependencies/deps.lock
  mk/dependencies/go-deps.sh
  mk/generate.mk
  mk/run.mk
  mk/test.mk
  pkg/core/ca/issuer/issuer.go
  pkg/kds/mux/client.go
  pkg/kds/server/status_tracker.go
  pkg/plugins/ca/builtin/ca.go
  pkg/plugins/policies/meshtrafficpermission/api/v1alpha1/meshtrafficpermission.go
  pkg/plugins/runtime/gateway/gateway_route_generator_test.go
  pkg/transparentproxy/transparentproxy_experimental.go
  pkg/util/xds/v3/callbacks.go
  pkg/util/xds/v3/callbacks_chain.go
  pkg/util/xds/v3/callbacks_chain_test.go
  pkg/util/xds/v3/noop_callbacks.go
  pkg/util/xds/v3/watchdog_callbacks.go
  pkg/xds/envoy/imports.go
  pkg/xds/server/callbacks/dataplane_callbacks_test.go
  pkg/xds/server/callbacks/dataplane_lifecycle_test.go
  pkg/xds/server/callbacks/dataplane_metadata_tracker_test.go
  pkg/xds/server/callbacks/dataplane_status_tracker_test.go
  pkg/xds/server/callbacks/dataplane_sync_tracker_test.go
  pkg/xds/server/v3/resource_warming_forcer.go
  pkg/xds/server/v3/snapshot_generator_test.go
  tools/policy-gen/generator/cmd/pluginfile.go
  tools/releases/distros.sh
  tools/releases/dockerfiles/Dockerfile.kuma-init
Labels: ci/run-full-matrix, release-2.0

#7545 build(mk): include GOENV where needed
  mk/check.mk
  mk/e2e.new.mk
Labels: release-2.0

#7555 ci(mk): remove nonexistent make dependency
  mk/test.mk
Labels: release-2.0

#7542 ci(envoy): extract everything from the archive not just envoy binary
  mk/distribution.mk
Labels: ci/skip-test, ci/force-publish

#7570 chore(logging): switch updating a resource log to debug
  pkg/kds/store/sync.go
  pkg/kds/v2/store/sync.go
Labels: ci/skip-test

#7572 fix(metrics): hijacker should not pass accept-encoding
  app/kuma-dp/pkg/dataplane/metrics/server.go
Labels: backport

#7564 test(e2e): do not use unsafe delete
  test/e2e_env/kubernetes/gateway/cross-mesh.go
  test/e2e_env/universal/gateway/utils.go
  test/e2e_env/universal/healthcheck/panic.go
  test/e2e_env/universal/meshhealthcheck/panic.go
  test/e2e_env/universal/meshretry/grpc.go
  test/e2e_env/universal/meshretry/http.go
  test/e2e_env/universal/retry/retry.go
  test/framework/envs/kubernetes/env.go
  test/framework/envs/multizone/env.go
  test/framework/envs/universal/env.go
  test/framework/gateway.go
  test/framework/k8s_cluster.go
  test/framework/universal_cluster.go
Labels: ci/run-full-matrix

#7587 feat(e2e): fix metrics tls test
  .golangci.yml
  pkg/api-server/auth_test.go
  test/e2e_env/kubernetes/gateway/resources.go
  test/e2e_env/universal/observability/metrics.go
Labels: ci/run-full-matrix

#7593 fix(kuma-cp): universal mode don't log on every lock acquire attempt
  pkg/plugins/leader/plugin.go
  pkg/plugins/leader/postgres/leader_elector.go
Labels: release-2.4

#7621 chore(release): merge release-2.4
  api/system/v1alpha1/zone_insight.pb.go
  api/system/v1alpha1/zone_insight.proto
  docs/generated/kuma-cp.md
  docs/generated/raw/kuma-cp.yaml
  pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
  pkg/config/plugins/runtime/k8s/config.go
  pkg/kds/server/status_tracker.go
  pkg/plugins/leader/plugin.go
  pkg/plugins/leader/postgres/leader_elector.go
Labels: ci/run-full-matrix
