Repository kumahq/kuma, pull requests merged in 2023-07, with the labels that each got.

#7180 ci(.github): fix update-docs job
  .github/workflows/update-docs.yaml
Labels: ci/skip-test

#7184 fix(helm): due to a bug in checkout action we need to use github.sha
  .github/workflows/helm-release.yaml
Labels: ci/skip-test

#7179 fix(kuma-cp): handle external services with permissive mtls
  pkg/xds/context/mesh_context_builder.go
  test/e2e_env/kubernetes/externalservices/permissive_mtls.go
  test/e2e_env/kubernetes/kubernetes_suite_test.go
Labels: backport

#7230 fix(kuma-cp): put metadata xds callbacks before sync
  pkg/xds/server/v3/components.go
Labels: ci/run-full-matrix

#7221 fix(kuma-cp): cancel OnTick when watchdog stopped
  pkg/hds/tracker/callbacks.go
  pkg/hds/tracker/healthcheck_generator.go
  pkg/hds/tracker/healthcheck_generator_test.go
  pkg/hds/tracker/reconciler.go
  pkg/kds/server/components.go
  pkg/kds/v2/server/components.go
  pkg/mads/v1/service/components.go
  pkg/util/watchdog/watchdog.go
  pkg/util/watchdog/watchdog_test.go
  pkg/xds/sync/dataplane_watchdog_factory.go
Labels: ci/run-full-matrix

#7231 fix(kuma-cp): pass context via snapshot reconciler to generateCerts
  pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/plugin_test.go
  pkg/plugins/policies/meshcircuitbreaker/plugin/v1alpha1/plugin_test.go
  pkg/plugins/policies/meshfaultinjection/plugin/v1alpha1/plugin_test.go
  pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/plugin_test.go
  pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/plugin_test.go
  pkg/plugins/policies/meshratelimit/plugin/v1alpha1/plugin_test.go
  pkg/plugins/policies/meshretry/plugin/v1alpha1/plugin_test.go
  pkg/plugins/policies/meshtimeout/plugin/v1alpha1/plugin_test.go
  pkg/plugins/runtime/gateway/gateway_route_generator_test.go
  pkg/plugins/runtime/gateway/generator.go
  pkg/plugins/runtime/gateway/listener_generator_test.go
  pkg/test/xds/secrets.go
  pkg/xds/generator/admin_proxy_generator.go
  pkg/xds/generator/admin_proxy_generator_test.go
  pkg/xds/generator/core/resource_generator.go
  pkg/xds/generator/direct_access_proxy_generator.go
  pkg/xds/generator/direct_access_proxy_generator_test.go
  pkg/xds/generator/dns_generator.go
  pkg/xds/generator/dns_generator_test.go
  pkg/xds/generator/egress/external_services_generator.go
  pkg/xds/generator/egress/generator.go
  pkg/xds/generator/egress/generator_test.go
  pkg/xds/generator/egress/internal_services_generator.go
  pkg/xds/generator/inbound_proxy_generator.go
  pkg/xds/generator/inbound_proxy_generator_test.go
  pkg/xds/generator/ingress_generator.go
  pkg/xds/generator/ingress_generator_test.go
  pkg/xds/generator/outbound_proxy_generator.go
  pkg/xds/generator/outbound_proxy_generator_test.go
  pkg/xds/generator/probe_generator.go
  pkg/xds/generator/probe_generator_test.go
  pkg/xds/generator/prometheus_endpoint_generator.go
  pkg/xds/generator/prometheus_endpoint_generator_test.go
  pkg/xds/generator/proxy_template.go
  pkg/xds/generator/proxy_template_profile_source_test.go
  pkg/xds/generator/proxy_template_test.go
  pkg/xds/generator/secrets/generator.go
  pkg/xds/generator/secrets/generator_test.go
  pkg/xds/generator/tracing_proxy_generator.go
  pkg/xds/generator/tracing_proxy_generator_test.go
  pkg/xds/generator/transparent_proxy_generator.go
  pkg/xds/generator/transparent_proxy_generator_test.go
  pkg/xds/secrets/secrets.go
  pkg/xds/secrets/secrets_test.go
  pkg/xds/server/v3/reconcile.go
  pkg/xds/server/v3/reconcile_test.go
  pkg/xds/server/v3/snapshot_generator_test.go
  pkg/xds/sync/dataplane_watchdog.go
  pkg/xds/sync/dataplane_watchdog_test.go
  pkg/xds/sync/interfaces.go
Labels: ci/run-full-matrix

#7262 chore(deps): bump envoy to 1.24.9
  tools/releases/version.sh
Labels: ci/run-full-matrix, release-1.8

#7263 chore(deps): bump envoy to 1.24.9
  tools/releases/version.sh
Labels: ci/run-full-matrix, release-2.0

#7264 chore(deps): bump envoy to 1.24.9
  tools/releases/version.sh
Labels: ci/run-full-matrix, release-2.1

#7265 chore(deps): bump envoy to 1.25.8
  tools/releases/version.sh
Labels: ci/run-full-matrix, release-2.2

#7266 chore(deps): bump envoy to 1.26.3
  tools/releases/version.sh
Labels: ci/run-full-matrix, release-2.3

#7278 ci(tracing): add span.type attribute to pgx tracer
  pkg/plugins/resources/postgres/pgx_store.go
Labels: ci/skip-test

#7280 chore(kuma-dp): fix missing type in accesslogs streamer on windows
  app/kuma-dp/pkg/dataplane/accesslogs/streamer_windows.go
Labels: ci/skip-test

#7277 ci(mk): update kind k8s version to v1.22
  mk/kind.mk
Labels: ci/run-full-matrix

#7281 ci(.github): move changelog versions.yaml in a `raw` dir
  .github/workflows/update-docs.yaml
Labels: ci/skip-test

#7276 feat(kuma-dp): don't require NET_BIND_SERVICE capability
  pkg/plugins/runtime/k8s/controllers/gateway_instance_controller.go
  tools/releases/dockerfiles/envoy.Dockerfile
Labels: ci/run-full-matrix

#7282 fix(kuma-cp): don't fail when 2 headless services pointing to the same service
  pkg/dns/vips/virtual_outbound_view.go
  pkg/dns/vips_allocator_test.go
Labels: ci/run-full-matrix, backport

#7297 fix(kumactl): treat 404 as resource not found error
  pkg/plugins/resources/remote/store.go
Labels: backport

#7311 fix(dist): ensure rel flags are flags
  mk/distribution.mk
Labels: backport

#7324 test(e2e): switch to tproxy v2 by default
  test/framework/interface.go
Labels: ci/run-full-matrix

#7339 ci(e2e): fix meshretry test
  test/e2e_env/universal/meshretry/http.go
Labels: ci/run-full-matrix

#7325 test(e2e): exclude outbound ports for uid
  test/e2e_env/kubernetes/connectivity/exclude_outbound_port.go
  test/e2e_env/kubernetes/kubernetes_suite_test.go
  test/framework/deployments/testserver/deployment.go
  test/framework/deployments/testserver/kubernetes.go
Labels: ci/run-full-matrix

#7348 fix(kuma-cp): don't leak goroutine on every tick in SimpleWatchdog
  pkg/util/watchdog/watchdog.go
Labels: ci/run-full-matrix, backport

#7333 fix(kuma-cp): order resources for building VIPs
  pkg/dns/vips_allocator.go
Labels: backport

#7363 chore(deps): upgrade envoy to 1.24.10
  tools/releases/version.sh
Labels: ci/run-full-matrix, release-2.1

#7368 chore(deps): upgrade envoy to 1.26.4
  tools/releases/version.sh
Labels: ci/run-full-matrix, release-2.3

#7366 chore(deps): upgrade envoy to 1.25.9
  tools/releases/version.sh
Labels: ci/run-full-matrix, release-2.2

#7367 chore(deps): upgrade envoy to 1.26.4
  tools/releases/version.sh
Labels: ci/run-full-matrix

#7364 chore(deps): upgrade envoy to 1.24.10
  tools/releases/version.sh
Labels: ci/run-full-matrix, release-2.0

#7365 chore(deps): upgrade envoy to 1.24.10
  tools/releases/version.sh
Labels: ci/run-full-matrix, release-1.8

#7374 test(gatewayapi): run conformance tests with profiles
  .golangci.yml
  mk/build.mk
  test/e2e/gateway/gatewayapi/conformance_test.go
Labels: ci/run-full-matrix

#7387 fix(sec): get rid of dependency on containerd
  app/kuma-dp/pkg/dataplane/cgroups/cgroups.go
  app/kuma-dp/pkg/dataplane/envoy/memory_limit_linux.go
  go.mod
  go.sum
Labels: ci/run-full-matrix, backport

#7402 ci(check): show git diff if changes exist
  mk/check.mk
Labels: ci/skip-test
