Repository kumahq/kuma, pull requests merged in 2023-04, with the labels that each got.

#6348 feat(meshgateway): create MADR for deployment customization
  docs/madr/decisions/023-gateway-custom-deploy.md
Labels: ci/skip-test

#6421 ci(health): use ci-tools to get active-branches and versions
  .github/workflows/lifecycle.yml
  .github/workflows/release.yaml
  README.md
  UPGRADE.md
  mk/dev.mk
  tools/dev/repo-health.go
Labels: ci/skip-test

#6457 fix(conf): add more validation to postgres strore config
  pkg/config/plugins/resources/postgres/config.go
  pkg/config/plugins/resources/postgres/config_test.go
Labels: ci/skip-e2e-test

#6474 docs(CONTRIBUTING.md): clarify feat and fix in commit types
  CONTRIBUTING.md
Labels: ci/skip-test

#6483 chore(deps): upgrade envoy to v1.22.10
  mk/envoy.mk
  tools/releases/version.sh
Labels: release-2.1

#6488 chore(ci): bump envoy to 1.22.10 envoy/version.sh
  tools/envoy/version.sh
Labels: area/ci-cd, ci/skip-test, ci/auto-merge, release-2.0

#6487 ci(.github): fix schedule for release.yaml
  .github/workflows/release.yaml
Labels: ci/skip-test

#6506 ci(.github): fix invalid syntax in release.yaml
  .github/workflows/release.yaml
Labels: ci/skip-test

#6528 ci(distributions): avoid adding `.` to tar
  mk/distribution.mk
Labels: ci/force-publish

#6564 ci(lifecycle): meta_repo.yaml to meta_repo.yml
  meta_repo.yml
Labels: ci/skip-test

#6565 ci(mk): don't rebuild distributions in publish
  .circleci/config.yml
  mk/build.mk
Labels: ci/run-full-matrix

#6346 feat(retry): create MADR for host selection
  docs/madr/decisions/022-retry-host-selection.md
Labels: ci/skip-test

#6550 chore(e2e): changed order of defer
  test/e2e/compatibility/cp_compatibility_kubernetes_multizone.go
  test/e2e/trafficpermission/kubernetes/traffic_permission_k8s.go
Labels: ci/run-full-matrix

#6571 ci(circleci): use docker build job instead of vm
  .circleci/config.yml
  test/dockerfiles/universal.Dockerfile
  test/e2e_env/universal/mtls/mtls.go
Labels: ci/run-full-matrix

#6366 test(e2e): use different KDS port
  test/framework/constants.go
  test/framework/interface.go
  test/framework/k8s_controlplane.go
  test/framework/setup.go
Labels: ci/run-full-matrix

#6581 ci(tests): add container structure tests
  .circleci/config.yml
  Makefile
  mk/dependencies/container-structure-test.sh
  mk/dependencies/deps.lock
  mk/dev.mk
  mk/test-container-structure.mk
  tools/container-structure-test/kuma-cni.yaml
  tools/container-structure-test/kuma-cp.yaml
  tools/container-structure-test/kuma-dp.yaml
  tools/container-structure-test/kuma-init.yaml
  tools/container-structure-test/kumactl.yaml
Labels: ci/run-full-matrix

#6614 chore(deps): bump gateway-api to v0.7.0 prerelease
  go.mod
  go.sum
  pkg/plugins/runtime/k8s/controllers/gatewayapi/attachment/attachment_test.go
  pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_conversion.go
  test/e2e/gateway/gatewayapi/conformance_test.go
Labels: ci/run-full-matrix

#6563 feat(GatewayAPI): initial GAMMA support
  pkg/plugins/runtime/k8s/controllers/gatewayapi/attachment/attachment.go
  pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_controller.go
  pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_conversion.go
  pkg/plugins/runtime/k8s/controllers/gatewayapi/mesh_http_route_conversion.go
  pkg/plugins/runtime/k8s/controllers/inbound_converter.go
  pkg/plugins/runtime/k8s/util/util.go
  pkg/plugins/runtime/k8s/util/util_test.go
  test/e2e/gateway/gatewayapi/conformance_test.go
Labels: ci/run-full-matrix

#6631 test(e2e): remove framework.Clusters interface and its implems
  test/e2e/externalservices/localityawarelb_multizone/locality_multizone_hybrid.go
  test/e2e/helm/kuma_helm_deploy_global_zone.go
  test/e2e/resilience/resilience_multizone_k8s.go
  test/e2e/trafficpermission/kubernetes/traffic_permission_k8s.go
  test/e2e/zoneegress/externalservices/zoneegress_externalservices_hybrid.go
  test/framework/constants.go
  test/framework/interface.go
  test/framework/k8s_clusters.go
  test/framework/universal_clusters.go
Labels: ci/run-full-matrix
