Repository kumahq/kuma, pull requests merged in 2023-06, with the labels that each got.

#6889 chore(image/kuma-init): update iptables depencendy version
  tools/releases/dockerfiles/kuma-init.Dockerfile
Labels: ci/skip-test, backport

#6898 chore(gateway): remove deprecated envoy APIs from route configurers
  pkg/plugins/runtime/gateway/route/configurers.go
  pkg/plugins/runtime/gateway/testdata/http/05-gateway-route.yaml
  pkg/plugins/runtime/gateway/testdata/http/06-gateway-route.yaml
  pkg/plugins/runtime/gateway/testdata/http/09-gateway-route.yaml
  pkg/plugins/runtime/gateway/testdata/http/10-gateway-route.yaml
  pkg/plugins/runtime/gateway/testdata/http/11-gateway-route.yaml
  pkg/plugins/runtime/gateway/testdata/http/13-gateway-route.yaml
  pkg/plugins/runtime/gateway/testdata/http/drop-prefix-gateway-route.yaml
  pkg/plugins/runtime/gateway/testdata/http/response-header-set-gateway-route.yaml
  pkg/plugins/runtime/gateway/testdata/http/rewrite-prefix-gateway-route.yaml
  pkg/plugins/runtime/gateway/testdata/http/rewrite-prefix-trailing-gateway-route.yaml
  pkg/plugins/runtime/gateway/testdata/https/05-gateway-route.yaml
  pkg/plugins/runtime/gateway/testdata/https/06-gateway-route.yaml
  pkg/plugins/runtime/gateway/testdata/https/09-gateway-route.yaml
  pkg/plugins/runtime/gateway/testdata/https/10-gateway-route.yaml
  pkg/plugins/runtime/gateway/testdata/https/11-gateway-route.yaml
  pkg/plugins/runtime/gateway/testdata/https/13-gateway-route.yaml
  pkg/plugins/runtime/gateway/testdata/https/drop-prefix-gateway-route.yaml
  pkg/plugins/runtime/gateway/testdata/https/response-header-set-gateway-route.yaml
  pkg/plugins/runtime/gateway/testdata/https/rewrite-prefix-gateway-route.yaml
  pkg/plugins/runtime/gateway/testdata/https/rewrite-prefix-trailing-gateway-route.yaml
Labels: kind/cleanup, area/gateway

#6896 fix(gateway): don't skip retry policy with retry methods
  pkg/plugins/runtime/gateway/route/configurers.go
Labels: kind/bug, area/gateway, backport

#6895 refactor(xds/builders): remove redundant structures
  pkg/plugins/policies/xds/testutil.go
  pkg/test/xds/name_configurer.go
  pkg/xds/envoy/clusters/cluster_builder.go
  pkg/xds/envoy/clusters/configurers.go
  pkg/xds/envoy/listeners/filter_chain_builder.go
  pkg/xds/envoy/listeners/listener_builder.go
  pkg/xds/envoy/routes/route_configuration_builder.go
  pkg/xds/envoy/routes/virtual_host_builder.go
Labels: kind/cleanup

#6912 chore(deps): bump gateway-api with conformance test fixes
  go.mod
  go.sum
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/listeners.go
Labels: ci/run-full-matrix

#6917 docs(readme): updating links in README
  README.md
Labels: ci/skip-test

#6934 fix(kuma-cp): wait for zone to create insights with admin streams
  pkg/intercp/envoyadmin/forwarding_kds_client.go
  pkg/kds/service/server.go
Labels: ci/run-full-matrix

#6940 perf(k8s): omit fetching other dataplanes when vips are in the config map
  pkg/plugins/runtime/k8s/controllers/pod_controller.go
Labels: ci/run-full-matrix, ci/force-publish

#6950 ci(mk): disable pager in `make check`
  mk/check.mk
Labels: ci/skip-test

#6959 chore(deps): bump golang from 1.20.4 to 1.20.5
  .circleci/config.yml
  .github/workflows/blackbox-tests.yaml
  .github/workflows/pr-comments.yaml
  .github/workflows/release.yaml
  .github/workflows/update-insecure-dependencies.yaml
  mk/dependencies/deps.lock
  mk/dev.mk
Labels: backport

#6967 chore(deps): upgrade envoy to 1.25.7
  tools/releases/version.sh
Labels: ci/run-full-matrix, release-2.2

#6995 ci(makefile): build platform dependent tools
  mk/generate.mk
Labels: ci/skip-test, ci/skip-e2e-test

#7010 feat(kuma-cp): add possibility to configure concurrent reconciliation…
  docs/generated/kuma-cp.md
  pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
  pkg/config/loader_test.go
  pkg/config/plugins/runtime/k8s/config.go
  pkg/config/plugins/runtime/k8s/testdata/default-config.golden.yaml
  pkg/plugins/runtime/k8s/controllers/pod_controller.go
  pkg/plugins/runtime/k8s/plugin.go
Labels: ci/run-full-matrix

#7020 chore(deps): bump gateway-api with more conformance tests
  go.mod
  go.sum
  test/framework/k8s.go
Labels: ci/run-full-matrix

#6969 chore(deps): upgrade envoy to 1.24.8
  Makefile
  mk/build.mk
  mk/docker.mk
  mk/envoy.mk
  test/dockerfiles/Dockerfile.universal
  tools/envoy/Dockerfile.build-centos
  tools/envoy/Dockerfile.build-centos.dockerignore
  tools/envoy/Dockerfile.build-ubuntu
  tools/envoy/Dockerfile.build-ubuntu.dockerignore
  tools/envoy/README.md
  tools/envoy/build_centos.sh
  tools/envoy/build_darwin.sh
  tools/envoy/build_linux.sh
  tools/envoy/contrib_enabled_matrix.py
  tools/envoy/fetch.sh
  tools/envoy/fetch_sources.sh
  tools/envoy/publish.sh
  tools/releases/distros.sh
  tools/releases/docker.sh
  tools/releases/dockerfiles/Dockerfile.envoy
  tools/releases/version.sh
Labels: ci/run-full-matrix, release-2.1

#6968 chore(deps): upgrade envoy to 1.24.8
  Makefile
  mk/build.mk
  mk/dependencies/deps.lock
  mk/dev.mk
  mk/docker.mk
  mk/envoy.mk
  test/dockerfiles/Dockerfile.universal
  test/e2e_env/universal/healthcheck/policy.go
  tools/envoy/Dockerfile.build-centos
  tools/envoy/Dockerfile.build-centos.dockerignore
  tools/envoy/Dockerfile.build-ubuntu
  tools/envoy/Dockerfile.build-ubuntu.dockerignore
  tools/envoy/README.md
  tools/envoy/build_centos.sh
  tools/envoy/build_darwin.sh
  tools/envoy/build_linux.sh
  tools/envoy/contrib_enabled_matrix.py
  tools/envoy/fetch.sh
  tools/envoy/fetch_sources.sh
  tools/envoy/publish.sh
  tools/envoy/version.sh
  tools/releases/distros.sh
  tools/releases/docker.sh
  tools/releases/dockerfiles/Dockerfile.kuma-dp
  tools/releases/version.sh
Labels: ci/run-full-matrix, release-2.0

#6966 chore(deps): upgrade envoy to 1.24.8
  Makefile
  mk/build.mk
  mk/docker.mk
  mk/envoy.mk
  test/dockerfiles/Dockerfile.universal
  tools/envoy/Dockerfile.build-centos
  tools/envoy/Dockerfile.build-centos.dockerignore
  tools/envoy/Dockerfile.build-ubuntu
  tools/envoy/Dockerfile.build-ubuntu.dockerignore
  tools/envoy/README.md
  tools/envoy/build_centos.sh
  tools/envoy/build_darwin.sh
  tools/envoy/build_linux.sh
  tools/envoy/contrib_enabled_matrix.py
  tools/envoy/fetch.sh
  tools/envoy/fetch_sources.sh
  tools/envoy/publish.sh
  tools/envoy/version.sh
  tools/releases/distros.sh
  tools/releases/docker.sh
  tools/releases/dockerfiles/Dockerfile.kuma-dp
  tools/releases/version.sh
Labels: ci/run-full-matrix, release-1.8

#7071 feat(rest): add conflict error
  pkg/core/rest/errors/error_handler.go
  pkg/core/rest/errors/errors.go
Labels: ci/skip-test

#6920 chore(community): update governance.md
  CODEOWNERS
  GOVERNANCE.md
  OWNERS.md
Labels: ci/skip-test

#7077 ci(.github): ignore sync of CONTRIBUTING.md
  .github/workflows/lifecycle.yml
Labels: ci/skip-test

#7088 fix(kuma-cp): add backward compatible reading of virtual outbound from config
  docs/generated/kuma-cp.md
  pkg/config/app/kuma-cp/config.go
  pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
  pkg/dns/vips/persistence.go
  pkg/dns/vips/persistence_test.go
Labels: ci/run-full-matrix

#7102 fix(kuma-cp): do not require certs on https api port
  pkg/api-server/server.go
Labels: backport

#7126 ci(.mergify): remove mergify config file
  .mergify.yml
Labels: ci/skip-test

#7135 feat(e2e): add possibility to configure kubeconfig location in e2e test cluster
  test/framework/k8s_cluster.go
Labels: ci/skip-test

#7133 fix(k8s): tolerate unknown `appProtocol`
  pkg/plugins/runtime/k8s/controllers/inbound_converter.go
  pkg/plugins/runtime/k8s/controllers/pod_converter_test.go
  pkg/plugins/runtime/k8s/controllers/testdata/01.dataplane.yaml
  pkg/plugins/runtime/k8s/controllers/testdata/10.dataplane.yaml
  pkg/plugins/runtime/k8s/controllers/testdata/11.dataplane.yaml
Labels: ci/run-full-matrix

#7146 ci(docs): add `make docs/output` to copy all raw docs
  mk/dependencies/deps.lock
  mk/dependencies/go-deps.sh
  mk/dev.mk
  mk/docs.mk
Labels: ci/skip-test, backport

#7154 ci(.github): add job to update spec files in docs repo
  .github/workflows/update-docs.yaml
Labels: ci/skip-test
