Repository kumahq/kuma, pull requests merged in 2023-01, with the labels that each got.

#5504 docs: mesh proxy patch madr
  docs/madr/decisions/017-mesh-proxy-patch.md
Labels: ci/skip-test, ci/skip-e2e-test

#5573 chore: do not hide errors when generating policy
  mk/generate.mk
Labels: ci/skip-e2e-test

#5660 ci: include all release branches in auto-merge actions
  .github/workflows/auto-merge.yaml
Labels: ci/skip-test

#5665 fix syntax errors
  README.md
Labels: ci/skip-test

#5677 feat: allow injecting env from parent projects
  deployments/charts/kuma/templates/_helpers.tpl
Labels: ci/skip-e2e-test

#5666 docs: add ci/cd to backporting policy
  CONTRIBUTING.md
Labels: ci/skip-test

#5679 test(e2e): disable compatibility tests on arm
  test/e2e_env/universal/universal_suite_test.go
Labels: ci/run-full-matrix

#5676 test(e2e): move all universal multizone tests into e2e_env
  test/e2e/deploy/e2e_suite_test.go
  test/e2e/externalservices/e2e_suite_test.go
  test/e2e/ownership/e2e_suite_test.go
  test/e2e/resilience/e2e_suite_test.go
  test/e2e_env/multizone/externalservices/externalservices_multizone_universal.go
  test/e2e_env/multizone/multizone_suite_test.go
  test/e2e_env/multizone/ownership/ownership.go
  test/e2e_env/multizone/resilience/resilience_multizone_universal.go
  test/e2e_env/multizone/resilience/resilience_multizone_universal_postgres.go
  test/e2e_env/multizone/zonedisable/zone_disable.go
Labels: ci/run-full-matrix

#5715 ci(.github): auto merge and skip tests for changelog changes
  .github/workflows/update-changelog.yaml
Labels: ci/skip-test

#5608 docs(MADR): create fault injection MADR
  docs/madr/decisions/018-fault-injection-policy.md
Labels: ci/skip-test

#5734 feat(security): update security updates time
  .github/dependabot.yml
Labels: ci/skip-test

#5728 ci(CHANGELOG.md): improve excluded patterns for commits
  tools/releases/changelog/github.go
Labels: ci/skip-test

#5746 chore(policy): add files missing from master
  docs/generated/cmd/kumactl/kumactl_get_meshhttproute.md
  docs/generated/cmd/kumactl/kumactl_get_meshhttproutes.md
  docs/generated/cmd/kumactl/kumactl_inspect_meshhttproute.md
Labels: ci/skip-test

#5748 fix(lint): make check target fail if there are untracked files
  mk/check.mk
Labels: ci/skip-test

#5758 feat(build): automatically apply security updates for release branches
  .github/workflows/update-insecure-dependencies.yaml
Labels: ci/skip-test

#5767 feat(build): revert scan output and add matrix branch to title
  .github/workflows/update-insecure-dependencies.yaml
Labels: ci/skip-test

#5778 feat(build): disable fail fast
  .github/workflows/update-insecure-dependencies.yaml
Labels: ci/skip-test

#5783 feat(build): add regex disable for packages in security update
  .github/workflows/update-insecure-dependencies.yaml
Labels: ci/skip-test

#5786 chore: remove dependabot branch updates since they do not work
  .github/dependabot.yml
Labels: ci/skip-test

#5813 chore(release): update readme file
  README.md
  UPGRADE.md
Labels: ci/skip-test

#5816 chore: fix version sh pipe exit
  tools/releases/version.sh
Labels: ci/skip-test

#5809 chore: fix file not found
  tools/envoy/fetch.sh
Labels: ci/skip-test

#5821 fix(kuma-cp): kds deadlock in unit tests
  pkg/test/grpc/serverstream.go
Labels: ci/skip-e2e-test

#5820 fix(kuma-cp): fix the way how we set FractionalPercent in envoy
  pkg/plugins/policies/meshfaultinjection/plugin/v1alpha1/testdata/basic_listener_1.golden.yaml
  pkg/plugins/policies/meshfaultinjection/plugin/v1alpha1/testdata/gateway_basic_listener.golden.yaml
  pkg/plugins/runtime/gateway/testdata/http/04-gateway-route.yaml
  pkg/plugins/runtime/gateway/testdata/http/06-gateway-route.yaml
  pkg/plugins/runtime/gateway/testdata/https/04-gateway-route.yaml
  pkg/plugins/runtime/gateway/testdata/https/06-gateway-route.yaml
  pkg/xds/envoy/listeners/v3/fault_injection_configurer_test.go
  pkg/xds/envoy/listeners/v3/util.go
  pkg/xds/envoy/listeners/v3/util_test.go
Labels: breaking-change

#5829 ci: add action to automatically update README badges
  .github/workflows/lifecycle.yml
  .github/workflows/update-changelog.yaml
  .github/workflows/update-insecure-dependencies.yaml
  README.md
  active-branches.json
  mk/dev.mk
  tools/dev/repo-health.go
Labels: ci/skip-test

#5833 ci(.github): fix bad if in refresh-active-releases
  .github/workflows/lifecycle.yml
Labels: ci/skip-test

#5836 chore: change gateway log to V1
  pkg/plugins/runtime/gateway/cluster_generator.go
Labels: ci/skip-e2e-test

#5862 ci(.github): fix update-insecure-dependencies matrix
  .github/workflows/update-insecure-dependencies.yaml
Labels: ci/skip-test
