Repository kumahq/kuma, pull requests merged in 2023-11, with the labels that each got.

#8156 fix(MeshGateway): ensure that duplicate listeners are not added when crossMesh is enabled on a listener and Routes specify hostnames
  pkg/plugins/runtime/gateway/filter_chain_generator.go
  pkg/plugins/runtime/gateway/gateway_route_generator_test.go
  pkg/plugins/runtime/gateway/testdata/http/cross-mesh-gateway.yaml
  pkg/plugins/runtime/gateway/testdata/https/cross-mesh-gateway.yaml
Labels: ci/run-full-matrix

#8150 chore(deps): bump sigs.k8s.io/gateway-api from v0.8.1 to v1.0.0
  UPGRADE.md
  deployments/charts/kuma/templates/gateway-class.yaml
  go.mod
  go.sum
  pkg/plugins/runtime/k8s/controllers/gatewayapi/attachment/attachment.go
  pkg/plugins/runtime/k8s/controllers/gatewayapi/attachment/attachment_test.go
  pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_class_controller.go
  pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_controller.go
  pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_conversion.go
  pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_conversion_test.go
  pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_status.go
  pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_controller.go
  pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_conversion.go
  pkg/plugins/runtime/k8s/controllers/gatewayapi/mesh_http_route_conversion.go
  pkg/plugins/runtime/k8s/controllers/pod_controller_test.go
  pkg/plugins/runtime/k8s/controllers/pod_converter_test.go
  test/e2e/gateway/gatewayapi/conformance_test.go
  test/e2e_env/kubernetes/gateway/gatewayapi.go
  test/framework/k8s.go
Labels: ci/run-full-matrix

#8246 test(e2e): revert implementation of delete deployment for test-server
  test/e2e_env/multizone/localityawarelb/locality_aware_multizone_hybrid.go
  test/framework/deployments/testserver/kubernetes.go
Labels: ci/run-full-matrix

#8252 chore(metrics): do not shorten commit in basedOnKuma cp_metric
  pkg/version/version.go
Labels: ci/skip-test

#8255 chore(kuma-cp): fix incorrect conversion between integer types
  pkg/plugins/policies/meshretry/plugin/xds/configurer.go
Labels: ci/skip-test

#8270 chore(deps): update gateway-api
  go.mod
  go.sum
Labels: release-2.5

#8282 fix(kuma-dp): fix build
  app/kuma-dp/pkg/dataplane/command/build_command_windows.go
Labels: ci/skip-test

#8262 feat(kds): enable delta by default
  .circleci/config.yml
  UPGRADE.md
  app/kumactl/cmd/install/testdata/install-control-plane.dump-values.yaml
  deployments/charts/kuma/README.md
  deployments/charts/kuma/templates/_helpers.tpl
  deployments/charts/kuma/values.yaml
  docs/generated/kuma-cp.md
  docs/generated/raw/helm-values.yaml
  docs/generated/raw/kuma-cp.yaml
  pkg/config/app/kuma-cp/config.go
  pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
  test/e2e/compatibility/cp_compatibility_kubernetes_multizone.go
  test/e2e/compatibility/e2e_suite_test.go
  test/e2e/helm/e2e_suite_test.go
  test/e2e/helm/kuma_helm_deploy_global_zone.go
  test/e2e/helm/kuma_helm_upgrade.go
  test/framework/config.go
Labels: ci/run-full-matrix

#8319 fix(kuma-cni): support port exclusion for UIDs
  app/cni/pkg/cni/annotations.go
  app/cni/pkg/cni/annotations_test.go
  app/cni/pkg/cni/injector_linux.go
  pkg/transparentproxy/kubernetes/kubernetes.go
  pkg/transparentproxy/transparentproxy_v2.go
  test/e2e/cni/e2e_suite_test.go
  test/e2e/cni/exclude_outbound_port.go
Labels: ci/run-full-matrix

#8341 chore(deps): update go to 1.21.4
  .circleci/config.yml
  go.mod
Labels: backport

#8342 ci(actions): make security update work with go updates
  tools/ci/update-vulnerable-dependencies.sh
Labels: area/ci-cd, ci/skip-test

#8347 chore(deps): bump the go-opentelemetry-io group with 3 updates
  go.mod
  go.sum
  pkg/kds/mux/server.go
Labels: ci/run-full-matrix, backport

#8356 test(gui): fix gui test not working on branches that start with release-x.y*
  pkg/api-server/gui_handler_test.go
Labels: ci/skip-e2e-test

#8360 ci(actions): add the 'build-test-distribute' GitHub Action, label switches supported
  .github/workflows/build-test-distribute.yaml
Labels: ci/skip-test, no-backport-autolabel

#8330 fix(observability): add annotation to make observability while running CNI work
  app/kumactl/cmd/install/testdata/install-observability.defaults.golden.yaml
  app/kumactl/cmd/install/testdata/install-observability.no-jaeger.golden.yaml
  app/kumactl/cmd/install/testdata/install-observability.no-loki.golden.yaml
  app/kumactl/cmd/install/testdata/install-observability.no-prometheus.golden.yaml
  app/kumactl/cmd/install/testdata/install-observability.overrides.golden.yaml
  app/kumactl/data/install/k8s/metrics/grafana/grafana.yaml
  pkg/api-server/testdata/inspect/empty_resources_dataplanes.golden.json
  pkg/api-server/testdata/inspect/match_mesh_dataplanes.golden.json
  pkg/api-server/testdata/inspect/match_meshservice_dataplanes.golden.json
  pkg/api-server/testdata/inspect/meshgateway_dataplanes.golden.json
  pkg/api-server/testdata/inspect/meshgatewayroute_dataplanes.golden.json
  pkg/api-server/testdata/inspect/meshhttproute_absent_dataplanes.golden.json
  pkg/api-server/testdata/inspect/meshhttproute_dataplanes.golden.json
  pkg/api-server/testdata/inspect/meshtimeouthttproute.golden.json
  pkg/api-server/testdata/inspect/namefilter_dataplanes.golden.json
  pkg/api-server/testdata/inspect/pagination_dataplanes.golden.json
  pkg/api-server/testdata/inspect/policy_not_found_dataplanes.golden.json
  pkg/api-server/testdata/inspect/proxytemplate_dataplanes.golden.json
  pkg/api-server/testdata/inspect/retry_dataplanes.golden.json
  pkg/plugins/policies/core/matchers/testdata/matchedpolicies/dataplanepolicies/06.golden.yaml
Labels: ci/skip-e2e-test

#8311 test(lb): use concurrecny 1 for lb test
  test/framework/envs/multizone/env.go
  test/framework/setup.go
  test/framework/universal_app.go
  test/framework/universal_cluster.go
Labels: ci/run-full-matrix

#8371 chore(backport): merge release-2.5 to master
  test/framework/envs/multizone/env.go
  test/framework/setup.go
  test/framework/universal_app.go
  test/framework/universal_cluster.go
Labels: ci/skip-e2e-test

#8372 fix(observability): change Grafana container UID to be different from initContainer UID
  app/kumactl/cmd/install/testdata/install-observability.defaults.golden.yaml
  app/kumactl/cmd/install/testdata/install-observability.no-jaeger.golden.yaml
  app/kumactl/cmd/install/testdata/install-observability.no-loki.golden.yaml
  app/kumactl/cmd/install/testdata/install-observability.no-prometheus.golden.yaml
  app/kumactl/cmd/install/testdata/install-observability.overrides.golden.yaml
  app/kumactl/data/install/k8s/metrics/grafana/grafana.yaml
Labels: ci/skip-e2e-test

#8378 ci(actions): fix helm release
  .github/workflows/helm-release.yaml
Labels: ci/skip-test

#8380 ci(actions): fix helm release by not specifying repostiory scope
  .github/workflows/helm-release.yaml
Labels: ci/skip-test

#8382 ci(docs): auto-trigger workflows on release and docs change
  .github/workflows/release.yaml
  .github/workflows/update-docs.yaml
Labels: ci/skip-test, backport

#8389 chore(backport): merge release-2.5 to master
  .github/workflows/helm-release.yaml
Labels: ci/skip-test

#8392 ci(.github): backport golangci-lint
  .github/workflows/golangci-lint.yml
Labels: backport

#8391 ci(.github): fix release which was invalid and ignore branches on docs
  .github/workflows/release.yaml
  .github/workflows/update-docs.yaml
Labels: ci/skip-test, backport

#8376 ci(actions): made build/test/check run in parallel in build-test-distribute workflow
  .github/workflows/build-test-distribute.yaml
Labels: ci/run-full-matrix, ci/skip-test, no-backport-autolabel

#8428 fix(metrics): fix kds metrics for simple watchdog
  pkg/kds/v2/server/components.go
Labels: ci/skip-test, backport

#8435 fix(metrics): unify zone name in metrics for k8s and universal
  pkg/core/bootstrap/bootstrap.go
  pkg/metrics/metrics.go
  pkg/plugins/bootstrap/k8s/plugin.go
Labels: ci/skip-e2e-test

#8424 ci(actions): generate e2e tests matrix
  .github/actions/e2e/action.yaml
  .github/workflows/build-test-distribute.yaml
Labels: ci/skip-test, no-backport-autolabel

#8448 ci(actions): fixing make check failure caused by YAML formatting
  .github/actions/e2e/action.yaml
  .github/workflows/build-test-distribute.yaml
  mk/check.mk
Labels: ci/skip-test, no-backport-autolabel

#8451 ci(lint): add prefix to actions paths
  mk/check.mk
Labels: ci/skip-test

#8427 docs(MADR): zone to global policy sync
  docs/madr/decisions/032-zone-to-global-policy-sync.md
Labels: ci/skip-test

#8445 docs(MADR): add inbound in runtime
  docs/madr/decisions/032-add-inbound-in-runtime.md
Labels: ci/skip-test

#8462 test(e2e): fix Gateway API Namespace label value
  test/e2e/gateway/gatewayapi/conformance_test.go
Labels: ci/run-full-matrix

#8486 ci(actions): do not run kuma-commit workflow when trigger E2E on CircleCI; use pull_request_target on PRs to master
  .circleci/config.yml
  .github/workflows/build-test-distribute.yaml
Labels: ci/skip-test, no-backport-autolabel

#8476 ci(actions): run amd64 E2E on GitHub actions and arm64 on CircleCI
  .github/workflows/build-test-distribute.yaml
  .github/workflows/e2e.yaml
Labels: ci/skip-test, no-backport-autolabel

#8493 ci(actions): disable e2e tests because they are not stable for the moment
  .github/workflows/build-test-distribute.yaml
Labels: ci/skip-test, no-backport-autolabel

#8487 test(policy): add extra testing of the matching algorithm
  pkg/plugins/policies/core/matchers/testdata/matchedpolicies/fromrules/multiple-policies-lexicog-order.dataplane.yaml
  pkg/plugins/policies/core/matchers/testdata/matchedpolicies/fromrules/multiple-policies-lexicog-order.golden.yaml
  pkg/plugins/policies/core/matchers/testdata/matchedpolicies/fromrules/multiple-policies-lexicog-order.policies.yaml
  pkg/plugins/policies/core/rules/testdata/rules/from/mtp-overrides-faulty.golden.yaml
  pkg/plugins/policies/core/rules/testdata/rules/from/mtp-overrides-faulty.input.yaml
  pkg/plugins/policies/core/rules/testdata/rules/from/mtp-overrides.golden.yaml
  pkg/plugins/policies/core/rules/testdata/rules/from/mtp-overrides.input.yaml
  pkg/plugins/policies/core/rules/testdata/rules/from/mtp-single-shadow-deny.golden.yaml
  pkg/plugins/policies/core/rules/testdata/rules/from/mtp-single-shadow-deny.input.yaml
  pkg/plugins/policies/core/rules/testdata/rules/from/single-mtp-from-overiding-one-another.golden.yaml
  pkg/plugins/policies/core/rules/testdata/rules/from/single-mtp-from-overiding-one-another.input.yaml
  pkg/test/ginkgo.go
Labels: ci/skip-e2e-test

#8497 test(unit): add json patch merge test
  pkg/plugins/policies/core/jsonpatch/jsonpatch_suite_test.go
  pkg/plugins/policies/core/jsonpatch/merge_test.go
Labels: ci/skip-e2e-test
