Repository kumahq/kuma, pull requests merged in 2023-02, with the labels that each got.

#5885 ci(commitlint): disallow scope `policies` and empty scopes
  .github/commitlint.config.js
  .github/workflows/lifecycle.yml
  CONTRIBUTING.md
Labels: ci/skip-test

#5893 docs(madr): offline signing tokens
  docs/madr/decisions/019-offline-signing-tokens.md
Labels: ci/skip-test, ci/skip-e2e-test

#5913 feat(helm): make it possbile to install universal cp on k8s
  app/kumactl/cmd/install/install_control_plane_test.go
  app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.cni-experimental-enabled.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.dump-values.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present-not-enabled.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.global-universal-on-k8s.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.registry.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.tproxy-ebpf-experimental-enabled.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.with-egress.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.with-helm-values.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/empty.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/fix4485.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/fix4496.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/fix4935.golden.yaml
  deployments/charts/kuma/README.md
  deployments/charts/kuma/templates/_helpers.tpl
  deployments/charts/kuma/templates/cp-deployment.yaml
  deployments/charts/kuma/templates/cp-rbac.yaml
  deployments/charts/kuma/templates/cp-service.yaml
  deployments/charts/kuma/templates/cp-webhooks-and-secrets.yaml
  deployments/charts/kuma/templates/pre-delete-webhooks.yaml
  deployments/charts/kuma/templates/pre-upgrade-install-missing-crds-job.yaml
  deployments/charts/kuma/values.yaml
  test/e2e/helm/e2e_suite_test.go
  test/e2e/helm/kuma_helm_deploy_global_universal_mode_and_zone.go
  test/framework/controlplane.go
  test/framework/deployments/postgres/deployment.go
  test/framework/deployments/postgres/kubernetes.go
  test/framework/k8s_cluster.go
  test/framework/k8s_clusters.go
  test/framework/k8s_controlplane.go
  test/framework/setup.go
  test/framework/universal_clusters.go
  test/framework/universal_controlplane.go
Labels: ci/run-full-matrix

#5941 ci(make): make some parameters optional in Makefile
  mk/build.mk
  mk/generate.mk
Labels: ci/skip-test

#5936 ci(helm): add `--dev` when doing pull_request too
  .github/workflows/helm-release.yaml
  .github/workflows/pr-comments.yaml
  Makefile
  mk/dependencies/deps.lock
  mk/dependencies/helm.sh
  mk/helm.mk
  tools/releases/helm.sh
Labels: ci/skip-test

#5959 ci(.circleci): remove dev jobs
  .circleci/config.yml
Labels: ci/skip-e2e-test

#5938 feat(helm): remove env vars that are supposed to be provided via secrets
  app/kumactl/cmd/install/testdata/install-control-plane.dump-values.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.global-universal-on-k8s.golden.yaml
  deployments/charts/kuma/README.md
  deployments/charts/kuma/templates/_helpers.tpl
  deployments/charts/kuma/templates/cp-deployment.yaml
  deployments/charts/kuma/values.yaml
  test/e2e/helm/kuma_helm_deploy_global_universal_mode_and_zone.go
Labels: ci/run-full-matrix

#6005 chore: fix docker.sh script
  tools/releases/docker.sh
Labels: ci/skip-test, ci/skip-e2e-test

#5822 chore: update latest supported k8s version in CI
  .circleci/config.yml
  mk/k3d.mk
  pkg/plugins/runtime/k8s/controllers/pod_controller.go
  test/e2e/helm/kuma_helm_deploy_multi_apps.go
  test/e2e_env/kubernetes/graceful/eviction.go
  test/e2e_env/kubernetes/kic/kong_ingress.go
  test/framework/interface.go
  test/framework/k8s_cluster.go
  test/framework/k8s_clusters.go
  test/framework/universal_cluster.go
  test/framework/universal_clusters.go
Labels: ci/run-full-matrix

#6032 ci(deps): don't add filename to deps.lock hash
  mk/dependencies/deps.lock
  tools/dev/install-dev-tools.sh
Labels: ci/skip-test

#6039 ci(.github): add workflow for create and check release
  .github/workflows/release.yaml
  .github/workflows/update-changelog.yaml
  tools/releases/changelog/github.go
  tools/releases/changelog/graphql.go
  tools/releases/changelog/main.go
Labels: ci/skip-test

#6047 ci(.github): fix typo in release.yaml
  .github/workflows/release.yaml
Labels: ci/skip-test

#6048 ci(.github): update PR template to make it smaller
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ci/skip-test

#6050 ci(.github): don't check for kuma cni image in version < 1.8
  .github/workflows/release.yaml
Labels: ci/skip-test

#6053 ci(.github): fix job with Changelog.md
  .github/workflows/release.yaml
Labels: ci/skip-test

#5916 chore(kds): disable nack backoff
  pkg/kds/server/components.go
Labels: ci/run-full-matrix

#6068 chore(kumactl): use location of the current clock
  app/kumactl/cmd/inspect/inspect_dataplanes.go
  app/kumactl/cmd/inspect/inspect_dataplanes_test.go
  app/kumactl/cmd/inspect/inspect_meshes_test.go
  app/kumactl/cmd/inspect/inspect_services_test.go
  app/kumactl/cmd/inspect/inspect_zoneegresses_test.go
  app/kumactl/cmd/inspect/inspect_zoneingresses_test.go
  app/kumactl/cmd/inspect/inspect_zones_test.go
  app/kumactl/pkg/output/table/cells.go
Labels: ci/run-full-matrix, ci/skip-e2e-test

#5950 ci(k3d): update k3d to latest and remove runc install in circleci
  .circleci/config.yml
  mk/dependencies/deps.lock
  mk/dependencies/k3d.sh
Labels: ci/run-full-matrix

#6103 chore(deps): bump github.com/vishvananda/netns to 0.0.4
  go.mod
  go.sum
Labels: ci/run-full-matrix

#6117 feat(policy): create MADR for LB policy
  docs/madr/decisions/021-lb-policy.md
Labels: ci/skip-test

#6141 test(e2e): reenable Gateway API conformance tests
  .circleci/config.yml
  test/e2e/gateway/gatewayapi/conformance_test.go
Labels: ci/run-full-matrix

#6146 test(e2e): enable passing Gateway API conformance test
  test/e2e/gateway/gatewayapi/conformance_test.go
Labels: ci/run-full-matrix

#6145 feat(kds): relax tls requirement
  app/kumactl/cmd/install/install_control_plane_test.go
  app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml
  deployments/charts/kuma/templates/_helpers.tpl
  pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
  pkg/config/loader_test.go
  pkg/config/multizone/kds.go
  pkg/config/multizone/multicluster.go
  pkg/kds/mux/server.go
  test/e2e/helm/kuma_helm_deploy_global_universal_mode_and_zone.go
  test/framework/interface.go
  test/framework/k8s_controlplane.go
  test/framework/universal_controlplane.go
Labels: ci/run-full-matrix

#6162 fix(helm): use emptyDir at /tmp with CP
  app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.cni-legacy-enabled.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present-not-enabled.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.global-universal-on-k8s.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.registry.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.tproxy-ebpf-experimental-enabled.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.with-egress.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.with-helm-values.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/empty.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/fix4485.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/fix4496.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/fix4935.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/fix5978.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/securityContext.golden.yaml
  deployments/charts/kuma/templates/cp-deployment.yaml
Labels: ci/run-full-matrix
