Repository kumahq/kuma, pull requests merged in 2023-10, with the labels that each got.

#7939 fix(kuma-cp): don't add `postStart` hook to builtin gateway even if `waitForDataplaneReady: true`
  pkg/plugins/runtime/k8s/plugin_gateway.go
  test/framework/envs/multizone/env.go
Labels: ci/run-full-matrix

#7951 chore(logs): add missing tenant id
  pkg/insights/components.go
  pkg/insights/resyncer.go
  pkg/insights/resyncer_test.go
  pkg/kds/server/components.go
  pkg/kds/server/status_sink.go
  pkg/kds/v2/server/components.go
  pkg/metrics/store/counter_test.go
Labels: ci/skip-e2e-test

#7964 chore(kuma-cp): add "Or" TypeFilter for core_model
  pkg/core/resources/model/resource.go
Labels: ci/skip-test

#7967 ci(.circleci): fix darwin job after deprecation
  .circleci/config.yml
Labels: ci/run-full-matrix, release-2.1

#7970 ci(.circleci): fix darwin job after deprecation
  .circleci/config.yml
Labels: release-2.0

#7807 test(unit): don't use ryku cleanup in CI
  mk/test.mk
Labels: ci/run-full-matrix

#7994 chore(logging): bump nack level to info to surface potential problems
  pkg/kds/v2/server/resource_retry_forcer.go
Labels: ci/skip-test

#8008 ci(circleci): install qemu on `build` to be able to build arm64 docker
  .circleci/config.yml
Labels: ci/run-full-matrix

#8001 chore(deps): bump go version to 1.21.3
  .circleci/config.yml
  go.mod
Labels: backport

#8017 chore(revert): revert "feat(kuma-cp): introduce zone health checks"
  api/mesh/v1alpha1/kds.pb.go
  api/mesh/v1alpha1/kds.proto
  docs/generated/raw/protos/ZoneHealthCheckResponse.json
  pkg/config/loader_test.go
  pkg/config/multizone/kds.go
  pkg/events/interfaces.go
  pkg/kds/features.go
  pkg/kds/global/components.go
  pkg/kds/mux/client.go
  pkg/kds/mux/zone_sync.go
  pkg/kds/mux/zone_watch.go
  pkg/kds/mux/zone_watch_test.go
  pkg/kds/service/server.go
Labels: ci/run-full-matrix

#8027 chore(deps): bump envoy from 1.24.10 to 1.24.11
  tools/releases/version.sh
Labels: ci/run-full-matrix, release-2.1

#8026 chore(deps): bump envoy from 1.25.9 to 1.25.10
  tools/releases/version.sh
Labels: ci/run-full-matrix, release-2.2

#8030 chore(deps): bump golang.org/x/net to v0.17.0, google.golang.org/grpc to v1.57.1
  go.mod
  go.sum
Labels: release-2.1

#8029 chore(deps): bump golang.org/x/net to v0.17.0, google.golang.org/grpc to v1.57.1
  go.mod
  go.sum
Labels: release-2.0

#8032 chore(deps): bump golang.org/x/net to v0.17.0, google.golang.org/grpc to v1.57.1
  go.mod
  go.sum
Labels: release-2.4

#8028 chore(deps): bump envoy from 1.24.10 to 1.24.11
  tools/releases/version.sh
Labels: ci/run-full-matrix, release-2.0

#8033 chore(deps): bump golang.org/x/net to v0.17.0, google.golang.org/grpc to v1.57.1
  go.mod
  go.sum
Labels: release-2.3

#8031 chore(deps): bump golang.org/x/net to v0.17.0, google.golang.org/grpc to v1.57.1
  go.mod
  go.sum
Labels: release-2.2

#8024 chore(deps): bump envoy from 1.26.4 to 1.26.5
  tools/releases/version.sh
Labels: ci/run-full-matrix, release-2.3

#8025 chore(deps): bump envoy from 1.27.0 to 1.27.1
  tools/releases/version.sh
Labels: ci/run-full-matrix, release-2.4

#8023 chore(deps): bump envoy from 1.27.0 to 1.27.1
  tools/releases/version.sh
Labels: ci/run-full-matrix, master

#8039 fix(api): 400 error on admin operations on not yet connected stream
  pkg/core/rest/errors/error_handler.go
  pkg/intercp/envoyadmin/forwarding_kds_client.go
Labels: ci/run-full-matrix

#8042 feat(kuma-cp): reintroduce zone health checks
  api/mesh/v1alpha1/kds.pb.go
  api/mesh/v1alpha1/kds.proto
  docs/generated/raw/protos/ZoneHealthCheckResponse.json
  pkg/config/loader_test.go
  pkg/config/multizone/kds.go
  pkg/events/interfaces.go
  pkg/kds/features.go
  pkg/kds/global/components.go
  pkg/kds/mux/client.go
  pkg/kds/mux/zone_sync.go
  pkg/kds/mux/zone_watch.go
  pkg/kds/mux/zone_watch_test.go
  pkg/kds/service/server.go
Labels: ci/run-full-matrix

#8070 chore(kuma-cp): fix golden filenames for api server dp overviews
  pkg/api-server/dataplane_overview_endpoints_test.go
  pkg/api-server/testdata/meshes_mesh1_dataplanes_insights.json
  pkg/api-server/testdata/meshes_mesh1_dataplanes_insights_gateway_builtin.json
  pkg/api-server/testdata/meshes_mesh1_dataplanes_insights_gateway_delegated.json
  pkg/api-server/testdata/meshes_mesh1_dataplanes_insights_gateway_true.json
  pkg/api-server/testdata/meshes_mesh1_dataplanes_insights_name_gateway.json
  pkg/api-server/testdata/meshes_mesh1_dataplanes_insights_name_tew.json
  pkg/api-server/testdata/meshes_mesh1_dataplanes_insights_tag_service_backend.json
  pkg/api-server/testdata/meshes_mesh1_dataplanes_insights_tag_service_backend_tag_version_v1.json
  pkg/api-server/testdata/meshes_mesh1_dataplanes_insights_tag_service_backend_tag_version_v2.json
  pkg/api-server/testdata/meshes_mesh1_dataplanes_insights_tag_service_ck.json
  pkg/api-server/testdata/meshes_mesh1_dataplanes_insights_tag_tagcolumn_tag_v.json
Labels: ci/skip-e2e-test

#8077 chore(helm): allow to set log level for {in|e}gress
  deployments/charts/kuma/README.md
  deployments/charts/kuma/templates/egress-deployment.yaml
  deployments/charts/kuma/templates/ingress-deployment.yaml
  deployments/charts/kuma/values.yaml
  docs/generated/raw/helm-values.yaml
Labels: ci/skip-test

#8078 chore(tests): update golden file for kumactl install cp
  app/kumactl/cmd/install/testdata/install-control-plane.dump-values.yaml
Labels: ci/skip-e2e-test

#8098 ci(security): filter out kuma from security update
  tools/ci/update-vulnerable-dependencies.sh
Labels: ci/skip-test

#8081 fix(kuma-cp): use stable hashes for outbound cluster names
  app/kuma-dp/pkg/dataplane/metrics/merge.go
  app/kuma-dp/pkg/dataplane/metrics/merge_test.go
  app/kuma-dp/pkg/dataplane/metrics/testdata/counter-and-noncluster-metrics.in
  app/kuma-dp/pkg/dataplane/metrics/testdata/counter-sparse.in
  app/kuma-dp/pkg/dataplane/metrics/testdata/counter-status-codes.in
  app/kuma-dp/pkg/dataplane/metrics/testdata/counter-with-labels.in
  app/kuma-dp/pkg/dataplane/metrics/testdata/counter.in
  app/kuma-dp/pkg/dataplane/metrics/testdata/gauge.in
  app/kuma-dp/pkg/dataplane/metrics/testdata/histogram.in
  app/kuma-dp/pkg/dataplane/metrics/testdata/summary.in
  app/kuma-dp/pkg/dataplane/metrics/testdata/untyped.in
  pkg/plugins/policies/core/xds/clusters.go
  pkg/plugins/policies/core/xds/endpoints.go
  pkg/plugins/policies/core/xds/meshroute/listeners.go
  pkg/plugins/policies/meshcircuitbreaker/plugin/v1alpha1/plugin_test.go
  pkg/plugins/policies/meshcircuitbreaker/plugin/v1alpha1/testdata/outbound_split_cluster_0_connection_limits_outlier_detection.golden.yaml
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/listeners.go
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/basic.clusters.golden.yaml
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/basic.endpoints.golden.yaml
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/basic.listeners.golden.yaml
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/request-mirror.clusters.golden.yaml
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/request-mirror.endpoints.golden.yaml
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/request-mirror.listeners.golden.yaml
  pkg/plugins/policies/meshtcproute/plugin/v1alpha1/listeners.go
  pkg/plugins/policies/meshtcproute/plugin/v1alpha1/testdata/split-traffic.clusters.golden.yaml
  pkg/plugins/policies/meshtcproute/plugin/v1alpha1/testdata/split-traffic.endpoints.golden.yaml
  pkg/plugins/policies/meshtcproute/plugin/v1alpha1/testdata/split-traffic.listeners.golden.yaml
  pkg/xds/envoy/names/resource_names.go
  pkg/xds/envoy/tags/match.go
  pkg/xds/generator/outbound_proxy_generator.go
  pkg/xds/generator/testdata/outbound-proxy/03.envoy.golden.yaml
  pkg/xds/generator/testdata/outbound-proxy/04.envoy.golden.yaml
  pkg/xds/generator/testdata/outbound-proxy/05.envoy.golden.yaml
  pkg/xds/generator/testdata/outbound-proxy/06.envoy.golden.yaml
  pkg/xds/generator/testdata/outbound-proxy/08.envoy.golden.yaml
  pkg/xds/generator/testdata/outbound-proxy/09.envoy.golden.yaml
  pkg/xds/generator/testdata/outbound-proxy/cluster-dots.envoy.golden.yaml
  test/e2e_env/universal/meshhealthcheck/policy.go
Labels: ci/run-full-matrix

#8129 fix(kuma-cp): fix Zone{In|E}gress sync when no mesh
  pkg/xds/context/aggregate_mesh_context.go
  pkg/xds/context/mesh_context_builder.go
  pkg/xds/sync/dataplane_watchdog.go
  pkg/xds/sync/egress_proxy_builder.go
Labels: ci/force-publish, backport

#8136 chore(xds): improve error logging
  pkg/core/permissions/matcher.go
  pkg/core/permissions/matcher_test.go
  pkg/plugins/runtime/gateway/generator.go
  pkg/plugins/runtime/gateway/plugin.go
  pkg/xds/context/mesh_context_builder.go
  pkg/xds/sync/dataplane_proxy_builder.go
  pkg/xds/sync/dataplane_watchdog.go
Labels: backport

#8022 docs(madr): add Locality Aware load balancing madr
  docs/madr/decisions/031-locality-aware-load-balancing.md
  docs/madr/decisions/assets/031/use_case_1.png
  docs/madr/decisions/assets/031/use_case_2.png
  docs/madr/decisions/assets/031/use_case_2_1.png
  docs/madr/decisions/assets/031/use_case_2_2.png
  docs/madr/decisions/assets/031/use_case_2_3.png
  docs/madr/decisions/assets/031/use_case_3_1.png
  docs/madr/decisions/assets/031/use_case_3_2.png
  docs/madr/decisions/assets/031/use_case_4_1.png
  docs/madr/decisions/assets/031/use_case_4_2.png
  docs/madr/decisions/assets/031/use_case_4_3.png
  docs/madr/decisions/assets/031/use_case_5_1.png
  docs/madr/decisions/assets/031/use_case_5_2.png
  docs/madr/decisions/assets/031/use_case_5_3.png
  docs/madr/decisions/assets/031/use_case_6_1.png
  docs/madr/decisions/assets/031/use_case_6_2.png
  docs/madr/decisions/assets/031/use_case_6_3.png
  docs/madr/decisions/assets/031/use_case_7.png
  docs/madr/decisions/assets/031/use_case_8.png
  docs/madr/decisions/assets/031/xds_generation_with_cache.png
  docs/madr/decisions/assets/031/xds_generation_without_cache.png
Labels: ci/skip-test

#8159 build(go): remove no longer needed `experimental` build tag
  .golangci.yml
  mk/build.mk
Labels: ci/run-full-matrix

#8165 chore(deps): upgrade envoy to 1.24.12
  tools/releases/version.sh
Labels: ci/run-full-matrix, release-2.1

#8164 chore(deps): upgrade envoy to 1.24.12
  tools/releases/version.sh
Labels: ci/run-full-matrix, release-2.0

#8163 chore(deps): upgrade envoy to 1.25.11
  tools/releases/version.sh
Labels: ci/run-full-matrix, release-2.2

#8162 chore(deps): upgrade envoy to 1.26.6
  tools/releases/version.sh
Labels: ci/run-full-matrix, release-2.3

#8161 chore(deps): upgrade envoy to 1.27.2
  tools/releases/version.sh
Labels: ci/run-full-matrix, release-2.4

#8158 chore(deps): upgrade envoy to 1.28.0
  tools/releases/version.sh
Labels: ci/run-full-matrix

#8084 docs(madr): auto reachable services
  docs/madr/decisions/031-automatic-rechable-services.md
Labels: ci/skip-test

#8171 fix(MeshTrafficPermission): support permissive mtls
  pkg/plugins/policies/meshtrafficpermission/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshtrafficpermission/plugin/v1alpha1/plugin_test.go
  pkg/plugins/policies/meshtrafficpermission/plugin/v1alpha1/testdata/apply.golden.yaml
  pkg/test/resources/builders/mesh_builder.go
  pkg/xds/generator/inbound_proxy_generator.go
  pkg/xds/generator/testdata/inbound-proxy/5-envoy-config.golden.yaml
  pkg/xds/generator/testdata/inbound-proxy/6-envoy-config.golden.yaml
  test/e2e_env/universal/meshtrafficpermission/meshtrafficpermission.go
Labels: backport

#8148 feat(api-server): new inspect api
  api/mesh/v1alpha1/dataplane_helpers.go
  api/openapi/openapi.cfg.yaml
  api/openapi/specs/api.yaml
  api/openapi/specs/common/resource.yaml
  api/openapi/types/common/zz_generated.resource.go
  api/openapi/types/zz_generated.api.go
  docs/generated/openapi.yaml
  mk/docs.mk
  pkg/api-server/api_server_suite_test.go
  pkg/api-server/resource_endpoints.go
  pkg/api-server/resource_endpoints_test.go
  pkg/api-server/testdata/inspect/empty_resources_dataplanes.golden.json
  pkg/api-server/testdata/inspect/empty_resources_dataplanes.input.yaml
  pkg/api-server/testdata/inspect/gateway_targetref_dataplanes.golden.json
  pkg/api-server/testdata/inspect/match_mesh_dataplanes.golden.json
  pkg/api-server/testdata/inspect/match_mesh_dataplanes.input.yaml
  pkg/api-server/testdata/inspect/match_meshservice_dataplanes.golden.json
  pkg/api-server/testdata/inspect/match_meshservice_dataplanes.input.yaml
  pkg/api-server/testdata/inspect/meshgateway_dataplanes.golden.json
  pkg/api-server/testdata/inspect/meshgateway_dataplanes.input.yaml
  pkg/api-server/testdata/inspect/meshgatewayroute_dataplanes.golden.json
  pkg/api-server/testdata/inspect/meshgatewayroute_dataplanes.input.yaml
  pkg/api-server/testdata/inspect/meshhttproute_absent_dataplanes.golden.json
  pkg/api-server/testdata/inspect/meshhttproute_absent_dataplanes.input.yaml
  pkg/api-server/testdata/inspect/meshhttproute_dataplanes.golden.json
  pkg/api-server/testdata/inspect/meshhttproute_dataplanes.input.yaml
  pkg/api-server/testdata/inspect/meshtimeouthttproute.golden.json
  pkg/api-server/testdata/inspect/meshtimeouthttproute.input.yaml
  pkg/api-server/testdata/inspect/namefilter_dataplanes.golden.json
  pkg/api-server/testdata/inspect/namefilter_dataplanes.input.yaml
  pkg/api-server/testdata/inspect/pagination_dataplanes.golden.json
  pkg/api-server/testdata/inspect/pagination_dataplanes.input.yaml
  pkg/api-server/testdata/inspect/policy_not_found_dataplanes.golden.json
  pkg/api-server/testdata/inspect/policy_not_found_dataplanes.input.yaml
  pkg/api-server/testdata/inspect/proxytemplate_dataplanes.golden.json
  pkg/api-server/testdata/inspect/proxytemplate_dataplanes.input.yaml
  pkg/api-server/testdata/inspect/retry_dataplanes.golden.json
  pkg/api-server/testdata/inspect/retry_dataplanes.input.yaml
  pkg/core/resources/model/resource.go
  pkg/core/xds/matched_policies.go
  pkg/plugins/policies/core/matchers/dataplane.go
  pkg/plugins/policies/core/matchers/dataplane_test.go
  pkg/plugins/policies/core/matchers/testdata/matchedpolicies/dataplanepolicies/06.dataplane.yaml
  pkg/plugins/policies/core/matchers/testdata/matchedpolicies/dataplanepolicies/06.golden.yaml
  pkg/plugins/policies/core/matchers/testdata/matchedpolicies/dataplanepolicies/06.policies.yaml
  pkg/plugins/policies/core/rules/rules.go
  pkg/plugins/policies/core/rules/rules_test.go
  pkg/plugins/policies/meshtcproute/plugin/v1alpha1/plugin_test.go
  pkg/plugins/policies/meshtrafficpermission/graph/reachable_services_graph.go
  pkg/plugins/policies/meshtrafficpermission/graph/reachable_services_graph_test.go
  pkg/plugins/resources/remote/store.go
  pkg/plugins/runtime/k8s/controllers/gatewayapi/mesh_http_route_conversion.go
  pkg/plugins/runtime/k8s/controllers/inbound_converter.go
  pkg/test/ginkgo.go
  test/e2e_env/kubernetes/inspect/inspect.go
  test/e2e_env/multizone/inspect/inspect.go
Labels: ci/run-full-matrix

#8168 fix(k8s): fix VIPs configmap entries with invalid keys for ExternalName services
  pkg/dns/vips/interfaces.go
  pkg/plugins/runtime/k8s/controllers/inbound_converter.go
  pkg/plugins/runtime/k8s/controllers/kube_hosts_converter.go
  pkg/plugins/runtime/k8s/controllers/outbound_converter.go
  pkg/plugins/runtime/k8s/controllers/service_controller.go
  pkg/plugins/runtime/k8s/controllers/service_controller_test.go
  test/e2e_env/kubernetes/externalname-services/externalname-services.go
  test/e2e_env/kubernetes/kubernetes_suite_test.go
Labels: backport

#8200 ci(mk): make generate/envoy-imports target to only run on Kuma
  mk/generate.mk
Labels: ci/skip-test

#8208 chore(actions): run security update job at 3 am
  .github/workflows/update-insecure-dependencies.yaml
Labels: ci/skip-test
