Repository kumahq/kuma, pull requests merged in 2023-05, with the labels that each got.

#6638 chore(deps): bump Envoy to v1.26.1
  tools/releases/version.sh
Labels: ci/run-full-matrix

#6672 ci(k8s): use metallb instead of servicelb
  mk/k3d.mk
  mk/metallb-k3d-kuma-1.yaml
  mk/metallb-k3d-kuma-2.yaml
Labels: ci/run-full-matrix

#6442 chore(ci): run experimental delta xds on full matrix
  .circleci/config.yml
  test/framework/config.go
Labels: ci/run-full-matrix

#6674 chore(deps): bump gateway-api to v0.7.0-rc1
  go.mod
  go.sum
  test/e2e/gateway/gatewayapi/conformance_test.go
Labels: ci/run-full-matrix

#6700 docs(madr/numeration): fix madr decision numeration
  docs/madr/decisions/012-rate-limit-policy.md
  docs/madr/decisions/013-health-check-policy.md
  docs/madr/decisions/014-multizone-envoy-admin.md
  docs/madr/decisions/015-mesh-circuit-breaker-policy.md
  docs/madr/decisions/016-retry-policy.md
  docs/madr/decisions/017-policy-array-merging.md
  docs/madr/decisions/018-mesh-proxy-patch.md
  docs/madr/decisions/019-fault-injection-policy.md
  docs/madr/decisions/020-offline-signing-tokens.md
  docs/madr/decisions/021-kds-redesign.md
  docs/madr/decisions/022-lb-policy.md
  docs/madr/decisions/023-retry-host-selection.md
  docs/madr/decisions/024-gateway-custom-deploy.md
Labels: kind/docs, ci/skip-test

#6663 fix(helm): use correct secret for CP CA in ingress/egress
  app/kumactl/cmd/install/testdata/install-control-plane.with-egress.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/fix4496.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/fix4935.golden.yaml
  deployments/charts/kuma/templates/_helpers.tpl
  deployments/charts/kuma/templates/egress-deployment.yaml
  deployments/charts/kuma/templates/ingress-deployment.yaml
Labels: ci/run-full-matrix

#6720 docs(madr/numeration): fix madr numeration
  docs/madr/decisions/025-disable-default-policies.md
Labels: kind/docs, ci/skip-test

#6727 ci(.github): add backport action to replace mergify
  .github/workflows/backport.yaml
  CONTRIBUTING.md
Labels: ci/skip-test

#6695 ci(.circleci): don't prefix all jobs with 'test/e2e'
  .circleci/config.yml
  mk/k3d.mk
Labels: ci/run-full-matrix

#6784 test(e2e): add option to set init scripts for postgres
  test/framework/deployments/postgres/deployment.go
  test/framework/deployments/postgres/kubernetes.go
Labels: ci/skip-test, ci/skip-e2e-test

#6785 ci(.github): update backport workflow secret names
  .github/workflows/backport.yaml
Labels: ci/skip-test

#6789 fix(multitenancy): global tenant in intercp when creating certs
  pkg/intercp/components.go
Labels: ci/skip-test, ci/skip-e2e-test

#6795 chore(build): add mk/metallb-k3d-kuma.yaml
  mk/metallb-k3d-kuma.yaml
Labels: ci/skip-test, ci/skip-e2e-test, ci/skip-container-structure-test

#6809 chore(deps): bump controller-runtime from v0.14.6 to v0.15.0-beta0
  app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present-not-enabled.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml
  app/kumactl/cmd/install/testdata/install-crds.all.golden.yaml
  app/kumactl/cmd/install/testdata/install-crds.experimental-gatewayapi.golden.yaml
  deployments/charts/kuma/crds/kuma.io_meshgatewayconfigs.yaml
  deployments/charts/kuma/crds/kuma.io_meshgatewayinstances.yaml
  go.mod
  go.sum
  pkg/plugins/bootstrap/k8s/cache/cache.go
  pkg/plugins/bootstrap/k8s/cache/doc.go
  pkg/plugins/bootstrap/k8s/cache/informer_cache.go
  pkg/plugins/bootstrap/k8s/cache/internal/cache_reader.go
  pkg/plugins/bootstrap/k8s/cache/internal/deleg_map.go
  pkg/plugins/bootstrap/k8s/cache/internal/informers_map.go
  pkg/plugins/bootstrap/k8s/plugin.go
  pkg/plugins/common/k8s/composite_validator.go
  pkg/plugins/common/k8s/composite_validator_test.go
  pkg/plugins/resources/k8s/events/listener.go
  pkg/plugins/runtime/k8s/controllers/cni_taint_controller.go
  pkg/plugins/runtime/k8s/controllers/configmap_controller.go
  pkg/plugins/runtime/k8s/controllers/configmap_controller_test.go
  pkg/plugins/runtime/k8s/controllers/gateway_instance_controller.go
  pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_class_controller.go
  pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_controller.go
  pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_controller.go
  pkg/plugins/runtime/k8s/controllers/pod_controller.go
  pkg/plugins/runtime/k8s/controllers/pod_controller_test.go
  pkg/plugins/runtime/k8s/plugin.go
  pkg/plugins/runtime/k8s/webhooks/containerpatch_validator.go
  pkg/plugins/runtime/k8s/webhooks/dataplane_validator.go
  pkg/plugins/runtime/k8s/webhooks/defaulter.go
  pkg/plugins/runtime/k8s/webhooks/defaulter_test.go
  pkg/plugins/runtime/k8s/webhooks/externalservice_validator.go
  pkg/plugins/runtime/k8s/webhooks/gateway_instance_validator.go
  pkg/plugins/runtime/k8s/webhooks/gatewayapi_multizone_validator.go
  pkg/plugins/runtime/k8s/webhooks/mesh_validator.go
  pkg/plugins/runtime/k8s/webhooks/owner_reference_mutator.go
  pkg/plugins/runtime/k8s/webhooks/policy_namespace_validator.go
  pkg/plugins/runtime/k8s/webhooks/ratelimit_validator.go
  pkg/plugins/runtime/k8s/webhooks/secret_validator.go
  pkg/plugins/runtime/k8s/webhooks/service_validator.go
  pkg/plugins/runtime/k8s/webhooks/service_validator_test.go
  pkg/plugins/runtime/k8s/webhooks/validation.go
  pkg/plugins/runtime/k8s/webhooks/validation_test.go
  pkg/plugins/runtime/k8s/webhooks/webhook_suite_test.go
  pkg/plugins/runtime/k8s/webhooks/zone_validator.go
Labels: ci/run-full-matrix

#6840 chore(deps): bump gateway-api to have more conformance tests
  go.mod
  go.sum
Labels: ci/run-full-matrix

#6843 fix(MeshGateway): tweak route precedence to match Gateway API
  go.mod
  go.sum
  pkg/plugins/runtime/gateway/route/sorter.go
  pkg/plugins/runtime/gateway/route/sorter_test.go
  pkg/plugins/runtime/gateway/route/table.go
Labels: ci/run-full-matrix

#6839 refactor(GatewayAPI): more flexible condition accumulation
  pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_conversion.go
Labels: ci/run-full-matrix

#6852 fix(GatewayAPI): npe errors
  pkg/plugins/runtime/k8s/controllers/gatewayapi/mesh_http_route_conversion.go
Labels: ci/run-full-matrix

#6853 chore(MeshTCPRoute): remove log "apply not implemented"
  pkg/plugins/policies/meshtcproute/plugin/v1alpha1/plugin.go
Labels: ci/skip-test

#6836 refactor(GatewayAPI): fewer MeshHTTPRoutes per GAMMA HTTPRoute
  pkg/plugins/runtime/k8s/controllers/gatewayapi/mesh_http_route_conversion.go
Labels: ci/run-full-matrix

#6857 test(MeshTCPRoute): add e2e test for colision with MeshHTTPRoute
  test/e2e_env/kubernetes/meshtcproute/test.go
Labels: ci/skip-test

#6859 test(MeshTCPRoute): small name fix in e2e test case
  test/e2e_env/kubernetes/meshtcproute/test.go
Labels: ci/skip-test

#6854 fix(GatewayAPI): properly handle owned MeshHTTPRoutes
  pkg/plugins/runtime/k8s/controllers/gatewayapi/common/reconcile.go
  pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_controller.go
  pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_controller.go
  pkg/plugins/runtime/k8s/controllers/gatewayapi/mesh_http_route_conversion.go
Labels: ci/run-full-matrix

#6868 test(MeshTCPRoute): add e2e case for clash when destination is tcp
  test/e2e_env/kubernetes/meshtcproute/test.go
Labels: ci/skip-test

#6870 test(MeshTCPRoute): add tests for xds config generation
  pkg/plugins/policies/meshtcproute/plugin/v1alpha1/plugin_suite_test.go
  pkg/plugins/policies/meshtcproute/plugin/v1alpha1/plugin_test.go
  pkg/plugins/policies/meshtcproute/plugin/v1alpha1/testdata/meshhttproute-clash-http-destination.clusters.golden.yaml
  pkg/plugins/policies/meshtcproute/plugin/v1alpha1/testdata/meshhttproute-clash-http-destination.endpoints.golden.yaml
  pkg/plugins/policies/meshtcproute/plugin/v1alpha1/testdata/meshhttproute-clash-http-destination.listeners.golden.yaml
  pkg/plugins/policies/meshtcproute/plugin/v1alpha1/testdata/meshhttproute-clash-tcp-destination.clusters.golden.yaml
  pkg/plugins/policies/meshtcproute/plugin/v1alpha1/testdata/meshhttproute-clash-tcp-destination.endpoints.golden.yaml
  pkg/plugins/policies/meshtcproute/plugin/v1alpha1/testdata/meshhttproute-clash-tcp-destination.listeners.golden.yaml
  pkg/plugins/policies/meshtcproute/plugin/v1alpha1/testdata/redirect-traffic.clusters.golden.yaml
  pkg/plugins/policies/meshtcproute/plugin/v1alpha1/testdata/redirect-traffic.endpoints.golden.yaml
  pkg/plugins/policies/meshtcproute/plugin/v1alpha1/testdata/redirect-traffic.listeners.golden.yaml
  pkg/plugins/policies/meshtcproute/plugin/v1alpha1/testdata/split-traffic.clusters.golden.yaml
  pkg/plugins/policies/meshtcproute/plugin/v1alpha1/testdata/split-traffic.endpoints.golden.yaml
  pkg/plugins/policies/meshtcproute/plugin/v1alpha1/testdata/split-traffic.listeners.golden.yaml
Labels: ci/skip-test

#6872 chore(docs/madr): fix madr files numbering
  docs/madr/decisions/027-meshgateway-targetref.md
Labels: ci/skip-test

#6786 docs(MADR): use MeshHTTPRoute as spec.targetRef.kind
  docs/madr/decisions/028-meshhttproute-as-targetref.md
Labels: ci/skip-test

#6887 feat(kuma-cp): allow to override resource store plugin
  pkg/core/plugins/registry.go
Labels: ci/skip-e2e-test
