Repository kumahq/kuma, pull requests merged in 2023-09, with the labels that each got.

#7662 fix(xds): backwards compatibility on access logs paths
  pkg/core/xds/metadata.go
  pkg/core/xds/metadata_test.go
  pkg/xds/auth/callbacks.go
  pkg/xds/server/callbacks/dataplane_callbacks.go
  pkg/xds/server/callbacks/dataplane_status_tracker.go
Labels: backport

#7696 fix(kumactl): add `--mesh` parameter to `inspect <policy>`
  app/kumactl/cmd/completion/testdata/bash.golden
  app/kumactl/cmd/inspect/inspect_policy.go
  app/kumactl/cmd/inspect/inspect_policy_test.go
  app/kumactl/cmd/inspect/testdata/inspect-traffic-trace-other-mesh.golden.txt
  app/kumactl/cmd/inspect/testdata/inspect-traffic-trace-other-mesh.server-response.json
  docs/generated/cmd/kumactl/kumactl_inspect_circuit-breaker.md
  docs/generated/cmd/kumactl/kumactl_inspect_fault-injection.md
  docs/generated/cmd/kumactl/kumactl_inspect_healthcheck.md
  docs/generated/cmd/kumactl/kumactl_inspect_meshaccesslog.md
  docs/generated/cmd/kumactl/kumactl_inspect_meshcircuitbreaker.md
  docs/generated/cmd/kumactl/kumactl_inspect_meshfaultinjection.md
  docs/generated/cmd/kumactl/kumactl_inspect_meshhealthcheck.md
  docs/generated/cmd/kumactl/kumactl_inspect_meshhttproute.md
  docs/generated/cmd/kumactl/kumactl_inspect_meshloadbalancingstrategy.md
  docs/generated/cmd/kumactl/kumactl_inspect_meshproxypatch.md
  docs/generated/cmd/kumactl/kumactl_inspect_meshratelimit.md
  docs/generated/cmd/kumactl/kumactl_inspect_meshretry.md
  docs/generated/cmd/kumactl/kumactl_inspect_meshtcproute.md
  docs/generated/cmd/kumactl/kumactl_inspect_meshtimeout.md
  docs/generated/cmd/kumactl/kumactl_inspect_meshtrace.md
  docs/generated/cmd/kumactl/kumactl_inspect_meshtrafficpermission.md
  docs/generated/cmd/kumactl/kumactl_inspect_proxytemplate.md
  docs/generated/cmd/kumactl/kumactl_inspect_rate-limit.md
  docs/generated/cmd/kumactl/kumactl_inspect_retry.md
  docs/generated/cmd/kumactl/kumactl_inspect_timeout.md
  docs/generated/cmd/kumactl/kumactl_inspect_traffic-log.md
  docs/generated/cmd/kumactl/kumactl_inspect_traffic-permission.md
  docs/generated/cmd/kumactl/kumactl_inspect_traffic-route.md
  docs/generated/cmd/kumactl/kumactl_inspect_traffic-trace.md
Labels: backport

#7654 feat(kuma-cp): pass resource keys to postgres query for delta kds
  docs/generated/kuma-cp.md
  docs/generated/raw/kuma-cp.yaml
  pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
  pkg/config/loader_test.go
  pkg/config/plugins/resources/postgres/config.go
  pkg/core/resources/model/resource.go
  pkg/core/resources/store/options.go
  pkg/core/resources/store/pagination_store.go
  pkg/kds/v2/store/sync.go
  pkg/plugins/resources/postgres/pgx_store.go
  pkg/plugins/resources/postgres/pq_store.go
  pkg/plugins/resources/postgres/store_template_test.go
  pkg/test/store/store_test_template.go
Labels: ci/run-full-matrix

#7660 ci(upgrade): do not cache go mod manually
  .github/workflows/blackbox-tests.yaml
  .github/workflows/pr-comments.yaml
Labels: ci/skip-test, ci/skip-e2e-test

#7656 fix(install): use bitnami/kubectl image for helm hooks
  app/kumactl/cmd/install/testdata/install-control-plane.dump-values.yaml
  deployments/charts/kuma/README.md
  deployments/charts/kuma/templates/_helpers.tpl
  deployments/charts/kuma/templates/pre-delete-webhooks.yaml
  deployments/charts/kuma/templates/pre-install-patch-namespace-job.yaml
  deployments/charts/kuma/templates/pre-upgrade-install-crds-job.yaml
  deployments/charts/kuma/values.yaml
  docs/generated/raw/helm-values.yaml
  mk/k3d.mk
  tools/kubectl/Dockerfile
  tools/kubectl/README.md
  tools/kubectl/docker-build-and-publish.sh
Labels: ci/run-full-matrix

#7740 feat(dist): add cloudsmith ENVs to dist mk target
  mk/distribution.mk
Labels: ci/skip-test, ci/force-publish, backport

#7751 fix(metrics): result of reconciliation
  pkg/kds/v2/reconcile/reconciler.go
Labels: ci/skip-e2e-test

#7708 docs(madr): madr for extending Global Insight with info about number of policies, zones, services, dataplanes and their status
  docs/madr/decisions/030-extended-global-insights.md
Labels: ci/skip-test, ci/skip-e2e-test

#7574 ci(k8s): update max k8s to 1.28
  .circleci/config.yml
  mk/dependencies/deps.lock
  mk/dev.mk
Labels: ci/run-full-matrix

#7756 fix(madr): Rewriting Global Insight response structure to make it more coherent
  docs/madr/decisions/030-extended-global-insights.md
Labels: ci/skip-test

#7767 test(unit): do not panic on missing metric
  pkg/insights/resyncer_test.go
Labels: ci/skip-e2e-test

#7769 fix(postgres): use customizer for ro pool
  pkg/plugins/resources/postgres/pgx_store.go
Labels: ci/skip-e2e-test

#7780 fix(api-server): empty list instead of null
  pkg/api-server/inspect_endpoints.go
  pkg/api-server/inspect_endpoints_test.go
  pkg/api-server/testdata/inspect_dataplane_rules_empty.golden.json
Labels: ci/skip-e2e-test

#7781 chore(deps): bump sigs.k8s.io/gateway-api from v0.8.0 to v0.8.1
  go.mod
  go.sum
  test/e2e/gateway/gatewayapi/conformance_test.go
  test/framework/k8s.go
Labels: ci/run-full-matrix

#7771 fix(gatewayapi): don't set RefNotPermitted for GAMMA routes
  pkg/plugins/runtime/k8s/controllers/gatewayapi/conversion.go
  pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_controller.go
  pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_conversion.go
  pkg/plugins/runtime/k8s/controllers/gatewayapi/mesh_http_route_conversion.go
Labels: ci/run-full-matrix

#7770 feat(store): add owner reference to the secrets
  pkg/core/ca/manager.go
  pkg/core/managers/apis/mesh/mesh_helpers.go
  pkg/core/managers/apis/mesh/mesh_manager.go
  pkg/core/tokens/meshed_signing_key_manager.go
  pkg/defaults/components.go
  pkg/defaults/mesh.go
  pkg/defaults/mesh/mesh.go
  pkg/defaults/mesh/mesh_test.go
  pkg/defaults/mesh/signing_key.go
  pkg/plugins/ca/builtin/manager.go
  pkg/plugins/ca/builtin/manager_test.go
  pkg/plugins/ca/provided/manager.go
  pkg/plugins/runtime/k8s/controllers/mesh_defaults_controller.go
  pkg/plugins/runtime/k8s/controllers/mesh_defaults_controller_test.go
  pkg/plugins/secrets/k8s/plugin.go
  pkg/plugins/secrets/k8s/store.go
  pkg/plugins/secrets/k8s/store_test.go
  pkg/test/store/owner_test_template.go
  pkg/xds/secrets/secrets_test.go
  test/e2e_env/kubernetes/gateway/gateway.go
  test/e2e_env/kubernetes/gateway/mtls.go
Labels: ci/run-full-matrix

#7805 fix(kuma-cp): take proper context for resync
  pkg/insights/resyncer.go
Labels: ci/skip-e2e-test

#7808 fix(metrics): resources synced
  pkg/kds/v2/store/sync.go
Labels: ci/skip-test

#7799 chore(deps): bump go from 1.20.7 to 1.21.1
  .circleci/config.yml
  .github/workflows/blackbox-tests.yaml
  .github/workflows/golangci-lint.yml
  .github/workflows/helm-release.yaml
  .github/workflows/pr-comments.yaml
  .github/workflows/release.yaml
  .github/workflows/update-docs.yaml
  .github/workflows/update-insecure-dependencies.yaml
  go.mod
  go.sum
  mk/dependencies/deps.lock
  mk/dev.mk
Labels: backport

#7836 chore(gitignore): add asdf-specific file
  .gitignore
Labels: ci/skip-test

#7871 ci(.github): add setup-go to helm release workflow
  .github/workflows/helm-release.yaml
Labels: release-2.0

#7868 feat(kds): better error handling
  pkg/kds/mux/server.go
  pkg/kds/mux/zone_sync.go
  pkg/kds/service/server.go
  pkg/kds/v2/server/error_recorder_stream.go
  pkg/kds/v2/server/kds.go
  pkg/kds/v2/server/streamwrapper.go
Labels: backport

#7885 chore(kuma-cp): improve logging
  .golangci.yml
  app/kuma-cp/cmd/run.go
  pkg/config/loader.go
  pkg/core/alias.go
  pkg/core/secrets/manager/validator.go
  pkg/insights/resyncer.go
  pkg/mads/v1/generator/assignments.go
  pkg/plugins/policies/core/matchers/dataplane.go
  pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_class_controller.go
  pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_controller.go
  pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_controller.go
  pkg/xds/context/context.go
Labels: ci/skip-test

#7887 ci(ghaction): fix pr-comments /format gh action
  .github/workflows/pr-comments.yaml
Labels: ci/skip-test

#7870 feat(transparent-proxy): allow to wait for xtables lock and retry when installing tproxy fails
  api/mesh/v1alpha1/externalservice.pb.go
  api/mesh/v1alpha1/externalservice.proto
  app/kumactl/cmd/completion/testdata/bash.golden
  app/kumactl/cmd/install/install_transparent_proxy.go
  app/kumactl/cmd/install/install_transparent_proxy_test.go
  docs/generated/cmd/kumactl/kumactl_install_transparent-proxy.md
  docs/generated/resources/policy_external-service.md
  pkg/insights/globalinsight/testdata/full_global_insight.golden.json
  pkg/transparentproxy/config/config.go
  pkg/transparentproxy/iptables/builder/builder.go
  pkg/transparentproxy/iptables/builder/builder_restore.go
  pkg/transparentproxy/iptables/builder/builder_table_mangle.go
  pkg/transparentproxy/iptables/builder/builder_table_nat.go
  pkg/transparentproxy/iptables/builder/builder_table_nat_test.go
  pkg/transparentproxy/iptables/builder/builder_table_raw.go
  pkg/transparentproxy/iptables/commands/command.go
  pkg/transparentproxy/iptables/parameters/noflush.go
  pkg/transparentproxy/iptables/parameters/parameters.go
  pkg/transparentproxy/iptables/parameters/wait.go
  pkg/transparentproxy/iptables/parameters/wait_interval.go
  pkg/transparentproxy/iptables/parameters/wait_interval_test.go
  pkg/transparentproxy/iptables/parameters/wait_test.go
  pkg/transparentproxy/transparentproxy_v2.go
Labels: backport

#7910 chore(kds): tenant logging
  pkg/kds/global/components.go
  pkg/kds/global/components_test.go
  pkg/kds/mux/zone_sync.go
  pkg/kds/service/server.go
  pkg/kds/v2/client/zone_sync_test.go
  pkg/kds/v2/reconcile/interfaces.go
  pkg/kds/v2/reconcile/reconciler.go
  pkg/kds/v2/server/components.go
  pkg/kds/v2/server/event_based_watchdog.go
  pkg/kds/v2/server/event_based_watchdog_test.go
  pkg/kds/v2/store/sync.go
  pkg/kds/v2/store/sync_test.go
  pkg/kds/zone/components.go
  pkg/kds/zone/components_test.go
  pkg/test/kds/setup/server.go
Labels: ci/skip-e2e-test
