Repository kumahq/kuma, pull requests merged in 2023-12, with the labels that each got.

#8498 test(e2e): add retries to prevent some flakes
  test/e2e/helm/kuma_helm_deploy_global_universal_mode_and_zone.go
  test/e2e_env/multizone/localityawarelb/locality_aware_multizone_hybrid.go
  test/e2e_env/multizone/localityawarelb/locality_aware_multizone_hybrid_egress.go
Labels: ci/run-full-matrix

#8509 feat(kuma-cp): support cross-zone MeshTCPRoute
  pkg/xds/generator/ingress_generator_test.go
  pkg/xds/generator/testdata/ingress/with-meshtcproute-subset.envoy.golden.yaml
  pkg/xds/generator/zoneproxy/destinations.go
  test/e2e_env/multizone/multizone_suite_test.go
Labels: ci/run-full-matrix

#8514 ci(commitlint): disallow `tests` as scope it's a type
  .github/commitlint.config.js
Labels: ci/skip-test

#8533 chore(MeshAccessLog): improve policy's openapi schema
  app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present-not-enabled.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml
  app/kumactl/cmd/install/testdata/install-crds.all.golden.yaml
  app/kumactl/cmd/install/testdata/install-crds.experimental-gatewayapi.golden.yaml
  deployments/charts/kuma/crds/kuma.io_meshaccesslogs.yaml
  docs/generated/openapi.yaml
  docs/generated/raw/crds/kuma.io_meshaccesslogs.yaml
  pkg/plugins/policies/meshaccesslog/api/v1alpha1/meshaccesslog.go
  pkg/plugins/policies/meshaccesslog/api/v1alpha1/schema.yaml
  pkg/plugins/policies/meshaccesslog/k8s/crd/kuma.io_meshaccesslogs.yaml
Labels: kind/improvement, area/policies, ci/skip-e2e-test

#8532 chore(MeshTimeout): improve policy's openapi schema
  app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present-not-enabled.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml
  app/kumactl/cmd/install/testdata/install-crds.all.golden.yaml
  app/kumactl/cmd/install/testdata/install-crds.experimental-gatewayapi.golden.yaml
  deployments/charts/kuma/crds/kuma.io_meshtimeouts.yaml
  docs/generated/openapi.yaml
  docs/generated/raw/crds/kuma.io_meshtimeouts.yaml
  pkg/plugins/policies/meshtimeout/api/v1alpha1/meshtimeout.go
  pkg/plugins/policies/meshtimeout/api/v1alpha1/schema.yaml
  pkg/plugins/policies/meshtimeout/k8s/crd/kuma.io_meshtimeouts.yaml
Labels: kind/improvement, area/policies, ci/skip-e2e-test

#8535 ci(policy-gen): change "inplace" to "in-place"
  tools/policy-gen/bootstrap/root.go
Labels: ci/skip-test

#8539 chore(logging): add more context on errors from http servers
  app/kuma-dp/pkg/dataplane/metrics/server.go
  go.mod
  go.sum
  pkg/api-server/server.go
  pkg/diagnostics/server.go
  pkg/dp-server/server/server.go
  pkg/mads/server/server.go
Labels: ci/skip-e2e-test

#8547 ci(actions): stabilize the E2E tests for running on GH Actions by preventing binding to ipv6 ports when creating test containers
  .github/workflows/build-test-distribute.yaml
  .github/workflows/e2e.yaml
  test/framework/deployments/docker.go
  test/framework/deployments/observability/universal.go
  test/framework/docker.go
  test/framework/k8s_cluster.go
  test/framework/universal_app.go
Labels: ci/skip-test, no-backport-autolabel

#8552 ci(actions): pin git SHA to the same value as GH Actions when running e2e tests on CircleCI
  .circleci/config.yml
  .github/workflows/e2e.yaml
Labels: ci/skip-test, no-backport-autolabel

#8558 test(framework): try to fix flaky tests related to postgre db and k8s resource installation
  pkg/test/store/postgres/test_container.go
  test/framework/k8s_cluster.go
  test/framework/setup.go
Labels: no-backport-autolabel

#8556 chore(MeshProxyPatch): handle multiple modification types in a single object
  pkg/plugins/policies/meshproxypatch/api/v1alpha1/validator.go
  pkg/plugins/policies/meshproxypatch/api/v1alpha1/validator_test.go
Labels: kind/improvement, area/policies

#8566 test(e2e): skip change service
  test/e2e_env/kubernetes/kubernetes_suite_test.go
Labels: ci/skip-test

#8565 docs(MADR): add `to` to `MeshFaultInjection` for top level `MeshGateway`
  docs/madr/decisions/019-fault-injection-policy.md
Labels: ci/skip-test, ci/skip-e2e-test

#8449 docs(MADR): deprecate standalone mode
  docs/madr/decisions/033-deprecate-standalone.md
Labels: ci/skip-test

#8526 docs(MADR): `MeshMetric` policy
  docs/madr/decisions/035-mesh-metric-policy.md
  docs/madr/decisions/assets/035/meshmetric_diagram.png
Labels: ci/skip-test

#8572 ci(actions): improve the GH Actions format to make it better for sync…
  .github/workflows/build-test-distribute.yaml
  .github/workflows/e2e.yaml
Labels: area/ci-cd, no-backport-autolabel

#8597 fix(madr): change `MeshMetric` MADR to use prometheus client id instead of backend name for MADS
  docs/madr/decisions/035-mesh-metric-policy.md
Labels: ci/skip-test

#8603 ci(.github): make hooks easier in workflows
  .github/workflows/build-test-distribute.yaml
  .github/workflows/e2e.yaml
Labels: ci/skip-test

#8605 ci(.github): fix typo in bash script
  .github/workflows/build-test-distribute.yaml
Labels: ci/skip-test

#8606 ci(publish): don't use -i in docker
  mk/distribution.mk
Labels: ci/skip-test, backport

#8628 ci(github): use a ci_tools dir inside the checkout
  .github/workflows/build-test-distribute.yaml
  .gitignore
Labels: ci/skip-test

#8631 ci(.github): improve ci caching by including dynamic go-deps version in deps lock
  .github/workflows/build-test-distribute.yaml
  .github/workflows/e2e.yaml
  .gitignore
  mk/dependencies/deps.lock
  mk/dependencies/go-deps.sh
  tools/dev/install-dev-tools.sh
Labels: ci/skip-e2e-test, no-backport-autolabel

#8614 feat(routes): handle routing if there are no TrafficRoutes
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/listeners.go
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshtcproute/plugin/v1alpha1/listeners.go
  pkg/plugins/policies/meshtcproute/plugin/v1alpha1/listeners_backendrefs.go
  pkg/plugins/policies/meshtcproute/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshtcproute/plugin/v1alpha1/testdata/meshhttproute-clash-http-destination.clusters.golden.yaml
  pkg/plugins/policies/meshtcproute/plugin/v1alpha1/testdata/meshhttproute-clash-http-destination.endpoints.golden.yaml
  pkg/plugins/policies/meshtcproute/plugin/v1alpha1/testdata/meshhttproute-clash-http-destination.listeners.golden.yaml
  pkg/plugins/policies/meshtcproute/plugin/v1alpha1/testdata/meshhttproute-clash-tcp-destination.listeners.golden.yaml
  pkg/plugins/policies/meshtcproute/plugin/v1alpha1/testdata/redirect-traffic.listeners.golden.yaml
  pkg/xds/generator/outbound_proxy_generator.go
  pkg/xds/generator/proxy_template_profile_source_test.go
  pkg/xds/generator/zoneproxy/destinations.go
  test/e2e_env/kubernetes/meshhttproute/test.go
  test/e2e_env/kubernetes/meshtcproute/test.go
Labels: ci/run-full-matrix

#8649 ci(github): correct syntax of secrets in distribution
  .github/workflows/build-test-distribute.yaml
Labels: ci/skip-test

#8652 ci(github): set CI_TOOLS_DIR so that cache always works
  .github/workflows/helm-release.yaml
  .github/workflows/pr-comments.yaml
Labels: ci/skip-test

#8578 docs(MADR): update zone to global policy sync madr
  docs/madr/decisions/032-zone-to-global-policy-sync.md
Labels: ci/skip-test

#8655 ci(github): add arch in cache keys
  .github/workflows/blackbox-tests.yaml
  .github/workflows/build-test-distribute.yaml
  .github/workflows/e2e.yaml
  .github/workflows/helm-release.yaml
  .github/workflows/pr-comments.yaml
Labels: ci/skip-test

#8636 ci(docs): change auto-generated docs path in kuma-website
  .github/workflows/update-docs.yaml
Labels: ci/skip-test

#8677 chore(deps): fix update insecure dependencies by setting bigger swap
  .github/workflows/update-insecure-dependencies.yaml
Labels: ci/skip-test

#8494 chore(lock): only error log after 3 retries
  pkg/plugins/leader/postgres/leader_elector.go
Labels: ci/run-full-matrix

#8680 ci(github): use concurrency to avoid multiple CI in PRs
  .github/workflows/build-test-distribute.yaml
Labels: ci/skip-test

#8682 test(postgres): simplify tests to hope to get stability
  .github/dependabot.yml
  pkg/plugins/leader/postgres/leader_elector_test.go
  pkg/plugins/leader/postgres/postgres_suite_test.go
  pkg/plugins/resources/postgres/listener_test.go
  pkg/plugins/resources/postgres/migrate.go
  pkg/plugins/resources/postgres/migrate_test.go
  pkg/plugins/resources/postgres/plugin.go
  pkg/plugins/resources/postgres/store_suite_test.go
  pkg/plugins/resources/postgres/store_template_test.go
  pkg/test/store/postgres/test_container.go
Labels: ci/skip-e2e-test

#8679 test(framework): get logs from pods when it's not available to help diagnose CI issues
  test/framework/k8s.go
Labels: ci/skip-test

#8704 chore(deps): bump github.com/envoyproxy/go-control-plane from 0.11.0 to 0.11.1
  go.mod
  go.sum
  pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/testdata/basic_http_health_check_cluster.golden.yaml
  pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/testdata/basic_http_health_check_split_cluster.golden.yaml
  pkg/plugins/policies/meshhealthcheck/plugin/xds/configurer.go
Labels: release-2.1

#8692 ci(github): don't have update docs trigger on non release branches
  .github/workflows/update-docs.yaml
Labels: ci/skip-test

#8489 docs(MADR): support `MeshHTTPRoute` with `MeshGateway`
  docs/madr/decisions/033-meshhttproute-meshgateway.md
Labels: ci/skip-test

#8710 ci(github): use GitHub public artifact API when downloading artifacts from CircleCI
  .circleci/config.yml
  .github/workflows/e2e.yaml
Labels: ci/skip-test

#8722 ci(github): collapse helm release inside build-test-distribute
  .github/workflows/build-test-distribute.yaml
  .github/workflows/helm-release.yaml
Labels: ci/skip-test
