Repository kumahq/kuma, pull requests merged in 2024-11, with the labels that each got.

#11981 test(e2e): disable helm deploy / admin ops test while investigating flake
  test/e2e/helm/kuma_helm_deploy_global_zone.go
Labels: ci/skip-test

#11988 feat(kuma-cp): allow missing transparent proxy ConfigMap or empty in k8s
  deployments/charts/kuma/templates/_helpers.tpl
  deployments/charts/kuma/templates/cp-configmap.yaml
  pkg/plugins/runtime/k8s/webhooks/injector/injector.go
Labels: ci/run-full-matrix

#11997 fix(kuma-cp): avoid concurrent access on resource meta
  pkg/kds/util/meta.go
  pkg/kds/util/resource.go
  pkg/plugins/resources/memory/store.go
  pkg/plugins/resources/remote/store.go
  pkg/plugins/secrets/k8s/store.go
Labels: backport

#12000 chore(deps): change go-control-plane version
  go.mod
  go.sum
  pkg/xds/envoy/imports.go
Labels: ci/run-full-matrix, backport

#12043 fix(meshtimeout): don't set default timeouts on inbound cluster and listener
  pkg/plugins/policies/meshtimeout/plugin/testdata/basic_without_defaults_inbound_cluster.golden.yaml
  pkg/plugins/policies/meshtimeout/plugin/testdata/basic_without_defaults_inbound_listener.golden.yaml
  pkg/plugins/policies/meshtimeout/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshtimeout/plugin/v1alpha1/plugin_test.go
Labels: backport

#12062 ci(github): bump github action create-pull-request from v0.5.2 to v0.5.3
  .github/workflows/release.yaml
  .github/workflows/update-docs.yaml
  .github/workflows/update-insecure-dependencies.yaml
Labels: release-2.6

#12087 chore(deps): upgrade go from 1.22.8 to 1.22.9
  go.mod
Labels: release-2.6

#12086 chore(deps): upgrade go from 1.22.8 to 1.22.9
  go.mod
Labels: release-2.7

#12085 chore(deps): upgrade go from 1.22.8 to 1.22.9
  go.mod
Labels: release-2.8

#12084 chore(deps): upgrade go from 1.23.2 to 1.23.3
  go.mod
Labels: release-2.9

#12038 chore(deps): remove deprecated protobuf dependency
  .golangci.yml
  pkg/core/xds/resource.go
  pkg/mads/v1/service/http.go
  pkg/mads/v1/service_test.go
  pkg/plugins/policies/meshloadbalancingstrategy/plugin/xds/lbconfigurer.go
  pkg/plugins/runtime/gateway/suite_test.go
  pkg/test/kds/verifier/executables.go
  pkg/util/cache/v3/cache.go
  pkg/util/envoy/raw.go
  pkg/util/proto/any.go
  pkg/util/proto/proto.go
  pkg/xds/generator/modifications/v3/cluster.go
  pkg/xds/generator/modifications/v3/listener.go
Labels: ci/run-full-matrix

#12096 chore(gha): replace new line with whitespace and change to array
  .github/workflows/ci-stability.yaml
Labels: ci/skip-test, ci/skip-e2e-test

#12108 test(e2e): disable meshmtls test with delegated gateway
  test/e2e_env/kubernetes/gateway/delegated.go
  test/e2e_env/kubernetes/gateway/delegated/meshtls.go
Labels: backport

#12131 chore(images): pin ubuntu version
  .github/workflows/build-test-distribute.yaml
Labels: ci/skip-test, ci/skip-e2e-test, release-2.6

#12129 chore(images): pin ubuntu version
  .github/workflows/_build_publish.yaml
Labels: ci/skip-test, ci/skip-e2e-test, release-2.8

#12132 ci(docs): remove version before 2.2.x from automation of versions.yaml
  .github/workflows/release.yaml
Labels: ci/skip-test

#12135 docs(UPGRADE.md): remove links to docs that are not longer published
  UPGRADE.md
Labels: ci/skip-test

#12091 docs(maintainer): maintainer nomination
  OWNERS.md
Labels: ci/skip-test, ci/skip-e2e-test, gitvote
