Repository kumahq/kuma, pull requests merged in 2024-12, with the labels that each got.

#12144 chore(e2e): disable flaking TrafficRoute multizone e2e_env test
  test/e2e_env/multizone/trafficroute/trafficroute.go
Labels: ci/skip-test

#12152 fix(meshtrafficpermission): nil pointer for autoreachableservice when no top targetRef
  pkg/plugins/policies/meshtrafficpermission/graph/backends/reachable_backend_refs_graph.go
  pkg/plugins/policies/meshtrafficpermission/graph/reachable_backend_refs_graph_test.go
  pkg/plugins/policies/meshtrafficpermission/graph/reachable_services_graph_test.go
  pkg/plugins/policies/meshtrafficpermission/graph/services/reachable_services_graph.go
Labels: backport

#12149 ci(gh): allow to run `build-test-distribute` on `workflow_dispatch`
  .github/workflows/build-test-distribute.yaml
Labels: ci/skip-test

#12164 docs(MADR): improve state of the ci on release branches - periodic runs
  docs/madr/decisions/068-improve-the-state-of-the-ci-on-release-branches-periodic-ci-runs.md
Labels: area/ci-cd, kind/docs, ci/skip-test

#12176 ci(gatewayapi): update crd version
  test/framework/k8s.go
Labels: ci/run-full-matrix

#12137 docs(maintainer): maintainer nomination
  OWNERS.md
Labels: ci/skip-test, gitvote

#12182 ci(github): fix footnote link
  .github/workflows/check.yaml
Labels: ci/skip-test

#12177 ci(SBOM): improve SBOM accuracy and remove false positives from the CVE report
  .github/workflows/build-test-distribute.yaml
  .syft.yaml
Labels: ci/skip-test

#12215 chore(deps): upgrade envoy to version v1.32.2
  mk/dependencies/deps.lock
  mk/dev.mk
Labels: master

#12220 chore(deps): upgrade golang from 1.23.3 to 1.23.4
  go.mod
Labels: master

#12216 chore(deps): upgrade envoy to version v1.29.11
  tools/releases/version.sh
Labels: release-2.6

#12217 chore(deps): upgrade envoy to version v1.29.11
  mk/dependencies/deps.lock
  mk/dev.mk
Labels: release-2.7

#12218 chore(deps): upgrade envoy to version v1.30.8
  mk/dependencies/deps.lock
  mk/dev.mk
Labels: release-2.8

#12219 chore(deps): upgrade envoy to version v1.30.8
  mk/dependencies/deps.lock
  mk/dev.mk
Labels: release-2.9

#12221 chore(deps): upgrade golang from 1.22.9 to 1.22.10
  go.mod
Labels: release-2.6

#12222 chore(deps): upgrade golang from 1.22.9 to 1.22.10
  go.mod
Labels: release-2.7

#12223 chore(deps): upgrade golang from 1.22.9 to 1.22.10
  go.mod
Labels: release-2.8

#12224 chore(deps): upgrade golang from 1.23.3 to 1.23.4
  go.mod
Labels: release-2.9

#12231 ci(gh): allow to run `build-test-distribute` on `workflow_dispatch`
  .github/workflows/build-test-distribute.yaml
Labels: ci/skip-test

#12234 ci(gh): allow to run build-test-distribute on workflow_dispatch
  .github/workflows/build-test-distribute.yaml
Labels: ci/skip-test

#12233 ci(gh): allow to run `build-test-distribute` on `workflow_dispatch`
  .github/workflows/build-test-distribute.yaml
Labels: ci/skip-test

#12235 ci(gh): increate timeout for `check` job in `built-test-distribute`
  .github/workflows/build-test-distribute.yaml
Labels: ci/skip-test

#12232 ci(gh): allow to run `build-test-distribute` on `workflow_dispatch`
  .github/workflows/build-test-distribute.yaml
Labels: ci/skip-test

#12252 ci(github): sanitize title input in pr-check action
  .github/workflows/check.yaml
Labels: ci/skip-test

#12264 fix(kds): remove context from map on stream close (backport of #12243)
  pkg/kds/v2/server/tenant_callback.go
Labels: release-2.7

#12263 fix(kds): remove context from map on stream close (backport of #12243)
  pkg/kds/v2/server/tenant_callback.go
Labels: release-2.8

#12262 fix(kds): remove context from map on stream close (backport of #12243)
  pkg/kds/v2/server/tenant_callback.go
Labels: release-2.9

#12256 ci(github): add workflow to check ci stability of release branches
  .github/workflows/ci-stability-release-branches.yaml
Labels: ci/skip-test

#12289 ci(github): make workflow id to trigger for ci-stability-release-branches workflow configurable
  .github/workflows/build-test-distribute.yaml
  .github/workflows/ci-stability-release-branches.yaml
Labels: ci/skip-test

#12290 ci(github): set the correct id of workflow to trigger for CI stability
  .github/workflows/build-test-distribute.yaml
  .github/workflows/ci-stability-release-branches.yaml
Labels: ci/skip-test

#12291 chore(mk): fix k3d start errors when using calico CNI
  mk/k3d.mk
Labels: backport

#12299 ci(github): rewrite ci-stability-release-branches workflow to bash
  .github/workflows/ci-stability-release-branches.yaml
Labels: ci/skip-test

#12307 ci(github): remove trailing space from ci-stability-release-branches
  .github/workflows/ci-stability-release-branches.yaml
Labels: ci/skip-test

#12272 feat(oapi): add mesh and meshgateway to oapi spec
  api/mesh/v1alpha1/mesh/rest.yaml
  api/mesh/v1alpha1/mesh/schema.yaml
  api/mesh/v1alpha1/meshgateway/rest.yaml
  api/mesh/v1alpha1/meshgateway/schema.yaml
  docs/generated/openapi.yaml
  go.mod
  go.sum
  mk/docs.mk
  mk/generate.mk
  tools/openapi/templates/endpoints.yaml
  tools/openapi/templates/schema.yaml
  tools/policy-gen/crd-extract-openapi.sh
  tools/resource-gen/genutils/util.go
  tools/resource-gen/main.go
Labels: ci/skip-e2e-test

#12329 feat(oapi): properly marshal proto struct and set paths
  api/mesh/v1alpha1/mesh/schema.yaml
  docs/generated/openapi.yaml
  mk/generate.mk
  tools/resource-gen/main.go
Labels: ci/skip-e2e-test

#12330 feat(oapi): fix missing dependency
  mk/generate.mk
Labels: ci/skip-test

#12336 feat(oapi): fix out dir
  tools/resource-gen/main.go
Labels: ci/skip-test

#12351 chore(gha): inherit secrets
  .github/workflows/build-test-distribute.yaml
Labels: release-2.6
