Repository kumahq/kuma, pull requests merged in 2024-09, with the labels that each got.

#11275 chore(transparent-proxy): cleanup in transparent-proxy source code
  pkg/transparentproxy/config/config.go
  pkg/transparentproxy/config/config_executables.go
  pkg/transparentproxy/config/config_executables_linux.go
  pkg/transparentproxy/config/config_logger.go
  pkg/transparentproxy/config/utils.go
  pkg/transparentproxy/iptables/builder/builder.go
  pkg/transparentproxy/iptables/builder/builder_table_mangle.go
  pkg/transparentproxy/iptables/builder/builder_table_nat.go
  pkg/transparentproxy/iptables/builder/builder_table_raw.go
  pkg/transparentproxy/iptables/chains/chains.go
  pkg/transparentproxy/iptables/consts/consts.go
  pkg/transparentproxy/iptables/parameters/match_conntrack.go
  pkg/transparentproxy/iptables/parameters/parameters.go
  pkg/transparentproxy/iptables/rules/rules.go
  pkg/transparentproxy/iptables/setup.go
Labels: ci/skip-test

#11278 fix(kuma-cp): handle cases when requested BackendRefIdentifier contains ports
  pkg/plugins/policies/meshtrafficpermission/graph/reachable_graph.go
Labels: ci/run-full-matrix

#11277 fix(transparent-proxy): use found executable path
  pkg/transparentproxy/config/config_executables.go
Labels: ci/run-full-matrix

#10860 docs(MADR): add MeshService migration
  docs/madr/decisions/056-meshservice-migration.md
Labels: ci/skip-test

#11302 feat(transparent-proxy): enable custom iptables binaries paths configuration
  app/kumactl/cmd/completion/testdata/bash.golden
  app/kumactl/cmd/install/install_transparent_proxy.go
  pkg/transparentproxy/config/config.go
  pkg/transparentproxy/config/config_executables.go
  pkg/transparentproxy/iptables/consts/consts.go
Labels: ci/run-full-matrix

#11316 refactor(transparent-proxy): move `contsts` package and remove dot imports
  app/kumactl/cmd/install/install_transparent_proxy.go
  pkg/transparentproxy/config/config.go
  pkg/transparentproxy/config/config_executables.go
  pkg/transparentproxy/config/config_executables_functionality.go
  pkg/transparentproxy/config/config_executables_linux.go
  pkg/transparentproxy/config/utils.go
  pkg/transparentproxy/consts/consts.go
  pkg/transparentproxy/iptables/builder/builder_table_nat.go
  pkg/transparentproxy/iptables/builder/builder_table_nat_test.go
  pkg/transparentproxy/iptables/builder/builder_table_raw.go
  pkg/transparentproxy/iptables/chains/chains.go
  pkg/transparentproxy/iptables/parameters/protocol.go
  pkg/transparentproxy/iptables/rules/rules.go
  pkg/transparentproxy/iptables/setup.go
  pkg/transparentproxy/iptables/tables/table_mangle.go
  pkg/transparentproxy/iptables/tables/table_nat.go
  pkg/transparentproxy/iptables/tables/table_raw.go
  pkg/transparentproxy/iptables/tables/tables.go
  pkg/transparentproxy/test/config.go
  test/blackbox_network_tests/dns_test.go
  test/blackbox_network_tests/outbound_redirect_test.go
Labels: ci/skip-test

#11324 docs(upgrade.md): minor enhancement on upgrade notes of app probe proxy
  UPGRADE.md
Labels: ci/skip-test

#11342 ci(e2e/framework): don't fail when some debug commands will fail
  test/framework/debug.go
Labels: backport

#11350 feat(meshexternalservice): remove unix support
  UPGRADE.md
  app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml
  app/kumactl/cmd/install/testdata/install-crds.all.golden.yaml
  deployments/charts/kuma/crds/kuma.io_meshexternalservices.yaml
  docs/generated/openapi.yaml
  docs/generated/raw/crds/kuma.io_meshexternalservices.yaml
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/meshexternalservice.go
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/schema.yaml
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/testdata/full-invalid.input.yaml
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/testdata/full-invalid.output.yaml
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/testdata/full-without-extension-valid.input.yaml
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/validator.go
  pkg/core/resources/apis/meshexternalservice/k8s/crd/kuma.io_meshexternalservices.yaml
  pkg/xds/topology/outbound.go
  pkg/xds/topology/outbound_test.go
Labels: ci/skip-test

#11110 fix(kuma-cp): use contexts instead of channels in watchdog
  pkg/hds/tracker/callbacks.go
  pkg/kds/v2/reconcile/interfaces.go
  pkg/kds/v2/reconcile/reconciler.go
  pkg/kds/v2/server/components.go
  pkg/kds/v2/server/event_based_watchdog.go
  pkg/kds/v2/server/event_based_watchdog_test.go
  pkg/mads/v1/service/components.go
  pkg/mads/v1/service_test.go
  pkg/util/watchdog/watchdog.go
  pkg/util/watchdog/watchdog_test.go
  pkg/util/xds/v3/watchdog_callbacks.go
  pkg/xds/server/callbacks/dataplane_sync_tracker.go
  pkg/xds/server/callbacks/dataplane_sync_tracker_test.go
  pkg/xds/sync/dataplane_watchdog_factory.go
  pkg/xds/sync/interfaces.go
Labels: ci/run-full-matrix

#11386 ci(actions): add more segments to artifacts name to avoid conflicts
  .github/workflows/_e2e.yaml
Labels: ci/skip-test, backport

#11392 chore(dev): improve k3d/deploy make targets
  mk/k3d.mk
Labels: ci/skip-test

#11393 chore(dev): set all image tags if run on clean branch in k3d/deploy targets
  mk/k3d.mk
Labels: ci/skip-test

#11400 ci(gh/actions): add parallelRunnerId to e2e debug artifact name
  .github/workflows/_e2e.yaml
Labels: ci/skip-test

#11401 chore(config/loader): remove logs when loading configs
  pkg/config/loader.go
Labels: ci/skip-test

#11327 perf(k8s): do not update resource on control-plane restart
  pkg/plugins/runtime/k8s/controllers/gateway_converter.go
  pkg/plugins/runtime/k8s/controllers/pod_controller.go
  pkg/plugins/runtime/k8s/controllers/pod_controller_test.go
  pkg/plugins/runtime/k8s/controllers/pod_converter.go
  pkg/plugins/runtime/k8s/controllers/pod_converter_test.go
  pkg/plugins/runtime/k8s/controllers/testdata/ingress/ingress-exists.golden.yaml
  pkg/plugins/runtime/k8s/util/errors.go
Labels: ci/run-full-matrix

#11399 fix(k8s): always authenticate with latest service account token
  pkg/config/dp-server/config.go
  pkg/xds/bootstrap/components.go
Labels: ci/run-full-matrix

#11403 feat(transparent-proxy): allow to use tproxy config from configmap in kubernetes
  app/cni/pkg/cni/annotations_linux.go
  app/cni/pkg/cni/injector_linux.go
  app/cni/pkg/cni/main_linux.go
  app/kumactl/cmd/install/testdata/install-control-plane.dump-values.yaml
  deployments/charts/kuma/README.md
  deployments/charts/kuma/templates/_helpers.tpl
  deployments/charts/kuma/templates/cp-configmap.yaml
  deployments/charts/kuma/templates/cp-rbac.yaml
  deployments/charts/kuma/values.yaml
  docs/generated/raw/helm-values.yaml
  pkg/config/loader_test.go
  pkg/config/plugins/runtime/k8s/config.go
  pkg/config/plugins/runtime/k8s/testdata/default-config.golden.yaml
  pkg/plugins/runtime/k8s/metadata/annotations.go
  pkg/plugins/runtime/k8s/probes/pod_probe_overrider.go
  pkg/plugins/runtime/k8s/webhooks/injector/injector.go
  pkg/transparentproxy/config/config.go
  pkg/transparentproxy/config/config_executables.go
  pkg/transparentproxy/consts/consts.go
  pkg/transparentproxy/kubernetes/kubernetes.go
  pkg/transparentproxy/kubernetes/kubernetes_config.go
  pkg/transparentproxy/kubernetes/kubernetes_test.go
Labels: ci/run-full-matrix

#11180 fix(xds): accelerate universal dp XDS generation
  pkg/xds/server/callbacks/dataplane_lifecycle.go
  pkg/xds/server/callbacks/dataplane_lifecycle_test.go
  pkg/xds/server/v3/components.go
Labels: ci/run-full-matrix

#11462 fix(policy): verify zone if dpp origin is zone and metadata exists
  pkg/api-server/testdata/resources/inspect/policies/_resources/dataplanes/meshtimeout_consumer_dataplanes.golden.json
  pkg/plugins/policies/core/matchers/dataplane.go
Labels: ci/run-full-matrix

#11463 fix(e2e): stabilize the gatewayapi E2E conformance tests by ignoring headless service cases
  test/e2e_env/gatewayapi/conformance_test.go
Labels: ci/run-full-matrix

#11488 chore(deps): upgrade envoy to 1.30.6
  mk/dependencies/deps.lock
  mk/dev.mk
Labels: master

#11484 chore(deps): upgrade envoy to 1.28.7
  tools/releases/version.sh
Labels: release-2.5

#11485 chore(deps): upgrade envoy to 1.28.7
  tools/releases/version.sh
Labels: release-2.6

#11487 chore(deps): upgrade envoy to 1.30.6
  mk/dependencies/deps.lock
  mk/dev.mk
Labels: release-2.8

#11486 chore(deps): upgrade envoy to 1.29.9
  mk/dependencies/deps.lock
  mk/dev.mk
Labels: release-2.7

#11506 test(framework): dont print CP logs to stdout on Universal as they can be too long
  test/framework/envs/universal/env.go
Labels: ci/skip-test

#11511 fix(kumactl): declare meshes before secrets when exporting
  app/kumactl/cmd/export/export.go
  app/kumactl/cmd/export/testdata/export-kube.golden.yaml
  app/kumactl/cmd/export/testdata/export-no-dp.golden.yaml
  app/kumactl/cmd/export/testdata/export.golden.yaml
Labels: ci/run-full-matrix

#11427 chore(kuma-cp): reenable ZoneEgress ES e2e test for ARM
  test/e2e/zoneegress/externalservices/e2e_suite_test.go
Labels: ci/run-full-matrix

#11527 test(gatewayapi): cleanup resources to unblock the gatewayapi job
  test/e2e_env/gatewayapi/conformance_test.go
Labels: ci/skip-test

#11533 ci(gha): bump timeout for image build
  .github/workflows/_build_publish.yaml
Labels: ci/skip-test, ci/skip-e2e-test

#11532 fix(kumactl): don't export full Mesh before secrets on Kubernetes
  app/kumactl/cmd/export/export.go
  app/kumactl/cmd/export/testdata/export-kube.golden.yaml
Labels: ci/run-full-matrix

#11543 ci(workflow): skip cis docker scan
  .github/workflows/_build_publish.yaml
Labels: ci/skip-test

#11539 fix(e2e): don't reuse namespace for helm upgrade test
  test/e2e/helm/kuma_helm_upgrade_multizone.go
Labels: ci/run-full-matrix

#11548 fix(MeshTrace): invalid sampling default values
  app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml
  app/kumactl/cmd/install/testdata/install-crds.all.golden.yaml
  deployments/charts/kuma/crds/kuma.io_meshtraces.yaml
  docs/generated/openapi.yaml
  docs/generated/raw/crds/kuma.io_meshtraces.yaml
  pkg/plugins/policies/meshtrace/api/v1alpha1/meshtrace.go
  pkg/plugins/policies/meshtrace/api/v1alpha1/schema.yaml
  pkg/plugins/policies/meshtrace/k8s/crd/kuma.io_meshtraces.yaml
Labels: backport

#11564 chore(debug): get envoy logs in docker logs on universal tests
  test/framework/universal_app.go
Labels: ci/run-full-matrix

#11561 ci(e2e): run `K8S_MIN_VERSION` tests on arm64
  .github/workflows/_test.yaml
  test/e2e/zoneegress/externalservices/e2e_suite_test.go
Labels: ci/run-full-matrix

#11593 ci(debug): prolong debug artifacts retention
  .github/workflows/_e2e.yaml
Labels: ci/skip-test
