Repository kumahq/kuma, pull requests merged in 2024-05, with the labels that each got.

#9692 docs(MADR): mesh service vips and hostnames
  docs/madr/decisions/046-meshservice-hostname-vips.md
Labels: ci/skip-test

#9964 docs(MADR): grpc and tcp virtual probes
  docs/madr/decisions/047-grpc-tcp-probes.md
Labels: ci/skip-test

#10206 refactor(transparent-proxy): simplify more tproxy configuration
  app/cni/pkg/cni/injector_linux.go
  app/kumactl/cmd/install/install_transparent_proxy.go
  pkg/transparentproxy/config/config.go
  pkg/transparentproxy/iptables/builder/builder.go
Labels: area/kumactl, kind/cleanup

#10207 refactor(transparent-proxy): allow config to be initialized
  app/cni/pkg/cni/injector_linux.go
  app/kumactl/cmd/install/install_transparent_proxy.go
  app/kumactl/cmd/uninstall/uninstall_transparent_proxy.go
  pkg/transparentproxy/config/config.go
  pkg/transparentproxy/ebpf/cleanup.go
  pkg/transparentproxy/ebpf/cleanup_fallback.go
  pkg/transparentproxy/ebpf/ebpf.go
  pkg/transparentproxy/ebpf/program.go
  pkg/transparentproxy/ebpf/setup.go
  pkg/transparentproxy/ebpf/setup_fallback.go
  pkg/transparentproxy/iptables/builder/builder.go
  pkg/transparentproxy/iptables/builder/builder_restore.go
  pkg/transparentproxy/iptables/builder/builder_table_mangle.go
  pkg/transparentproxy/iptables/builder/builder_table_nat.go
  pkg/transparentproxy/iptables/builder/builder_table_nat_test.go
  pkg/transparentproxy/iptables/builder/builder_table_raw.go
  pkg/transparentproxy/iptables/builder/dns.go
  pkg/transparentproxy/iptables/builder/loopback.go
  pkg/transparentproxy/iptables/consts/consts.go
  pkg/transparentproxy/iptables/setup.go
  pkg/transparentproxy/test/config.go
  pkg/transparentproxy/transparentproxy.go
  test/blackbox_network_tests/dns_test.go
  test/blackbox_network_tests/inbound_redirect_test.go
  test/blackbox_network_tests/outbound_redirect_test.go
Labels: area/kumactl, kind/cleanup

#10205 docs(MADR): mesh service universal ux
  docs/madr/decisions/048-meshservice-universal-ux.md
Labels: ci/skip-test

#10220 chore(cni): don't redirect inbound for gateway in CNI
  app/cni/pkg/cni/injector_linux.go
Labels: ci/run-full-matrix

#9979 docs(MADR): mesh service multizone ux
  docs/madr/decisions/049-meshservice-multizone.md
Labels: ci/skip-test

#10245 fix(kuma-cp): filter out old dangling zone resources in global
  pkg/kds/global/components.go
  pkg/kds/v2/store/sync.go
Labels: ci/run-full-matrix, release-2.6

#10252 ci(.circleci): update ubuntu image
  .circleci/config.yml
Labels: ci/run-full-matrix, release-2.6

#10259 ci(circleci): revert "ci(.circleci): update ubuntu image (#10252)"
  .circleci/config.yml
Labels: release-2.6

#10268 fix(kuma-cp): filter out old dangling zone resources in global (backport of #10245)
  pkg/kds/global/components.go
  pkg/kds/v2/store/sync.go
Labels: release-2.7

#10275 chore(deps): upgrade ci-tools to v0.13.0
  .github/workflows/release.yaml
Labels: ci/skip-test

#10278 chore(deps): upgrade ci-tools to v.0.13.1
  .github/workflows/release.yaml
Labels: ci/skip-test

#10243 feat(k8s): add kubernetes.io/hostname to default node labels to copy
  docs/generated/raw/kuma-cp.yaml
  pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
  pkg/config/plugins/runtime/k8s/config.go
  pkg/config/plugins/runtime/k8s/testdata/default-config.golden.yaml
Labels: ci/skip-e2e-test

#10229 docs(MADR): meshExternalService API madr
  docs/madr/decisions/050-meshexternalservice-api.md
Labels: ci/skip-test, ci/skip-e2e-test

#10253 docs(MADR): meshpassthrough design
  docs/madr/decisions/051-mesh-passthrough.md
Labels: ci/skip-test, ci/skip-e2e-test

#10293 feat(meshexternalservice): api implementation
  app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml
  app/kumactl/cmd/install/testdata/install-crds.all.golden.yaml
  deployments/charts/kuma/crds/kuma.io_meshexternalservices.yaml
  docs/generated/raw/crds/kuma.io_meshexternalservices.yaml
  docs/madr/decisions/050-meshexternalservice-api.md
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/meshexternalservice.go
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/schema.yaml
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/validator.go
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/zz_generated.deepcopy.go
  pkg/core/resources/apis/meshexternalservice/k8s/crd/kuma.io_meshexternalservices.yaml
  pkg/core/resources/apis/meshexternalservice/k8s/v1alpha1/zz_generated.deepcopy.go
Labels: ci/skip-e2e-test

#10215 ci(.github): publish slsa artifacts to cloudsmith
  .github/workflows/_build_publish.yaml
  .github/workflows/build-test-distribute.yaml
  mk/distribution.mk
  mk/docker.mk
Labels: ci/run-full-matrix, ci/skip-test, ci/skip-e2e-test, ci/force-publish

#10148 docs(MADR): policy on namespace
  docs/madr/decisions/052-policy-on-namespace.md
Labels: ci/skip-test

#10306 feat(MeshExternalService): implement validator
  app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml
  app/kumactl/cmd/install/testdata/install-crds.all.golden.yaml
  deployments/charts/kuma/crds/kuma.io_meshexternalservices.yaml
  docs/generated/raw/crds/kuma.io_meshexternalservices.yaml
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/meshexternalservice.go
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/schema.yaml
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/suite_test.go
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/testdata/full-invalid.input.yaml
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/testdata/full-invalid.output.yaml
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/testdata/full-without-extension-valid.input.yaml
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/testdata/full-without-extension-valid.output.yaml
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/testdata/min-higher-than-max-invalid.input.yaml
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/testdata/min-higher-than-max-invalid.output.yaml
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/testdata/minimal-invalid-extension.input.yaml
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/testdata/minimal-invalid-extension.output.yaml
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/testdata/minimal-invalid.input.yaml
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/testdata/minimal-invalid.output.yaml
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/testdata/minimal-valid.input.yaml
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/testdata/minimal-valid.output.yaml
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/testdata/missing-client-cert-invalid.input.yaml
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/testdata/missing-client-cert-invalid.output.yaml
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/validator.go
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/validator_test.go
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/zz_generated.deepcopy.go
  pkg/core/resources/apis/meshexternalservice/k8s/crd/kuma.io_meshexternalservices.yaml
Labels: ci/skip-e2e-test

#10331 feat(mk): add possibility to configure extra args for shellcheck
  mk/check.mk
Labels: ci/skip-test

#10332 ci(check): improve find call for shellcheck
  mk/check.mk
Labels: ci/skip-test

#10315 fix(kds): fix the case when webhook/db reject resource
  pkg/kds/v2/server/resource_retry_forcer.go
Labels: backport
