Repository kumahq/kuma, pull requests merged in 2024-06, with the labels that each got.

#10317 ci(lint): don't accidentally append to non-zero length slices
  .golangci.yml
  api/common/v1alpha1/ref.go
  app/kumactl/cmd/install/install_observability.go
Labels: ci/skip-test, ci/skip-e2e-test

#10152 docs(MADR): add policy matching for `MeshService`
  docs/madr/decisions/046-meshservice-policy-matching.md
Labels: ci/skip-test

#10382 chore(deps): bump envoy version from 1.27.5 to 1.27.6
  tools/releases/version.sh
Labels: release-2.3

#10385 chore(deps): bump envoy version from 1.28.3 to 1.28.4
  tools/releases/version.sh
Labels: release-2.5

#10412 chore(deps): ignore go-control-plane updates by dependabot
  .github/dependabot.yml
Labels: ci/skip-test, backport

#10386 chore(deps): bump envoy version from 1.28.3 to 1.28.4
  tools/releases/version.sh
Labels: ci/run-full-matrix, release-2.6

#10388 docs(MADR): multizone sni
  docs/madr/decisions/053-sni.md
Labels: ci/skip-test

#10441 docs(MADR): mesh service identity sync
  docs/madr/decisions/054-meshservice-identity-sync.md
Labels: ci/skip-test

#10445 feat(meshexternalservice): add servername
  app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml
  app/kumactl/cmd/install/testdata/install-crds.all.golden.yaml
  deployments/charts/kuma/crds/kuma.io_meshexternalservices.yaml
  docs/generated/raw/crds/kuma.io_meshexternalservices.yaml
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/meshexternalservice.go
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/schema.yaml
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/testdata/full-invalid.input.yaml
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/testdata/full-invalid.output.yaml
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/testdata/full-without-extension-valid.input.yaml
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/validator.go
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/zz_generated.deepcopy.go
  pkg/core/resources/apis/meshexternalservice/k8s/crd/kuma.io_meshexternalservices.yaml
Labels: ci/skip-e2e-test

#10448 chore(k3d): define ipv6 subnet only when ipv6 test
  mk/k3d.mk
Labels: ci/run-full-matrix

#10446 test(refactor): change the name from WithMesh to WithMeshBuilder
  pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/plugin_test.go
  pkg/plugins/policies/meshcircuitbreaker/plugin/v1alpha1/plugin_test.go
  pkg/plugins/policies/meshfaultinjection/plugin/v1alpha1/plugin_test.go
  pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/plugin_test.go
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/plugin_test.go
  pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/plugin_test.go
  pkg/plugins/policies/meshmetric/plugin/v1alpha1/plugin_test.go
  pkg/plugins/policies/meshratelimit/plugin/v1alpha1/plugin_test.go
  pkg/plugins/policies/meshretry/plugin/v1alpha1/plugin_test.go
  pkg/plugins/policies/meshtcproute/plugin/v1alpha1/plugin_test.go
  pkg/plugins/policies/meshtimeout/plugin/v1alpha1/plugin_test.go
  pkg/plugins/policies/meshtrafficpermission/plugin/v1alpha1/plugin_test.go
  pkg/test/xds/builders/context_builder.go
  pkg/test/xds/samples/meshcontext_samples.go
Labels: ci/skip-e2e-test

#10454 chore(mk): support extra targets for `make docs`
  mk/docs.mk
Labels: ci/skip-test

#10458 fix(meshpassthrough): fix build
  pkg/plugins/policies/meshpassthrough/plugin/v1alpha1/plugin_test.go
Labels: ci/skip-e2e-test

#10455 ci(policies): include labels and status in openapi spec
  docs/generated/openapi.yaml
  mk/docs.mk
  mk/generate.mk
  pkg/core/resources/apis/donothingresource/api/v1alpha1/rest.yaml
  pkg/core/resources/apis/donothingresource/api/v1alpha1/schema.yaml
  pkg/core/resources/apis/hostnamegenerator/api/v1alpha1/schema.yaml
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/schema.yaml
  pkg/core/resources/apis/meshservice/api/v1alpha1/schema.yaml
  pkg/plugins/policies/donothingpolicy/api/v1alpha1/schema.yaml
  pkg/plugins/policies/meshaccesslog/api/v1alpha1/schema.yaml
  pkg/plugins/policies/meshcircuitbreaker/api/v1alpha1/schema.yaml
  pkg/plugins/policies/meshfaultinjection/api/v1alpha1/schema.yaml
  pkg/plugins/policies/meshhealthcheck/api/v1alpha1/schema.yaml
  pkg/plugins/policies/meshhttproute/api/v1alpha1/schema.yaml
  pkg/plugins/policies/meshloadbalancingstrategy/api/v1alpha1/schema.yaml
  pkg/plugins/policies/meshmetric/api/v1alpha1/schema.yaml
  pkg/plugins/policies/meshpassthrough/api/v1alpha1/meshpassthrough.go
  pkg/plugins/policies/meshpassthrough/api/v1alpha1/schema.yaml
  pkg/plugins/policies/meshproxypatch/api/v1alpha1/schema.yaml
  pkg/plugins/policies/meshratelimit/api/v1alpha1/schema.yaml
  pkg/plugins/policies/meshretry/api/v1alpha1/schema.yaml
  pkg/plugins/policies/meshtcproute/api/v1alpha1/schema.yaml
  pkg/plugins/policies/meshtimeout/api/v1alpha1/schema.yaml
  pkg/plugins/policies/meshtrace/api/v1alpha1/schema.yaml
  pkg/plugins/policies/meshtrafficpermission/api/v1alpha1/schema.yaml
  tools/policy-gen/crd-extract-openapi.sh
  tools/policy-gen/templates/schema.yaml
Labels: ci/skip-e2e-test

#10466 fix(meshpassthrough): proper escape ipv6
  pkg/plugins/policies/meshpassthrough/plugin/xds/listeners_filter_chain.go
  test/e2e_env/kubernetes/meshpassthrough/meshpassthrough.go
Labels: ci/run-full-matrix

#10453 chore(deps): bump envoy version from 1.29.5 to 1.30.2
  mk/dependencies/deps.lock
  mk/dev.mk
Labels: ci/run-full-matrix

#10467 ci(policy-gen): handle global scoped policies correctly
  docs/generated/openapi.yaml
  mk/generate.mk
  pkg/core/resources/apis/donothingresource/api/v1alpha1/schema.yaml
  pkg/core/resources/apis/donothingresource/api/v1alpha1/zz_generated.resource.go
  pkg/core/resources/apis/hostnamegenerator/api/v1alpha1/rest.yaml
  pkg/core/resources/apis/hostnamegenerator/api/v1alpha1/schema.yaml
  pkg/core/resources/apis/hostnamegenerator/api/v1alpha1/zz_generated.resource.go
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/rest.yaml
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/zz_generated.resource.go
  pkg/core/resources/apis/meshservice/api/v1alpha1/rest.yaml
  pkg/core/resources/apis/meshservice/api/v1alpha1/zz_generated.resource.go
  pkg/plugins/policies/donothingpolicy/api/v1alpha1/schema.yaml
  pkg/plugins/policies/donothingpolicy/api/v1alpha1/zz_generated.resource.go
  pkg/plugins/policies/meshaccesslog/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshaccesslog/api/v1alpha1/zz_generated.resource.go
  pkg/plugins/policies/meshcircuitbreaker/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshcircuitbreaker/api/v1alpha1/zz_generated.resource.go
  pkg/plugins/policies/meshfaultinjection/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshfaultinjection/api/v1alpha1/zz_generated.resource.go
  pkg/plugins/policies/meshhealthcheck/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshhealthcheck/api/v1alpha1/zz_generated.resource.go
  pkg/plugins/policies/meshhttproute/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshhttproute/api/v1alpha1/zz_generated.resource.go
  pkg/plugins/policies/meshloadbalancingstrategy/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshloadbalancingstrategy/api/v1alpha1/zz_generated.resource.go
  pkg/plugins/policies/meshmetric/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshmetric/api/v1alpha1/zz_generated.resource.go
  pkg/plugins/policies/meshpassthrough/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshpassthrough/api/v1alpha1/zz_generated.resource.go
  pkg/plugins/policies/meshproxypatch/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshproxypatch/api/v1alpha1/zz_generated.resource.go
  pkg/plugins/policies/meshratelimit/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshratelimit/api/v1alpha1/zz_generated.resource.go
  pkg/plugins/policies/meshretry/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshretry/api/v1alpha1/zz_generated.resource.go
  pkg/plugins/policies/meshtcproute/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtcproute/api/v1alpha1/zz_generated.resource.go
  pkg/plugins/policies/meshtimeout/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtimeout/api/v1alpha1/zz_generated.resource.go
  pkg/plugins/policies/meshtrace/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtrace/api/v1alpha1/zz_generated.resource.go
  pkg/plugins/policies/meshtrafficpermission/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtrafficpermission/api/v1alpha1/zz_generated.resource.go
  tools/policy-gen/generator/cmd/core_resource.go
  tools/policy-gen/generator/cmd/k8s_resource.go
  tools/policy-gen/generator/cmd/openapi.go
  tools/policy-gen/templates/endpoints.yaml
  tools/policy-gen/templates/schema.yaml
Labels: ci/skip-e2e-test

#10426 fix(kuma-cp): consistently update ZoneIngress available services
  app/kuma-cp/cmd/run.go
  docs/generated/raw/kuma-cp.yaml
  pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
  pkg/config/loader_test.go
  pkg/config/multizone/multicluster.go
  pkg/xds/ingress/dataplane.go
  pkg/xds/ingress/dataplane_test.go
  pkg/xds/sync/ingress_proxy_builder.go
  pkg/xds/sync/proxy_builder_test.go
  pkg/zone/available_services.go
  pkg/zone/available_services_test.go
  pkg/zone/components.go
  pkg/zone/zone_suite_test.go
  test/e2e_env/multizone/connectivity/available_services.go
  test/e2e_env/multizone/multizone_suite_test.go
  test/e2e_env/multizone/sync/sync.go
  test/framework/constants.go
  test/framework/setup.go
  test/framework/universal_app.go
  test/framework/universal_cluster.go
Labels: ci/run-full-matrix, backport

#10475 fix(ZoneIngress): fix no pointer panic for advertised address resolving
  pkg/xds/context/mesh_context_builder.go
Labels: backport

#10499 test(e2e): fix previous version installs
  test/e2e/helm/kuma_helm_upgrade_multizone.go
  test/e2e/helm/kuma_helm_upgrade_standalone.go
  test/e2e_env/universal/compatibility/dp_compatibility.go
  test/e2e_env/universal/universal_suite_test.go
  test/framework/config.go
  test/framework/universal_app.go
  test/framework/versions/suite_test.go
  test/framework/versions/versions.go
  test/framework/versions/versions_test.go
Labels: release-2.6

#10480 fix(kds): send NACK only when resource is invalid and do not retry
  pkg/kds/global/components_test.go
  pkg/kds/util/resource.go
  pkg/kds/v2/client/kds_client.go
  pkg/kds/v2/client/stream.go
  pkg/kds/v2/reconcile/interfaces.go
  pkg/kds/v2/reconcile/reconciler.go
  pkg/kds/v2/reconcile/reconciler_test.go
  pkg/kds/v2/server/components.go
  pkg/kds/v2/server/resource_retry_forcer.go
  pkg/kds/zone/components_test.go
  pkg/test/kds/samples/resources.go
Labels: backport

#10500 chore(dependabot): set dependabot to run on monday
  .github/dependabot.yml
Labels: ci/skip-test, ci/skip-e2e-test

#10542 ci(meshexternalservice): skip ipv6 on meshexternalservice
  test/e2e_env/kubernetes/kubernetes_suite_test.go
  test/e2e_env/universal/universal_suite_test.go
Labels: ci/skip-test

#10538 fix(build): set envoy version conditionally
  mk/build.mk
Labels: ci/skip-test, ci/skip-e2e-test

#10549 test(e2e): ipv6 for mesh service and mesh external service
  test/e2e_env/kubernetes/kubernetes_suite_test.go
  test/e2e_env/multizone/meshservice/status.go
  test/e2e_env/multizone/multizone_suite_test.go
  test/e2e_env/universal/universal_suite_test.go
  test/framework/config.go
  test/framework/envs/multizone/env.go
  test/framework/k8s_cluster.go
  test/framework/universal_cluster.go
Labels: ci/run-full-matrix

#10566 ci(gha): figure out the newest branch
  mk/dependencies/deps.lock
  mk/dev.mk
Labels: ci/skip-test

#10571 test(e2e): mesh service connectivity
  test/e2e_env/multizone/meshservice/connectivity.go
  test/e2e_env/multizone/meshservice/sync.go
  test/e2e_env/multizone/multizone_suite_test.go
Labels: release-2.8

#10544 feat(Mesh*Service): validate name length
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/testdata/name-too-long.input.yaml
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/testdata/name-too-long.output.yaml
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/validator.go
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/validator_test.go
  pkg/core/resources/apis/meshservice/api/v1alpha1/suite_test.go
  pkg/core/resources/apis/meshservice/api/v1alpha1/validator.go
  pkg/core/resources/apis/meshservice/api/v1alpha1/validator_test.go
  pkg/core/resources/model/rest/unmarshaller.go
  pkg/core/validators/common_validators.go
  pkg/plugins/runtime/k8s/controllers/meshservice_controller.go
  pkg/test/resources/validators/validation.go
  pkg/util/k8s/name_converter.go
Labels: release-2.8

#10576 fix(meshpassthrough): rename to passthroughMode and fix behaviour
  app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml
  app/kumactl/cmd/install/testdata/install-crds.all.golden.yaml
  deployments/charts/kuma/crds/kuma.io_meshpassthroughs.yaml
  docs/generated/openapi.yaml
  docs/generated/raw/crds/kuma.io_meshpassthroughs.yaml
  pkg/plugins/policies/meshpassthrough/api/v1alpha1/meshpassthrough.go
  pkg/plugins/policies/meshpassthrough/api/v1alpha1/schema.yaml
  pkg/plugins/policies/meshpassthrough/api/v1alpha1/zz_generated.deepcopy.go
  pkg/plugins/policies/meshpassthrough/k8s/crd/kuma.io_meshpassthroughs.yaml
  pkg/plugins/policies/meshpassthrough/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshpassthrough/plugin/v1alpha1/plugin_test.go
  pkg/plugins/policies/meshpassthrough/plugin/v1alpha1/testdata/enabled_on_policy_and_mesh.clusters.golden.yaml
  pkg/plugins/policies/meshpassthrough/plugin/v1alpha1/testdata/enabled_on_policy_and_mesh.listeners.golden.yaml
  test/e2e_env/kubernetes/meshpassthrough/meshpassthrough.go
Labels: release-2.8

#10548 feat(hostnamegenerator): prevent template being empty
  pkg/core/resources/apis/hostnamegenerator/api/v1alpha1/validate.go
  pkg/core/resources/apis/hostnamegenerator/api/v1alpha1/validate_test.go
Labels: ci/skip-e2e-test, release-2.8

#10594 feat(meshexternalservice): relax validation of port on universal
  pkg/core/resources/apis/mesh/dataplane_validator.go
  pkg/core/resources/apis/mesh/dataplane_validator_test.go
Labels: ci/skip-e2e-test

#10630 docs(MADR): MeshService subsets
  docs/madr/decisions/055-meshservice-subset.md
Labels: ci/skip-test

#10646 chore(deps): upgrade envoy to 1.30.3
  mk/dependencies/deps.lock
  mk/dev.mk
Labels: master

#10645 chore(deps): upgrade envoy to 1.30.3
  mk/dependencies/deps.lock
  mk/dev.mk
Labels: release-2.8

#10641 chore(deps): upgrade envoy version to 1.29.6
  tools/releases/version.sh
Labels: release-2.7

#10642 ci(gha): enable self hosted runners for arm64 e2e tasks
  .github/workflows/_e2e.yaml
Labels: ci/skip-test

#10651 fix(cni): set proper namespace for the taint controller
  app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/fix4935.golden.yaml
  deployments/charts/kuma/templates/_helpers.tpl
  test/e2e/cni/taint_controller_race.go
  test/framework/interface.go
  test/framework/k8s_cluster.go
Labels: ci/run-full-matrix, backport
