Repository kumahq/kuma, pull requests merged in 2024-01, with the labels that each got.

#8723 ci(github): allow arm/circleci failures to fail GH Actions CI
  .github/workflows/e2e.yaml
Labels: ci/skip-test

#8648 docs(readme): update slack community link
  CONTRIBUTING.md
Labels: ci/skip-test

#8736 test(bootstrap): move corefile template e2e test to test/e2e from test/e2e_env/kubernetes
  test/e2e/bootstrap/corefile_template.go
  test/e2e/bootstrap/e2e_suite_test.go
  test/e2e_env/kubernetes/kubernetes_suite_test.go
Labels: ci/run-full-matrix

#8761 test(e2e): fix cluster name in the resource
  test/e2e/externalservices/localityawarelb_multizone/locality_multizone_hybrid.go
  test/e2e/helm/kuma_helm_deploy_global_zone.go
Labels: ci/run-full-matrix

#8763 test(e2e): fix test failure for syncing when on legacyKDS mode
  test/e2e_env/multizone/sync/sync.go
Labels: ci/run-full-matrix

#8776 ci(github): use merge commit sha for pull requests to trigger CircleCI builds
  .github/workflows/e2e.yaml
Labels: ci/skip-test

#8787 ci(github): run security actions on schedule and fix issues
  .github/workflows/build-test-distribute.yaml
  .github/workflows/codeql.yaml
  .github/workflows/golangci-lint.yml
  .github/workflows/scorecard.yml
  .github/workflows/update-insecure-dependencies.yaml
Labels: ci/skip-test

#8792 ci(github): fix branch name for reference PR branches to trigger CircleCI builds
  .github/workflows/e2e.yaml
Labels: ci/skip-test

#8799 test(e2e): check DPP name without zone prefix
  test/e2e/helm/kuma_helm_deploy_global_universal_mode_and_zone.go
Labels: ci/run-full-matrix

#8805 docs(readme): update OSSF Badges
  README.md
Labels: ci/skip-test

#8808 test(e2e): fix ipv6 and helm failure
  .github/workflows/e2e.yaml
  test/e2e/helm/kuma_helm_deploy_global_zone.go
Labels: ci/run-full-matrix

#8814 fix(policy): fix meshmetric e2e flake
  app/kuma-dp/pkg/dataplane/meshmetrics/component.go
  test/e2e_env/kubernetes/meshmetric/meshmetric.go
Labels: ci/run-full-matrix

#8837 ci(github): fix bad reference in auto-merge
  .github/workflows/auto-merge.yaml
Labels: ci/skip-test

#8840 ci(github): add github app to lifecycle job
  .github/workflows/lifecycle.yml
Labels: ci/skip-test

#8843 ci(github): add periodic sbom and license check
  .clomonitor.yaml
  .github/workflows/bom.yaml
  README.md
Labels: ci/skip-test

#8872 fix(kds): race condition on fill metadata
  pkg/kds/v2/reconcile/reconciler.go
Labels: backport

#8528 docs(MADR): targetRef policy as a default engine
  docs/madr/decisions/034-default-target-ref-policy.md
Labels: ci/skip-test, ci/skip-e2e-test

#8829 docs(MADR): targeting all gateways in policy
  docs/madr/decisions/037-configure-all-gateways.md
Labels: ci/skip-test, ci/skip-e2e-test

#8879 ci(install-dev-tools.sh): add debug logs
  tools/dev/install-dev-tools.sh
Labels: ci/skip-test

#8880 ci(install-dev-tools.sh): add more debug logs
  tools/dev/install-dev-tools.sh
Labels: ci/skip-test

#8881 ci(go-deps): include `mk/dependencies/go-deps.versions` file
  .gitignore
  mk/dependencies/go-deps.versions
Labels: ci/skip-test

#8940 fix(kuma-cp): assign `extensions` in `ZoneInsightSink` constructor
  pkg/kds/status/status_sink.go
Labels: backport

#8946 ci(github-actions/backport): add missing PR: write permissions
  .github/workflows/backport.yaml
Labels: ci/skip-test

#8894 feat(metrics): add create conflicts to the metric
  pkg/metrics/store/store.go
  pkg/metrics/store/store_test.go
Labels: ci/skip-e2e-test

#8947 ci(github-actions/backport): move permissions section to job
  .github/workflows/backport.yaml
Labels: ci/skip-test

#8949 ci(github-actions/backport): move contents: read permission to job
  .github/workflows/backport.yaml
Labels: ci/skip-test

#8944 chore(deps): update go from 1.21.5 to 1.21.6
  .circleci/config.yml
  go.mod
Labels: backport

#9001 ci(github-actions/backport): add back "permissions" top section
  .github/workflows/backport.yaml
Labels: ci/skip-test

#9069 chore(e2e): fix flake
  test/e2e_env/multizone/meshtimeout/meshtimeout.go
Labels: ci/run-full-matrix

#9083 ci(distribute/helm-charts): add missing GH_USER/GH_EMAIL env vars
  .github/workflows/build-test-distribute.yaml
Labels: ci/skip-test

#9084 test(e2e): fix dp auth flake
  test/e2e_env/universal/auth/dp_auth.go
Labels: backport

#9085 ci(distribute/helm-charts): add missing GH_USER/GH_EMAIL env vars
  .github/workflows/build-test-distribute.yaml
Labels: ci/skip-test

#9093 test(e2e): enable admin operations from Global test
  test/e2e/helm/kuma_helm_deploy_global_zone.go
Labels: ci/run-full-matrix
