Repository kumahq/kuma, pull requests merged in 2024-10, with the labels that each got.

#11601 revert(kuma-cp): do not use additional addresses
  pkg/xds/envoy/listeners/listener_configurers.go
  pkg/xds/envoy/listeners/v3/additional_address_configuer.go
  pkg/xds/envoy/listeners/v3/additional_address_configurer_test.go
  pkg/xds/generator/outbound_proxy_generator.go
  pkg/xds/generator/testdata/outbound-proxy/08.envoy.golden.yaml
  pkg/xds/generator/testdata/outbound-proxy/10.envoy.golden.yaml
Labels: backport

#11631 chore(deps): manually bump go to 1.23.2
  go.mod
Labels: dependencies

#11630 chore(deps): bump golang from 1.22.7 to 1.22.8
  go.mod
Labels: dependencies, release-2.8

#11629 chore(deps): bump golang from 1.22.7 to 1.22.8
  go.mod
Labels: dependencies, release-2.7

#11628 chore(deps): bump golang from 1.22.7 to 1.22.8
  go.mod
Labels: dependencies, release-2.6

#11646 test(e2e): print debug info on namespace delete
  test/e2e/externalservices/externalservices_kubernetes_without_egress.go
  test/framework/k8s_cluster.go
Labels: ci/skip-test

#11627 chore(deps): bump golang from 1.22.7 to 1.22.8
  .circleci/config.yml
  go.mod
Labels: dependencies, release-2.5

#11625 ci(gha): verify CI stability action
  .github/workflows/ci-stability.yaml
Labels: ci/skip-test

#11649 test(e2e): simplify localityaware tests
  test/e2e/externalservices/e2e_suite_test.go
  test/e2e/externalservices/locality_multizone_hybrid.go
  test/e2e/externalservices/localityawarelb_multizone/e2e_suite_test.go
  test/e2e/helm/e2e_suite_test.go
  test/framework/k8s_cluster.go
Labels: ci/run-full-matrix

#11654 ci(github): move checklist to a PR
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/check.yaml
Labels: ci/skip-test

#11655 test(e2e): disable metrics server in k3d
  mk/k3d.mk
Labels: backport

#11666 ci(github): fix checklist comment
  .github/workflows/check.yaml
Labels: ci/skip-test

#11673 ci(gha): fix cron for ci stability
  .github/workflows/ci-stability.yaml
Labels: ci/skip-test

#11689 test(e2e): move isolated e2e to arm
  .github/workflows/_test.yaml
Labels: ci/skip-test

#11691 chore(gha): cancel in progress on prs to not clog up CI
  .github/workflows/build-test-distribute.yaml
Labels: ci/skip-test

#11684 fix(transparent-proxy): conntrack zone splitting in docker containers with custom network
  app/kumactl/cmd/install/install_transparent_proxy.go
  app/kumactl/cmd/install/install_transparent_proxy_test.go
  pkg/transparentproxy/config/config.go
  pkg/transparentproxy/consts/consts.go
  pkg/transparentproxy/iptables/builder/builder_table_nat.go
  pkg/transparentproxy/iptables/builder/builder_table_raw.go
  pkg/transparentproxy/iptables/parameters/destination.go
  pkg/transparentproxy/iptables/parameters/match.go
  pkg/transparentproxy/iptables/parameters/source.go
  pkg/transparentproxy/iptables/parameters/source_destination.go
  pkg/transparentproxy/iptables/parameters/source_destination_test.go
  pkg/transparentproxy/iptables/parameters/source_test.go
  test/blackbox_network_tests/dns_test.go
  test/blackbox_network_tests/outbound_redirect_test.go
  test/e2e_env/universal/universal_suite_test.go
  test/framework/universal_app.go
  test/framework/universal_cluster.go
Labels: ci/run-full-matrix

#11703 fix(dev/tools): fail make dev/tools step if installing go deps returned error
  mk/dependencies/deps.lock
  mk/dependencies/go-deps.sh
Labels: ci/skip-test, backport

#11705 ci(gha): fix retriving PR data for ci stability
  .github/workflows/ci-stability.yaml
Labels: ci/skip-test

#11711 test(e2e): rebalance arm and amd runners
  .github/workflows/_test.yaml
Labels: ci/skip-test

#11717 chore(heartbeat): properly log new leader address
  pkg/intercp/catalog/heartbeat_component.go
Labels: ci/skip-test

#11734 test(e2e): ci stability app token
  .github/workflows/ci-stability.yaml
Labels: ci/skip-test

#11731 chore(docs): update dev onboarding
  DEVELOPER.md
  docs/guides/e2e-test-tips.md
Labels: ci/skip-test, ci/skip-e2e-test

#11737 fix(e2e): port forward to service instead of pod of kuma-cp to improve test stability
  test/framework/k8s_controlplane.go
Labels: ci/run-full-matrix, backport

#11756 ci(.github): don't fail merge release to master if versions.yml isn't updated
  .github/workflows/merge-release-to-master.yaml
Labels: ci/skip-test, ci/skip-e2e-test

#11764 fix(e2e): loosen up assertion on traffic route test
  test/e2e_env/universal/trafficroute/traffic_route.go
Labels: backport, release-2.9

#11783 ci(github): downgrade github action runner from ubuntu-latest to ubuntu-22.04 for images building
  .github/workflows/_build_publish.yaml
Labels: release-2.9

#11760 docs(debug): add debugging on k8s and universal docs
  DEVELOPER.md
Labels: ci/skip-test

#11766 fix(api): when resource has origin zone assume is local
  pkg/core/resources/model/resource.go
  pkg/plugins/policies/core/matchers/dataplane.go
  pkg/plugins/policies/core/matchers/testdata/matchedpolicies/meshgateways/policies_from_different_zones_no_zone_label.dataplane.yaml
  pkg/plugins/policies/core/matchers/testdata/matchedpolicies/meshgateways/policies_from_different_zones_no_zone_label.golden.yaml
  pkg/plugins/policies/core/matchers/testdata/matchedpolicies/meshgateways/policies_from_different_zones_no_zone_label.policies.yaml
Labels: release-2.9

#11802 ci(gha): adjust cron in ci stability
  .github/workflows/ci-stability.yaml
Labels: ci/skip-test

#5945 chore(kuma-init): use distroless image
  tools/releases/dockerfiles/kuma-init.Dockerfile
  tools/releases/dockerfiles/kuma-init.Dockerfile.dockerignore
  tools/releases/templates/group
  tools/releases/templates/passwd
Labels: ci/run-full-matrix

#11826 ci(.github): use latest version of ubuntu runner image to build kuma-init image
  .github/workflows/_build_publish.yaml
Labels: ci/skip-test, ci/run-build

#11831 chore(deps): upgrade envoy to v1.32.0
  mk/dependencies/deps.lock
  mk/dev.mk
Labels: ci/run-full-matrix

#11832 test(e2e): use MeshService mode and generated hostname
  test/e2e_env/universal/meshhealthcheck/policy.go
Labels: backport

#11851 ci(k8s): download calico manifests as needed
  .gitignore
  mk/dependencies/deps.lock
  mk/dependencies/k3d.sh
  mk/k3d.mk
  test/k3d/calico.yaml.kubelint-excluded
Labels: ci/run-full-matrix, backport

#11862 test(e2e): disable amd64 self-hosted runners
  .github/workflows/build-test-distribute.yaml
Labels: ci/run-full-matrix

#11866 chore(kuma-cp): expose keep alive const
  pkg/dp-server/server/server.go
Labels: ci/skip-test

#11883 ci(gha): adjust timeout for check
  .github/workflows/build-test-distribute.yaml
Labels: ci/skip-test

#11882 ci(gha): adjust retention days
  .github/workflows/_build_publish.yaml
  .github/workflows/_e2e.yaml
  .github/workflows/helm-release.yaml
Labels: ci/skip-test

#11881 docs(MADR): update 061-meshtls.md
  docs/madr/decisions/061-meshtls.md
Labels: ci/skip-test

#11894 test(e2e): improve reachable services expectation to allow DNS timeouts
  test/e2e_env/kubernetes/reachableservices/reachableservices.go
Labels: backport

#11893 test(e2e): speed up reachable services
  go.mod
  test/e2e/reachableservices/auto_reachable_mesh_services_k8s.go
  test/e2e/reachableservices/auto_reachable_services_k8s.go
  test/e2e/reachableservices/cluster.go
  test/e2e/reachableservices/e2e_suite_test.go
  test/framework/setup.go
Labels: ci/run-full-matrix

#11902 test(e2e): remove virtual outbound legacy test
  test/e2e/virtualoutbound/e2e_suite_test.go
  test/e2e/virtualoutbound/virtualoutbound_k8s.go
Labels: ci/skip-test

#11911 test(e2e): protect deployment with mutex
  test/framework/k8s_cluster.go
Labels: ci/skip-test

#11922 fix(cni): delegated gateway was not correctly injected
  pkg/plugins/runtime/k8s/webhooks/injector/injector.go
  pkg/plugins/runtime/k8s/webhooks/injector/injector_test.go
  pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.41.golden.yaml
  pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.41.input.yaml
  pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.sidecar-feature.41.golden.yaml
  test/framework/envs/multizone/env.go
Labels: ci/run-full-matrix, backport

#11937 test(e2e): reenable amd64 self-hosted runners
  .github/workflows/_e2e.yaml
  .github/workflows/build-test-distribute.yaml
Labels: ci/run-full-matrix

#11960 chore(deps): upgrade envoy version from 1.28.7 to 1.29.10
  tools/releases/version.sh
Labels: release-2.6

#11959 chore(deps): upgrade envoy version from 1.28.7 to 1.29.10
  tools/releases/version.sh
Labels: release-2.5

#11956 chore(deps): upgrade envoy version to 1.29.10
  mk/dependencies/deps.lock
  mk/dev.mk
Labels: release-2.7

#11957 chore(deps): upgrade envoy version to 1.30.7
  mk/dependencies/deps.lock
  mk/dev.mk
Labels: release-2.8

#11958 chore(deps): upgrade envoy version to 1.30.7
  mk/dependencies/deps.lock
  mk/dev.mk
Labels: release-2.9

#11962 chore(deps): upgrade envoy version to 1.32.1
  mk/dependencies/deps.lock
  mk/dev.mk
Labels: master
