Repository kumahq/kuma, pull requests merged in 2024-04, with the labels that each got.

#9776 fix(transparent-proxy): make iptables mode detection more defensive
  pkg/transparentproxy/config/config.go
  pkg/transparentproxy/iptables/builder/builder.go
  pkg/transparentproxy/iptables/builder/builder_restore.go
  pkg/transparentproxy/iptables/builder/builder_table_raw.go
  pkg/transparentproxy/iptables/setup.go
Labels: ci/force-publish, backport

#9789 ci(github): fix provenance to use version for action
  .github/workflows/_provenance.yaml
Labels: ci/skip-test

#9791 ci(github): correct DOCKER_USERNAME in provenance
  .github/workflows/_provenance.yaml
Labels: ci/skip-test

#9571 docs(MADR): transition to new policies
  docs/madr/decisions/040-transition-to-new-policies.md
Labels: ci/skip-test

#9795 ci(update-vulnerable-dependencies): pass KUMA_DIR to the script
  tools/ci/update-vulnerable-dependencies/update-vulnerable-dependencies.sh
Labels: ci/skip-test, backport

#9732 feat(gatewayapi): use MeshHTTPRoutes instead of MeshGatewayRoutes internally
  pkg/plugins/runtime/k8s/controllers/gatewayapi/attachment/attachment.go
  pkg/plugins/runtime/k8s/controllers/gatewayapi/attachment/attachment_test.go
  pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_controller.go
  pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_conversion.go
  pkg/plugins/runtime/k8s/controllers/gatewayapi/mesh_http_route_conversion.go
  pkg/plugins/runtime/k8s/plugin.go
  pkg/plugins/runtime/k8s/plugin_gateway.go
  pkg/plugins/runtime/k8s/webhooks/gatewayapi_multizone_validator.go
  pkg/plugins/runtime/k8s/webhooks/gatewayapi_multizone_validator_test.go
Labels: area/gateway, ci/run-full-matrix

#9801 ci(check): fail CI wih `ci/force-publish` label on PRs from forks
  .github/workflows/build-test-distribute.yaml
Labels: ci/skip-test, backport

#9808 ci(build-test-distribute): fix check of 'ci/force-push' label in PRs
  .github/workflows/build-test-distribute.yaml
Labels: ci/skip-test, backport

#9807 ci(github): add registry to provenance
  .github/workflows/_build_publish.yaml
  .github/workflows/_provenance.yaml
  .github/workflows/build-test-distribute.yaml
Labels: ci/skip-test

#9829 docs(MADR): fix some typos
  docs/madr/decisions/011-mesh-traffic-route.md
  docs/madr/decisions/014-multizone-envoy-admin.md
  docs/madr/decisions/021-kds-redesign.md
  docs/madr/decisions/027-meshgateway-targetref.md
Labels: ci/skip-test

#9835 docs(UPGRADE.md): remove or fix links
  UPGRADE.md
Labels: ci/skip-test

#9842 chore(deps): update Envoy to v1.26.8
  tools/releases/version.sh
Labels: release-2.3

#9841 chore(deps): update Envoy to v1.26.8
  tools/releases/version.sh
Labels: release-2.2

#9843 chore(deps): update Envoy to v1.28.2
  tools/releases/version.sh
Labels: release-2.6

#9844 chore(deps): update Envoy to v1.27.4
  tools/releases/version.sh
Labels: release-2.4

#9845 chore(deps): update Envoy to v1.28.2
  tools/releases/version.sh
Labels: release-2.5

#9853 chore(deps): upgrade Envoy from 1.29.2 to 1.29.3
  tools/releases/version.sh
Labels: ci/run-full-matrix

#9736 fix(kds): fix retry on NACK and add backoff
  pkg/events/interfaces.go
  pkg/kds/v2/reconcile/interfaces.go
  pkg/kds/v2/reconcile/reconcile_suite_test.go
  pkg/kds/v2/reconcile/reconciler.go
  pkg/kds/v2/reconcile/reconciler_test.go
  pkg/kds/v2/server/components.go
  pkg/kds/v2/server/event_based_watchdog.go
  pkg/kds/v2/server/event_based_watchdog_test.go
  pkg/kds/v2/server/resource_retry_forcer.go
  test/framework/envs/multizone/env.go
  test/framework/k8s_cluster.go
Labels: ci/run-full-matrix

#9862 docs(MADR): `warnings` field in the Resource API responses
  docs/madr/decisions/041-resource-api-warnings.md
Labels: ci/skip-test

#9879 ci(build): fix jobs depending on distributions being skipped because …
  .github/workflows/build-test-distribute.yaml
Labels: ci/skip-test

#9888 docs(upgrade): document cluster merging
  UPGRADE.md
Labels: ci/skip-test

#9890 docs(UPGRADE.md): add section about using MeshHTTPRoute in GAPI
  UPGRADE.md
Labels: ci/skip-test

#9904 feat(k8s): add drain when using native sidecars
  app/kuma-cp/cmd/run.go
  app/kuma-dp/cmd/run.go
  app/kuma-dp/cmd/run_test.go
  app/kuma-dp/pkg/dataplane/envoy/envoy.go
  pkg/cmd/util.go
  pkg/core/alias.go
  pkg/plugins/runtime/k8s/webhooks/injector/injector.go
  pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.sidecar-feature.01.golden.yaml
  pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.sidecar-feature.02.golden.yaml
  pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.sidecar-feature.03.golden.yaml
  pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.sidecar-feature.04.golden.yaml
  pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.sidecar-feature.05.golden.yaml
  pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.sidecar-feature.06.golden.yaml
  pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.sidecar-feature.07.golden.yaml
  pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.sidecar-feature.08.golden.yaml
  pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.sidecar-feature.09.golden.yaml
  pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.sidecar-feature.10.golden.yaml
  pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.sidecar-feature.11.golden.yaml
  pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.sidecar-feature.12.golden.yaml
  pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.sidecar-feature.13.golden.yaml
  pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.sidecar-feature.14.golden.yaml
  pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.sidecar-feature.15.golden.yaml
  pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.sidecar-feature.16.golden.yaml
  pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.sidecar-feature.17.golden.yaml
  pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.sidecar-feature.18.golden.yaml
  pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.sidecar-feature.19.golden.yaml
  pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.sidecar-feature.20.golden.yaml
  pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.sidecar-feature.21.golden.yaml
  pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.sidecar-feature.22.golden.yaml
  pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.sidecar-feature.23.golden.yaml
  pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.sidecar-feature.24.golden.yaml
  pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.sidecar-feature.25.golden.yaml
  pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.sidecar-feature.26.golden.yaml
  pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.sidecar-feature.27.golden.yaml
  pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.sidecar-feature.28.golden.yaml
  pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.sidecar-feature.29.golden.yaml
  pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.sidecar-feature.30.golden.yaml
  pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.sidecar-feature.31.golden.yaml
  pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.sidecar-feature.32.golden.yaml
  pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.sidecar-feature.33.golden.yaml
  pkg/plugins/runtime/k8s/webhooks/injector/testdata/inject.sidecar-feature.34.golden.yaml
Labels: ci/run-full-matrix

#9927 fix(GAPI): add missing origin label for MeshGateway converted from Gateway
  app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present-not-enabled.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.registry.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.tproxy-ebpf-experimental-enabled.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.with-egress.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.with-helm-values.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/doNotChangeTlsChecksum.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/empty.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/fix4485.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/fix4496.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/fix4935.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/fix5978.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/fix7724.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/fix7824.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/minReadySeconds.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/securityContext.golden.yaml
  deployments/charts/kuma/templates/cp-webhooks-and-secrets.yaml
Labels: area/gateway

#9924 chore(demo): remove tags from meshgatewayinstance
  app/kumactl/cmd/install/testdata/install-demo.defaults.golden.yaml
  app/kumactl/cmd/install/testdata/install-demo.overrides.golden.yaml
  app/kumactl/data/install/k8s/demo/gateway.yaml
Labels: ci/skip-e2e-test

#9932 ci(github): update osv scanner
  .github/workflows/update-insecure-dependencies.yaml
Labels: ci/skip-test

#9933 fix(kuma-cni): fix the subject namespace reference in Helm Chart
  deployments/charts/kuma/templates/cni-rbac.yaml
Labels: ci/skip-test

#9939 feat(GatewayAPI): promote our Gateway API implementation to GA
  UPGRADE.md
  app/kumactl/cmd/completion/testdata/bash.golden
  app/kumactl/cmd/install/context/install_control_plane_context.go
  app/kumactl/cmd/install/context/install_crds_context.go
  app/kumactl/cmd/install/install_control_plane.go
  app/kumactl/cmd/install/install_control_plane_test.go
  app/kumactl/cmd/install/install_crds.go
  app/kumactl/cmd/install/install_crds_test.go
  app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.dump-values.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.registry.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.tproxy-ebpf-experimental-enabled.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.with-egress.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.with-helm-values.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/doNotChangeTlsChecksum.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/empty.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/fix4485.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/fix4496.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/fix4935.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/fix5978.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/fix7724.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/fix7824.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/minReadySeconds.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/securityContext.golden.yaml
  app/kumactl/cmd/install/testdata/install-crds.all.golden.yaml
  deployments/charts/kuma/README.md
  deployments/charts/kuma/templates/NOTES.txt
  deployments/charts/kuma/templates/_helpers.tpl
  deployments/charts/kuma/templates/cp-rbac.yaml
  deployments/charts/kuma/templates/gateway-class.yaml
  deployments/charts/kuma/templates/pre-upgrade-install-crds-job.yaml
  deployments/charts/kuma/values.yaml
  docs/generated/raw/helm-values.yaml
  docs/generated/raw/kuma-cp.yaml
  pkg/config/app/kuma-cp/config.go
  pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
  pkg/config/loader_test.go
  pkg/plugins/runtime/gateway/plugin.go
  pkg/plugins/runtime/k8s/plugin_gateway.go
  test/e2e_env/gatewayapi/conformance_test.go
  test/framework/envs/kubernetes/env.go
Labels: area/gateway

#9940 ci(update): make it possible to pass additional options to osv-scanner
  .github/workflows/update-insecure-dependencies.yaml
  tools/ci/update-vulnerable-dependencies/update-vulnerable-dependencies.sh
Labels: ci/skip-test

#9961 test(e2e): enable skipped delegated gateway tests
  test/e2e_env/kubernetes/gateway/delegated.go
  test/e2e_env/kubernetes/gateway/delegated/meshproxypatch.go
  test/e2e_env/kubernetes/gateway/delegated/meshtcproute.go
Labels: ci/run-full-matrix

#9965 chore(GAPI): move from deprecated behavior
  pkg/plugins/runtime/k8s/controllers/gatewayapi/common/common.go
  pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_controller.go
  pkg/plugins/runtime/k8s/controllers/gatewayapi/gateway_conversion.go
Labels: area/gateway

#9969 docs(MADR): adjust MADR numbers to avoid duplicates
  docs/madr/decisions/042-locality-aware-load-balancing.md
  docs/madr/decisions/043-zone-to-global-policy-sync.md
  docs/madr/decisions/044-meshhttproute-meshgateway.md
  docs/madr/decisions/045-route-transition.md
Labels: ci/skip-test

#10020 chore(deps): upgrade Envoy to version 1.28.3
  tools/releases/version.sh
Labels: release-2.5

#10033 chore(deps): upgrade Envoy to version 1.29.4
  tools/releases/version.sh
Labels: ci/run-full-matrix, release-2.7

#10032 docs(MADR): fix madr docs hyperlink mismatch problems
  docs/madr/README.md
Labels: ci/skip-test

#10019 chore(deps): upgrade Envoy to version 1.28.3
  tools/releases/version.sh
Labels: release-2.6

#10045 fix(transparent-proxy): stop logging all to stderr when installing tproxy
  pkg/transparentproxy/iptables/builder/builder.go
  pkg/transparentproxy/iptables/builder/builder_restore.go
Labels: backport

#10058 refactor(transparent-proxy): simplify tproxy configuration
  app/kumactl/cmd/install/install_transparent_proxy.go
  app/kumactl/cmd/uninstall/uninstall_transparent_proxy.go
  pkg/transparentproxy/config/config.go
  pkg/transparentproxy/setup.go
  pkg/transparentproxy/transparentproxy.go
  pkg/transparentproxy/transparentproxy_suite_test.go
  pkg/transparentproxy/transparentproxy_test.go
  pkg/transparentproxy/transparentproxy_v2.go
Labels: area/kumactl, area/installation

#10067 ci(github): bump ci-tools to v0.11.0
  .github/workflows/release.yaml
  mk/docs.mk
Labels: ci/skip-test

#9722 docs(MADR): add Kubernetes UX for `MeshService`
  docs/madr/decisions/041-meshservice-kubernetes-ux.md
Labels: ci/skip-test

#10079 fix(gatewayapi): validate presence of all required Gateway API resources
  pkg/plugins/runtime/k8s/plugin_gateway.go
Labels: area/gateway, backport

#10085 fix(jobs): jobs termination after CP restart
  pkg/plugins/runtime/k8s/controllers/pod_status_controller.go
Labels: backport

#10107 ci(gha): merge release to master
  .github/workflows/merge-release-to-master.yaml
  mk/dependencies/deps.lock
  mk/dev.mk
Labels: ci/skip-test

#10110 chore(docs): fix typo in README
  README.md
Labels: ci/skip-test

#10114 chore(makefile): fix merge-release target and action
  .github/workflows/merge-release-to-master.yaml
  mk/dependencies/deps.lock
  mk/dev.mk
Labels: ci/skip-test

#10140 chore(mk): print latest release branch target
  mk/dependencies/deps.lock
  mk/dev.mk
Labels: ci/skip-test

#10142 chore(gha): improve merge release to master job
  .github/workflows/merge-release-to-master.yaml
Labels: ci/skip-test

#10144 chore(gha): enable trigger for merge release to master
  .github/workflows/merge-release-to-master.yaml
Labels: ci/skip-test

#10145 chore(build): provide CNI only for linux
  app/cni/pkg/cni/annotations_linux.go
  app/cni/pkg/cni/annotations_linux_test.go
  app/cni/pkg/cni/injector_darwin.go
  app/cni/pkg/cni/injector_windows.go
  app/cni/pkg/cni/kubernetes_linux.go
  app/cni/pkg/cni/main_darwin.go
  app/cni/pkg/cni/main_linux.go
  app/cni/pkg/cni/main_linux_test.go
  app/cni/pkg/cni/main_windows.go
Labels: ci/run-full-matrix
