Repository kumahq/kuma, pull requests merged in 2024-08, with the labels that each got.

#11050 fix(transparent-proxy): fix pod delay when CNI on GKE with OS Login
  app/cni/pkg/cni/injector_linux.go
  pkg/transparentproxy/config/config.go
  pkg/transparentproxy/config/config_executables.go
  pkg/transparentproxy/config/config_executables_linux.go
  pkg/transparentproxy/config/config_executables_unspecified.go
  pkg/transparentproxy/iptables/consts/consts.go
Labels: ci/run-full-matrix, ci/force-publish

#10921 docs(MADR): MeshExternalService traffic through egress/sidecar and configuration placement
  docs/madr/decisions/056-meshexternalservice-and-zoneegress.md
Labels: ci/skip-test

#11062 fix(hostnamegenerator): multizone syncing
  pkg/defaults/hostname_generator.go
  pkg/defaults/hostname_generator_test.go
  pkg/kds/context/context.go
  pkg/kds/context/context_test.go
  pkg/kds/features.go
  pkg/kds/v2/client/stream.go
  test/e2e_env/kubernetes/meshexternalservice/meshexternalservice.go
  test/e2e_env/multizone/defaults/defaults.go
  test/e2e_env/multizone/meshmultizoneservice/connectivity.go
  test/e2e_env/multizone/meshservice/connectivity.go
  test/e2e_env/multizone/meshservice/sync.go
  test/e2e_env/universal/meshexternalservice/meshexternalservice.go
  test/e2e_env/universal/meshservice/meshservice.go
  test/framework/envs/multizone/env.go
Labels: ci/run-full-matrix

#11081 test(debug): add more logs
  test/framework/universal_cluster.go
Labels: ci/skip-test

#11109 chore(deps): upgrade envoy to 1.28.5
  tools/releases/version.sh
Labels: release-2.4

#11113 fix(transparent-proxy): avoid mounting xtables.lock for newer versions of legacy iptables
  pkg/transparentproxy/config/config_executables.go
  pkg/transparentproxy/config/config_executables_linux.go
  pkg/transparentproxy/config/config_executables_unspecified.go
  pkg/transparentproxy/iptables/consts/consts.go
Labels: ci/run-full-matrix, ci/force-publish

#11131 fix(kuma-dp): fix build failures on Windows because of TCP socket options on SO_LINGER
  app/kuma-dp/pkg/dataplane/probes/component.go
  app/kuma-dp/pkg/dataplane/probes/probe_dialer_others.go
  app/kuma-dp/pkg/dataplane/probes/probe_dialer_windows.go
Labels: ci/skip-e2e-test

#11144 fix(kuma-dp): fix flaky tests on application probe proxy due to readiness of mock apps
  app/kuma-dp/pkg/dataplane/probes/probe_suite_test.go
  app/kuma-dp/pkg/dataplane/probes/probes_test.go
Labels: ci/skip-e2e-test

#11114 test(e2e): cleanup in test and increase time
  test/e2e/federation/federation_kubernetes.go
  test/e2e/reachableservices/auto_reachable_mesh_services_k8s.go
  test/e2e/reachableservices/auto_reachable_services_k8s.go
Labels: ci/run-full-matrix

#11152 test(e2e): added resource name suffix to avoid conflicts
  test/e2e_env/kubernetes/gateway/delegated/meshaccesslog.go
  test/e2e_env/kubernetes/gateway/delegated/meshhealthcheck.go
  test/e2e_env/kubernetes/gateway/delegated/meshhttproute.go
  test/e2e_env/kubernetes/gateway/delegated/meshtcproute.go
Labels: release-2.7

#11153 test(e2e): added resource name suffix to avoid conflicts
  test/e2e_env/kubernetes/gateway/delegated/meshaccesslog.go
  test/e2e_env/kubernetes/gateway/delegated/meshhealthcheck.go
  test/e2e_env/kubernetes/gateway/delegated/meshhttproute.go
Labels: release-2.8

#11164 test(e2e): rename ES resource name
  test/e2e_env/kubernetes/gateway/delegated/meshhttproute.go
Labels: backport

#11165 feat(transparent-proxy): check for existing iptables rules when picking executables
  pkg/transparentproxy/config/config_executables.go
  pkg/transparentproxy/config/config_executables_functionality.go
Labels: ci/run-full-matrix

#11181 ci(deps): fix update-vulnerable-dependencies.sh additional opts passing
  tools/ci/update-vulnerable-dependencies/update-vulnerable-dependencies.sh
Labels: ci/skip-test, backport

#11188 ci(deps): improve handling OSV_SCANNER_ADDITIONAL_OPTS env var
  tools/ci/update-vulnerable-dependencies/update-vulnerable-dependencies.sh
Labels: ci/skip-test, backport

#11166 feat(transparent-proxy): enforce root privileges for (un)install commands
  app/kumactl/cmd/install/install_transparent_proxy.go
  app/kumactl/cmd/install/install_transparent_proxy_test.go
  app/kumactl/cmd/uninstall/uninstall_transparent_proxy.go
  pkg/transparentproxy/config/config_executables.go
Labels: ci/run-full-matrix

#11202 docs(meshtls): design of MeshTLS
  docs/madr/decisions/061-meshtls.md
Labels: ci/skip-test

#11207 fix(transparent-proxy): prioritize IPv4 executables initialization
  pkg/transparentproxy/config/config.go
  pkg/transparentproxy/config/config_executables.go
  test/transparentproxy/testdata/debian-10-with-multiple-flags.ip6tables-legacy.golden
  test/transparentproxy/testdata/debian-10.ip6tables-legacy.golden
  test/transparentproxy/testdata/debian-11-with-multiple-flags.ip6tables-legacy.golden
  test/transparentproxy/testdata/debian-11.ip6tables-legacy.golden
  test/transparentproxy/testdata/debian-12-with-multiple-flags.ip6tables-legacy.golden
  test/transparentproxy/testdata/debian-12.ip6tables-legacy.golden
  test/transparentproxy/testdata/ubuntu-20-04-with-multiple-flags.ip6tables-legacy.golden
  test/transparentproxy/testdata/ubuntu-20-04-with-multiple-flags.ip6tables.golden
  test/transparentproxy/testdata/ubuntu-20-04.ip6tables-legacy.golden
  test/transparentproxy/testdata/ubuntu-20-04.ip6tables.golden
  test/transparentproxy/testdata/ubuntu-22-04-with-multiple-flags.ip6tables-legacy.golden
  test/transparentproxy/testdata/ubuntu-22-04.ip6tables-legacy.golden
  test/transparentproxy/testdata/ubuntu-24-04-with-multiple-flags.ip6tables-legacy.golden
  test/transparentproxy/testdata/ubuntu-24-04.ip6tables-legacy.golden
Labels: ci/run-full-matrix, ci/force-publish

#11219 test(unit): regenerate golden files after merge
  pkg/plugins/policies/core/matchers/testdata/matchedpolicies/meshexternalservice/01.golden.yaml
  pkg/plugins/policies/core/rules/testdata/resourcerules/mretry_with_mes.global-k8s-2-zone-k8s.golden.yaml
  pkg/plugins/policies/core/rules/testdata/resourcerules/mretry_with_mes.global-k8s-2-zone-uni.golden.yaml
  pkg/plugins/policies/core/rules/testdata/resourcerules/mretry_with_mes.global-k8s.golden.yaml
  pkg/plugins/policies/core/rules/testdata/resourcerules/mretry_with_mes.global-uni-2-zone-k8s.golden.yaml
  pkg/plugins/policies/core/rules/testdata/resourcerules/mretry_with_mes.global-uni-2-zone-uni.golden.yaml
  pkg/plugins/policies/core/rules/testdata/resourcerules/mretry_with_mes.global-uni.golden.yaml
  pkg/plugins/policies/core/rules/testdata/resourcerules/mretry_with_mes.zone-k8s-2-global-k8s.golden.yaml
  pkg/plugins/policies/core/rules/testdata/resourcerules/mretry_with_mes.zone-k8s-2-global-uni.golden.yaml
  pkg/plugins/policies/core/rules/testdata/resourcerules/mretry_with_mes.zone-k8s-2-zone-k8s.golden.yaml
  pkg/plugins/policies/core/rules/testdata/resourcerules/mretry_with_mes.zone-k8s-2-zone-uni.golden.yaml
  pkg/plugins/policies/core/rules/testdata/resourcerules/mretry_with_mes.zone-k8s.golden.yaml
  pkg/plugins/policies/core/rules/testdata/resourcerules/mretry_with_mes.zone-uni-2-global-k8s.golden.yaml
  pkg/plugins/policies/core/rules/testdata/resourcerules/mretry_with_mes.zone-uni-2-global-uni.golden.yaml
  pkg/plugins/policies/core/rules/testdata/resourcerules/mretry_with_mes.zone-uni-2-zone-k8s.golden.yaml
  pkg/plugins/policies/core/rules/testdata/resourcerules/mretry_with_mes.zone-uni-2-zone-uni.golden.yaml
  pkg/plugins/policies/core/rules/testdata/resourcerules/mretry_with_mes.zone-uni.golden.yaml
Labels: ci/skip-e2e-test

#11223 test(e2e/debug): add kumactl inspect result when universal e2e test fail
  test/framework/debug.go
  test/framework/universal_cluster.go
Labels: backport

#11233 feat(meshtls): boilerplate
  app/kumactl/cmd/completion/testdata/bash.golden
  app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.dump-values.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.global-universal-on-k8s.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.registry.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.tproxy-ebpf-experimental-enabled.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.with-egress.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.with-helm-values.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.zone-universal-on-k8s.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/doNotChangeTlsChecksum.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/empty.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/envVarsDownwardApi.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/fix4485.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/fix4496.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/fix4935.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/fix5978.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/fix7724.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/fix7824.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/minReadySeconds.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/securityContext.golden.yaml
  app/kumactl/cmd/install/testdata/install-crds.all.golden.yaml
  deployments/charts/kuma/crds/kuma.io_meshtlses.yaml
  deployments/charts/kuma/values.yaml
  docs/generated/openapi.yaml
  docs/generated/raw/crds/kuma.io_meshtlses.yaml
  docs/generated/raw/helm-values.yaml
  docs/generated/raw/kuma-cp.yaml
  docs/guides/new-policies.md
  pkg/api-server/testdata/base_endpoints/_resources.golden.json
  pkg/api-server/testdata/base_endpoints/policies.golden.json
  pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
  pkg/config/plugins/policies/zz_generated.policies.go
  pkg/plugins/policies/core/ordered/ordered.go
  pkg/plugins/policies/meshtls/api/v1alpha1/meshtls.go
  pkg/plugins/policies/meshtls/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtls/api/v1alpha1/schema.yaml
  pkg/plugins/policies/meshtls/api/v1alpha1/zz_generated.resource.go
  pkg/plugins/policies/meshtls/k8s/v1alpha1/zz_generated.types.go
  pkg/plugins/policies/meshtls/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshtls/zz_generated.plugin.go
  pkg/plugins/policies/zz_generated.modules.go
Labels: ci/skip-e2e-test

#11245 test(e2e/universal): copy container logs during e2e universal debug
  test/framework/debug.go
Labels: backport

#11020 fix(kuma-cp): don't add namespace labels when resource was synced from universal zone
  app/kumactl/cmd/install/testdata/install-control-plane.cni-enabled.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.global.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.override-env-vars.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.overrides.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.registry.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.tproxy-ebpf-experimental-enabled.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.with-egress.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.with-helm-values.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.with-ingress.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.zone.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/doNotChangeTlsChecksum.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/empty.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/envVarsDownwardApi.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/fix4485.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/fix4496.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/fix4935.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/fix5978.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/fix7724.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/fix7824.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/minReadySeconds.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/securityContext.golden.yaml
  deployments/charts/kuma/templates/cp-webhooks-and-secrets.yaml
  pkg/core/resources/model/resource.go
  pkg/kds/context/context.go
  pkg/kds/v2/store/sync.go
  pkg/plugins/resources/k8s/store.go
  pkg/plugins/runtime/k8s/webhooks/defaulter_test.go
Labels: ci/run-full-matrix
