Repository kumahq/kuma, pull requests merged in 2024-07, with the labels that each got.

#10681 test(framework): request less resources for otel collector
  test/framework/debug.go
  test/framework/deployments/otelcollector/deployment_kubernetes.go
Labels: ci/skip-test

#10690 chore(deps): upgrade envoy to 1.27.7
  tools/releases/version.sh
Labels: release-2.4

#10686 chore(deps): upgrade envoy to 1.28.5
  tools/releases/version.sh
Labels: release-2.5

#10685 chore(deps): upgrade envoy to 1.28.5
  tools/releases/version.sh
Labels: release-2.6

#10691 chore(deps): upgrade envoy to 1.29.7
  tools/releases/version.sh
Labels: release-2.7

#10692 chore(deps): upgrade envoy to 1.30.4
  mk/dependencies/deps.lock
  mk/dev.mk
Labels: release-2.8

#10694 test(e2e): enable upgrade test
  test/e2e/helm/e2e_suite_test.go
Labels: release-2.8

#10706 test(framework): init TProxyConfig only in tproxy tests
  test/framework/config_transparentproxy.go
  test/transparentproxy/transparentproxy_suite_test.go
Labels: ci/run-full-matrix

#10707 test(cni): revert e2e taint test
  test/e2e/cni/taint_controller_race.go
Labels: ci/run-full-matrix, backport

#10739 test(e2e): refactor multizone env creation
  test/framework/envs/multizone/env.go
Labels: ci/run-full-matrix

#10561 fix(k8s): reenable deep copies
  pkg/plugins/bootstrap/k8s/plugin.go
Labels: ci/run-full-matrix

#10745 ci(.github): enable self hosted runners for AMD64 E2E tasks
  .github/workflows/_e2e.yaml
  .github/workflows/_test.yaml
Labels: ci/skip-test, backport

#10754 ci(dependabot): include all k8s updates in one group
  .github/dependabot.yml
Labels: ci/skip-test

#10782 ci(.github): disable self host runners for AMD64 tasks temporarily because of flakiness
  .github/workflows/_test.yaml
Labels: ci/skip-test

#10794 fix(transparent-proxy): allow iptables executable without mode
  pkg/transparentproxy/iptables/builder/builder_restore.go
  pkg/transparentproxy/iptables/consts/consts.go
Labels: ci/run-full-matrix

#10801 refactor(transparent-proxy): put default ports in consts package
  pkg/plugins/runtime/k8s/webhooks/injector/injector.go
  pkg/transparentproxy/config/config.go
  pkg/transparentproxy/iptables/consts/consts.go
Labels: backport

#10811 fix(transparent-proxy): don't add comments if no comment iptables module
  pkg/transparentproxy/iptables/builder/builder.go
  pkg/transparentproxy/iptables/builder/builder_table_nat_test.go
  pkg/transparentproxy/iptables/chains/chains.go
  pkg/transparentproxy/iptables/rules/rules.go
  pkg/transparentproxy/iptables/tables/tables.go
Labels: ci/run-full-matrix

#10810 test(transparent-proxy): refactor InstallFlagsToTest to use a map
  test/framework/utils/utils.go
  test/transparentproxy/config.go
  test/transparentproxy/install/install.go
Labels: ci/skip-test, backport

#10831 chore(transparent-proxy): increase tproxy tests timeout in CI
  .github/workflows/transparentproxy-tests.yaml
Labels: ci/skip-test, backport

#10837 docs(MADR): update referencing synced resources by `name/namespace`
  docs/madr/decisions/046-meshservice-policy-matching.md
Labels: ci/skip-test

#10847 chore(transparent-proxy): enhance test configuration and logging
  .github/workflows/transparentproxy-tests.yaml
  mk/test.mk
Labels: ci/skip-test, backport

#10839 refactor(transparent-proxy): improve IPv6 configuration handling
  app/kumactl/cmd/completion/testdata/bash.golden
  app/kumactl/cmd/install/install_transparent_proxy.go
  pkg/transparentproxy/config/config.go
  pkg/transparentproxy/ebpf/cleanup.go
  pkg/transparentproxy/ebpf/cleanup_fallback.go
  pkg/transparentproxy/ebpf/ebpf.go
  pkg/transparentproxy/ebpf/program.go
  pkg/transparentproxy/ebpf/setup.go
  pkg/transparentproxy/ebpf/setup_fallback.go
  pkg/transparentproxy/iptables/builder/builder.go
  pkg/transparentproxy/iptables/builder/builder_table_mangle.go
  pkg/transparentproxy/iptables/builder/builder_table_nat.go
  pkg/transparentproxy/iptables/builder/builder_table_nat_test.go
  pkg/transparentproxy/iptables/builder/builder_table_raw.go
  pkg/transparentproxy/iptables/chains/chains.go
  pkg/transparentproxy/iptables/consts/consts.go
  pkg/transparentproxy/iptables/rules/rules.go
  pkg/transparentproxy/iptables/setup.go
  pkg/transparentproxy/iptables/tables/table_mangle.go
  pkg/transparentproxy/iptables/tables/table_nat.go
  pkg/transparentproxy/iptables/tables/table_raw.go
  pkg/transparentproxy/iptables/tables/tables.go
  pkg/transparentproxy/test/config.go
  pkg/transparentproxy/transparentproxy.go
Labels: ci/run-full-matrix

#10871 test(transparent-proxy): add exclude ports flags to tproxy tests
  test/transparentproxy/config.go
  test/transparentproxy/install/testdata/alpine-3-with-multiple-flags.ip6tables-nft.golden
  test/transparentproxy/install/testdata/alpine-3-with-multiple-flags.ip6tables.golden
  test/transparentproxy/install/testdata/alpine-3-with-multiple-flags.iptables-nft.golden
  test/transparentproxy/install/testdata/alpine-3-with-multiple-flags.iptables.golden
  test/transparentproxy/install/testdata/amazon-linux-2-with-multiple-flags.ip6tables-legacy.golden
  test/transparentproxy/install/testdata/amazon-linux-2-with-multiple-flags.ip6tables.golden
  test/transparentproxy/install/testdata/amazon-linux-2-with-multiple-flags.iptables-legacy.golden
  test/transparentproxy/install/testdata/amazon-linux-2-with-multiple-flags.iptables.golden
  test/transparentproxy/install/testdata/amazon-linux-2023-with-multiple-flags.ip6tables-nft.golden
  test/transparentproxy/install/testdata/amazon-linux-2023-with-multiple-flags.ip6tables.golden
  test/transparentproxy/install/testdata/amazon-linux-2023-with-multiple-flags.iptables-nft.golden
  test/transparentproxy/install/testdata/amazon-linux-2023-with-multiple-flags.iptables.golden
  test/transparentproxy/install/testdata/debian-10-with-multiple-flags.ip6tables-nft.golden
  test/transparentproxy/install/testdata/debian-10-with-multiple-flags.ip6tables.golden
  test/transparentproxy/install/testdata/debian-10-with-multiple-flags.iptables-nft.golden
  test/transparentproxy/install/testdata/debian-10-with-multiple-flags.iptables.golden
  test/transparentproxy/install/testdata/debian-11-with-multiple-flags.ip6tables-nft.golden
  test/transparentproxy/install/testdata/debian-11-with-multiple-flags.ip6tables.golden
  test/transparentproxy/install/testdata/debian-11-with-multiple-flags.iptables-nft.golden
  test/transparentproxy/install/testdata/debian-11-with-multiple-flags.iptables.golden
  test/transparentproxy/install/testdata/debian-12-with-multiple-flags.ip6tables-nft.golden
  test/transparentproxy/install/testdata/debian-12-with-multiple-flags.ip6tables.golden
  test/transparentproxy/install/testdata/debian-12-with-multiple-flags.iptables-nft.golden
  test/transparentproxy/install/testdata/debian-12-with-multiple-flags.iptables.golden
  test/transparentproxy/install/testdata/fedora-38-with-multiple-flags.ip6tables-legacy.golden
  test/transparentproxy/install/testdata/fedora-38-with-multiple-flags.ip6tables.golden
  test/transparentproxy/install/testdata/fedora-38-with-multiple-flags.iptables-legacy.golden
  test/transparentproxy/install/testdata/fedora-38-with-multiple-flags.iptables.golden
  test/transparentproxy/install/testdata/fedora-39-with-multiple-flags.ip6tables-legacy.golden
  test/transparentproxy/install/testdata/fedora-39-with-multiple-flags.ip6tables.golden
  test/transparentproxy/install/testdata/fedora-39-with-multiple-flags.iptables-legacy.golden
  test/transparentproxy/install/testdata/fedora-39-with-multiple-flags.iptables.golden
  test/transparentproxy/install/testdata/fedora-40-with-multiple-flags.ip6tables-legacy.golden
  test/transparentproxy/install/testdata/fedora-40-with-multiple-flags.ip6tables.golden
  test/transparentproxy/install/testdata/fedora-40-with-multiple-flags.iptables-legacy.golden
  test/transparentproxy/install/testdata/fedora-40-with-multiple-flags.iptables.golden
  test/transparentproxy/install/testdata/fedora-41-with-multiple-flags.ip6tables-legacy.golden
  test/transparentproxy/install/testdata/fedora-41-with-multiple-flags.ip6tables.golden
  test/transparentproxy/install/testdata/fedora-41-with-multiple-flags.iptables-legacy.golden
  test/transparentproxy/install/testdata/fedora-41-with-multiple-flags.iptables.golden
  test/transparentproxy/install/testdata/rhel-8-with-multiple-flags.ip6tables.golden
  test/transparentproxy/install/testdata/rhel-8-with-multiple-flags.iptables.golden
  test/transparentproxy/install/testdata/rhel-9-with-multiple-flags.ip6tables-nft.golden
  test/transparentproxy/install/testdata/rhel-9-with-multiple-flags.ip6tables.golden
  test/transparentproxy/install/testdata/rhel-9-with-multiple-flags.iptables-nft.golden
  test/transparentproxy/install/testdata/rhel-9-with-multiple-flags.iptables.golden
  test/transparentproxy/install/testdata/ubuntu-18-04-with-multiple-flags.ip6tables.golden
  test/transparentproxy/install/testdata/ubuntu-18-04-with-multiple-flags.iptables.golden
  test/transparentproxy/install/testdata/ubuntu-20-04-with-multiple-flags.ip6tables-nft.golden
  test/transparentproxy/install/testdata/ubuntu-20-04-with-multiple-flags.iptables-nft.golden
  test/transparentproxy/install/testdata/ubuntu-22-04-with-multiple-flags.ip6tables-nft.golden
  test/transparentproxy/install/testdata/ubuntu-22-04-with-multiple-flags.ip6tables.golden
  test/transparentproxy/install/testdata/ubuntu-22-04-with-multiple-flags.iptables-nft.golden
  test/transparentproxy/install/testdata/ubuntu-22-04-with-multiple-flags.iptables.golden
  test/transparentproxy/install/testdata/ubuntu-24-04-with-multiple-flags.ip6tables-nft.golden
  test/transparentproxy/install/testdata/ubuntu-24-04-with-multiple-flags.ip6tables.golden
  test/transparentproxy/install/testdata/ubuntu-24-04-with-multiple-flags.iptables-nft.golden
  test/transparentproxy/install/testdata/ubuntu-24-04-with-multiple-flags.iptables.golden
Labels: ci/skip-test, backport

#10870 refactor(transparent-proxy): improvements in table builders
  pkg/transparentproxy/config/config.go
  pkg/transparentproxy/config/config_executables_functionality.go
  pkg/transparentproxy/config/config_suite_test.go
  pkg/transparentproxy/config/config_test.go
  pkg/transparentproxy/iptables/builder/builder_table_mangle.go
  pkg/transparentproxy/iptables/builder/builder_table_nat.go
  pkg/transparentproxy/iptables/builder/builder_table_raw.go
  pkg/transparentproxy/iptables/chains/chains.go
  pkg/transparentproxy/iptables/consts/consts.go
  pkg/transparentproxy/iptables/parameters/protocol.go
  pkg/transparentproxy/iptables/parameters/source.go
  pkg/transparentproxy/iptables/rules/rules.go
Labels: ci/run-full-matrix

#10890 feat(transparent-proxy): add option to uninstall transparent proxy
  app/kumactl/cmd/completion/testdata/bash.golden
  app/kumactl/cmd/install/install_transparent_proxy.go
  app/kumactl/cmd/install/install_transparent_proxy_test.go
  app/kumactl/cmd/uninstall/uninstall_suite_test.go
  app/kumactl/cmd/uninstall/uninstall_transparent_proxy.go
  app/kumactl/cmd/uninstall/uninstall_transparent_proxy_test.go
  pkg/transparentproxy/config/config.go
  pkg/transparentproxy/config/config_executables.go
  pkg/transparentproxy/config/config_logger.go
  pkg/transparentproxy/iptables/builder/builder.go
  pkg/transparentproxy/iptables/consts/consts.go
  pkg/transparentproxy/iptables/setup.go
  pkg/transparentproxy/transparentproxy.go
  test/transparentproxy/transparentproxy_test.go
Labels: ci/run-full-matrix

#10891 ci(circleci): upgrade go version on CircleCI config to 1.21.12
  .circleci/config.yml
  go.mod
Labels: ci/skip-test

#10905 fix(transparent-proxy): enable `kuma.io/transparent-proxying-ip-family-mode` annotation per pod
  pkg/plugins/runtime/k8s/webhooks/injector/injector.go
Labels: ci/run-full-matrix

#10924 docs(MADR): permissive mtls and mesh service
  docs/madr/decisions/058-meshservice-permissive-tls.md
Labels: ci/skip-test

#10934 chore(deps): upgrade envoy with DNS fix
  mk/dependencies/deps.lock
  mk/dev.mk
Labels: release-2.8

#10931 chore(deps): upgrade envoy with DNS fix
  tools/releases/version.sh
Labels: release-2.5

#10933 chore(deps): upgrade envoy with DNS fix
  tools/releases/version.sh
Labels: release-2.7

#10948 test(e2e): skip federation tests
  test/e2e/federation/federation_suite_test.go
Labels: ci/skip-test

#10737 docs(MADR): reachable/autoreachable services with Mesh*Service
  docs/madr/decisions/056-reachable-svc-mesh-service.md
Labels: ci/skip-test, ci/skip-e2e-test

#10916 docs(MADR): proxies stats of MeshService
  docs/madr/decisions/056-meshservice-proxies-stats.md
Labels: ci/skip-test

#10918 docs(MADR): SNI in the resource
  docs/madr/decisions/059-sni-in-the-resource.md
Labels: ci/skip-test

#10954 fix(kuma-cp): paginate Secrets correctly in universal
  pkg/core/bootstrap/bootstrap.go
  pkg/plugins/secrets/k8s/plugin.go
Labels: backport

#10726 docs(MADR): policy matching algorithm with the real resource kinds
  docs/madr/decisions/060-policy-matching-with-real-resources.md
Labels: ci/skip-test

#10966 fix(meshmetric): add missing timestamp in mapper
  app/kuma-dp/pkg/dataplane/metrics/metrics_format_mapper.go
  app/kuma-dp/pkg/dataplane/metrics/metrics_format_mapper_test.go
  app/kuma-dp/pkg/dataplane/metrics/metrics_producer.go
  app/kuma-dp/pkg/dataplane/metrics/testdata/otel/counter.golden.json
  app/kuma-dp/pkg/dataplane/metrics/testdata/otel/counter.in
  app/kuma-dp/pkg/dataplane/metrics/testdata/otel/gauge.golden.json
  app/kuma-dp/pkg/dataplane/metrics/testdata/otel/histogram.golden.json
  app/kuma-dp/pkg/dataplane/metrics/testdata/otel/summary.golden.json
Labels: backport

#10478 docs(MADR): default HostnameGenerators
  docs/madr/decisions/055-default-hostname-generators.md
Labels: ci/skip-test

#10981 chore(build): allow setting custom version of envoy
  mk/build.mk
  mk/dependencies/deps.lock
  mk/dev.mk
  mk/test.mk
  tools/releases/version.sh
Labels: release-2.7

#10945 ci(.github): enable self hosted runners for AMD64 E2E tasks
  .github/workflows/_e2e.yaml
  .github/workflows/_test.yaml
  .github/workflows/build-test-distribute.yaml
  mk/k3d.mk
  mk/kind.mk
  test/kind/cluster-ipv6-kuma-1.yaml
  test/kind/cluster-ipv6-kuma-2.yaml
  test/kind/cluster-ipv6-kuma.yaml
  test/kind/cluster-kuma-1.yaml
  test/kind/cluster-kuma-2.yaml
  test/kind/cluster-kuma.yaml
Labels: ci/run-full-matrix

#10858 docs(MADR): targeting mesh*routes in to section of policy
  docs/madr/decisions/057-rework-mesh-routes-matching.md
Labels: ci/skip-test
