Repository kumahq/kuma, pull requests merged in 2024-03, with the labels that each got.

#9457 ci(github): run golangci-lint before make dev/tools
  .github/workflows/build-test-distribute.yaml
Labels: ci/skip-test

#9456 ci(github): run image builds in parallel and add signing and scanning
  .github/workflows/_build.yaml
  .github/workflows/_build_publish.yaml
  .github/workflows/_publish.yaml
  .github/workflows/build-test-distribute.yaml
  mk/build.mk
  mk/docker.mk
  mk/test-container-structure.mk
Labels: ci/run-full-matrix, ci/force-publish

#9473 ci(mk): test-containers should run on enabled archs
  mk/test-container-structure.mk
Labels: ci/skip-e2e-test

#9475 chore(e2e): remove files which seems to not be used
  test/e2e/externalservices/testdata/externalservice-http-server.yaml
  test/e2e/externalservices/testdata/externalservice-https-server.yaml
Labels: ci/run-full-matrix

#9478 ci(github): use a specific version of ci-tools
  .github/workflows/release.yaml
Labels: ci/skip-test

#9269 docs(meshmetric): meshmetric profiles MADR
  docs/madr/decisions/038-meshmetric-profiles.md
Labels: ci/skip-test

#9470 docs(MADR): fixed grammatical error
  docs/madr/decisions/011-mesh-traffic-route.md
Labels: ci/skip-test

#9483 ci(github): set env in check for FULL_MATRIX
  .github/workflows/build-test-distribute.yaml
Labels: ci/skip-test

#9495 ci(actions): disable backport step temporarly
  .github/workflows/check.yaml
Labels: ci/skip-test

#9500 test(container-structure): skip iptable test on kuma-init
  test/container-structure/kuma-init.yaml
Labels: ci/skip-e2e-test

#9502 ci(github): use newer Kong/public-shared-actions
  .github/workflows/_build_publish.yaml
Labels: ci/skip-e2e-test

#9505 ci(github): fix helm publish
  .github/workflows/_build_publish.yaml
Labels: ci/skip-test

#9503 ci(github): enable image signing
  .github/workflows/_build_publish.yaml
  .github/workflows/_test.yaml
  .github/workflows/build-test-distribute.yaml
Labels: ci/skip-e2e-test, ci/force-publish

#9509 chore(workflow): increase timeout for update-insecure-dependencies
  .github/workflows/update-insecure-dependencies.yaml
Labels: ci/skip-test

#9501 feat(kds): add kds client version to outgoing context
  pkg/kds/context/context.go
Labels: ci/skip-test

#9498 ci(stability): tune refresh interval and eventually interval
  mk/test.mk
  test/e2e_env/kubernetes/gateway/delegated/meshmetric.go
Labels: ci/run-full-matrix

#9526 chore(workflow): add bash function to compare semvers
  tools/ci/update-vulnerable-dependencies.sh
Labels: ci/skip-test

#9539 chore(workflow): deduct the least common version for security updates
  mk/check.mk
  tools/ci/update-vulnerable-dependencies.sh
  tools/ci/update-vulnerable-dependencies/leastcommonversion/leastcommonversion.go
  tools/ci/update-vulnerable-dependencies/leastcommonversion/leastcommonversion_test.go
  tools/ci/update-vulnerable-dependencies/leastcommonversion/suite_test.go
  tools/ci/update-vulnerable-dependencies/main.go
  tools/ci/update-vulnerable-dependencies/update-vulnerable-dependencies.sh
Labels: ci/skip-e2e-test, backport

#9542 fix(xds): duplicated listeners
  pkg/xds/generator/outbound_proxy_generator.go
  pkg/xds/generator/outbound_proxy_generator_test.go
  pkg/xds/generator/testdata/outbound-proxy/08.envoy.golden.yaml
  pkg/xds/generator/testdata/outbound-proxy/11.envoy.golden.yaml
Labels: ci/run-full-matrix, backport

#9569 ci(.github): add checks permissions for golangci-lint-action
  .github/workflows/build-test-distribute.yaml
Labels: ci/skip-test

#9568 test(kuma-cp): fix order of expected/given
  pkg/config/app/kuma-cp/default_config_test.go
Labels: ci/skip-e2e-test

#9579 feat(meshmetric): profiles API
  app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present-not-enabled.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml
  app/kumactl/cmd/install/testdata/install-crds.all.golden.yaml
  app/kumactl/cmd/install/testdata/install-crds.experimental-gatewayapi.golden.yaml
  deployments/charts/kuma/crds/kuma.io_meshmetrics.yaml
  docs/generated/openapi.yaml
  docs/generated/raw/crds/kuma.io_meshmetrics.yaml
  pkg/plugins/policies/meshmetric/api/v1alpha1/meshmetric.go
  pkg/plugins/policies/meshmetric/api/v1alpha1/schema.yaml
  pkg/plugins/policies/meshmetric/api/v1alpha1/validator.go
  pkg/plugins/policies/meshmetric/api/v1alpha1/validator_test.go
  pkg/plugins/policies/meshmetric/api/v1alpha1/zz_generated.deepcopy.go
  pkg/plugins/policies/meshmetric/k8s/crd/kuma.io_meshmetrics.yaml
  pkg/test/resources/validators/validation.go
Labels: ci/skip-e2e-test

#9548 ci(github): add provenance for binary artifacts
  .github/workflows/_build_publish.yaml
  .github/workflows/_provenance.yaml
  .github/workflows/_test.yaml
  .github/workflows/build-test-distribute.yaml
Labels: ci/skip-test, ci/force-publish

#9592 fix(kuma-cp): clone outbound tags
  pkg/xds/generator/outbound_proxy_generator.go
Labels: backport

#9602 ci(github): don't build on PRs
  .github/workflows/build-test-distribute.yaml
  meta_repo.yml
Labels: ci/skip-test, ci/run-build

#9600 chore(deps): bump envoy version to v1.29.2
  tools/releases/version.sh
Labels: ci/run-full-matrix

#9610 test(_rules): add test case with httproutes with listeners on meshgateways
  pkg/api-server/testdata/resources/inspect/meshgateways/_rules/meshgateway2.golden.json
  pkg/api-server/testdata/resources/inspect/meshgateways/_rules/meshgateway2.input.yaml
Labels: ci/skip-e2e-test

#9583 feat(MeshService): xds generation
  api/common/v1alpha1/ref.go
  api/common/v1alpha1/zz_generated.deepcopy.go
  app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present-not-enabled.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml
  app/kumactl/cmd/install/testdata/install-crds.all.golden.yaml
  app/kumactl/cmd/install/testdata/install-crds.experimental-gatewayapi.golden.yaml
  deployments/charts/kuma/crds/kuma.io_meshhttproutes.yaml
  deployments/charts/kuma/crds/kuma.io_meshtcproutes.yaml
  docs/generated/openapi.yaml
  docs/generated/raw/crds/kuma.io_meshhttproutes.yaml
  docs/generated/raw/crds/kuma.io_meshtcproutes.yaml
  pkg/core/resources/apis/meshservice/api/v1alpha1/helpers.go
  pkg/plugins/policies/core/xds/meshroute/listeners.go
  pkg/plugins/policies/meshhttproute/api/v1alpha1/meshhttproute.go
  pkg/plugins/policies/meshhttproute/api/v1alpha1/schema.yaml
  pkg/plugins/policies/meshhttproute/api/v1alpha1/validation.go
  pkg/plugins/policies/meshhttproute/k8s/crd/kuma.io_meshhttproutes.yaml
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/gateway_routes.go
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/listeners.go
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/plugin_test.go
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/default-meshservice.clusters.golden.yaml
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/default-meshservice.endpoints.golden.yaml
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/default-meshservice.listeners.golden.yaml
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/default-meshservice.routes.golden.yaml
  pkg/plugins/policies/meshhttproute/xds/builder.go
  pkg/plugins/policies/meshhttproute/xds/configurer.go
  pkg/plugins/policies/meshhttproute/xds/filters/requestmirror.go
  pkg/plugins/policies/meshtcproute/api/v1alpha1/schema.yaml
  pkg/plugins/policies/meshtcproute/k8s/crd/kuma.io_meshtcproutes.yaml
  pkg/plugins/policies/meshtcproute/plugin/v1alpha1/listeners.go
  pkg/plugins/runtime/k8s/controllers/gatewayapi/mesh_http_route_conversion.go
  pkg/test/xds/builders/context_builder.go
  pkg/xds/context/context.go
  pkg/xds/context/mesh_context_builder.go
  pkg/xds/context/resources.go
  pkg/xds/topology/outbound.go
  pkg/xds/topology/outbound_test.go
Labels: ci/run-full-matrix

#9652 fix(MeshHTTPRoute): fix response headers filter in gateway route generation
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/gateway_routes.go
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/plugin_test.go
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/request-header-modifiers.clusters.golden.yaml
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/request-header-modifiers.endpoints.golden.yaml
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/request-header-modifiers.listeners.golden.yaml
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/request-header-modifiers.routes.golden.yaml
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/request-redirect.clusters.golden.yaml
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/request-redirect.endpoints.golden.yaml
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/request-redirect.listeners.golden.yaml
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/request-redirect.routes.golden.yaml
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/response-header-modifiers.clusters.golden.yaml
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/response-header-modifiers.endpoints.golden.yaml
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/response-header-modifiers.listeners.golden.yaml
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/response-header-modifiers.routes.golden.yaml
Labels: backport

#9672 ci(github): update public-shared-actions
  .github/workflows/_build_publish.yaml
  .github/workflows/build-test-distribute.yaml
Labels: ci/skip-test

#9673 ci(github): don't free disk space in e2e tests
  .github/workflows/_e2e.yaml
Labels: ci/skip-test

#9720 ci(github): add back all the disk pruning
  .github/workflows/_e2e.yaml
Labels: ci/skip-test

#9701 feat(images/kuma-init): use iptables-wrapper to use correct iptables version
  mk/build.mk
  mk/check.mk
  mk/docker.mk
  tools/releases/dockerfiles/kuma-init.Dockerfile
  tools/releases/dockerfiles/kuma-init.Dockerfile.dockerignore
Labels: ci/run-full-matrix, backport

#9585 ci(github): add provenance for images
  .github/workflows/_build_publish.yaml
  .github/workflows/_provenance.yaml
  .github/workflows/build-test-distribute.yaml
Labels: ci/skip-test, ci/force-publish, ci/run-build

#9731 build(kuma-init): don't run try to run iptables when building kuma-init
  tools/releases/dockerfiles/kuma-init.Dockerfile
Labels: ci/run-build

#9734 chore(kuma-init): revert iptables wrapper changes
  mk/build.mk
  mk/check.mk
  mk/docker.mk
  tools/releases/dockerfiles/kuma-init.Dockerfile
  tools/releases/dockerfiles/kuma-init.Dockerfile.dockerignore
Labels: backport

#9737 chore(meshmetric): adjust logs
  app/kuma-dp/pkg/dataplane/metrics/profiles.go
Labels: ci/skip-test

#9689 docs(MADR): mesh service api
  docs/madr/decisions/039-meshservice-api.md
Labels: ci/skip-test

#9753 ci(github): increase image build timeout a limit
  .github/workflows/_build_publish.yaml
Labels: ci/skip-test

#9755 Revert "feat(images/kuma-init): use iptables-wrapper to use correct iptables version (backport of #9701) (#9728)"
  mk/build.mk
  mk/check.mk
  mk/docker.mk
  tools/releases/dockerfiles/kuma-init.Dockerfile
  tools/releases/dockerfiles/kuma-init.Dockerfile.dockerignore
Labels: ci/skip-test

#9757 Revert "feat(images/kuma-init): use iptables-wrapper to use correct iptables version (backport of #9701) (#9726)"
  mk/build.mk
  mk/check.mk
  mk/docker.mk
  tools/releases/dockerfiles/kuma-init.Dockerfile
  tools/releases/dockerfiles/kuma-init.Dockerfile.dockerignore
Labels: ci/skip-test

#9758 Revert "feat(images/kuma-init): use iptables-wrapper to use correct iptables version (backport of #9701) (#9725)"
  mk/build.mk
  mk/check.mk
  mk/docker.mk
  tools/releases/dockerfiles/kuma-init.Dockerfile
  tools/releases/dockerfiles/kuma-init.Dockerfile.dockerignore
Labels: ci/skip-test

#9759 Revert "feat(images/kuma-init): use iptables-wrapper to use correct iptables version (backport of #9701) (#9727)"
  mk/build.mk
  mk/check.mk
  mk/docker.mk
  tools/releases/dockerfiles/kuma-init.Dockerfile
  tools/releases/dockerfiles/kuma-init.Dockerfile.dockerignore
Labels: ci/skip-test

#9756 Revert "feat(images/kuma-init): use iptables-wrapper to use correct iptables version (backport of #9701) (#9724)"
  mk/build.mk
  mk/check.mk
  mk/docker.mk
  tools/releases/dockerfiles/kuma-init.Dockerfile
  tools/releases/dockerfiles/kuma-init.Dockerfile.dockerignore
Labels: ci/skip-test

#9750 feat(transparent-proxy): add automatic iptables type detection
  app/cni/pkg/cni/injector_linux.go
  app/kumactl/cmd/completion/testdata/bash.golden
  app/kumactl/cmd/install/install_transparent_proxy.go
  app/kumactl/cmd/install/install_transparent_proxy_test.go
  app/kumactl/cmd/install/testdata/install-transparent-proxy.dns.no-conntrack.golden.txt
  pkg/transparentproxy/iptables/builder/builder.go
  pkg/transparentproxy/iptables/builder/builder_restore.go
  pkg/transparentproxy/iptables/setup.go
  pkg/transparentproxy/setup.go
  pkg/transparentproxy/transparentproxy.go
  pkg/transparentproxy/transparentproxy_v2.go
  test/blackbox_network_tests/dns_test.go
  test/blackbox_network_tests/inbound_redirect_test.go
  test/blackbox_network_tests/outbound_redirect_test.go
  test/framework/universal_app.go
  tools/releases/dockerfiles/kuma-init.Dockerfile
Labels: backport

#9760 ci(github): tweak parallelism in build-test-distribute
  .github/workflows/build-test-distribute.yaml
Labels: ci/skip-test
