Repository kumahq/kuma, pull requests merged in 2024-02, with the labels that each got.

#9124 fix(kubernetes): create builtin CA once
  pkg/plugins/runtime/k8s/controllers/mesh_controller.go
  pkg/plugins/runtime/k8s/controllers/mesh_controller_test.go
  pkg/plugins/runtime/k8s/controllers/mesh_defaults_controller.go
  pkg/plugins/runtime/k8s/plugin.go
Labels: backport

#9137 chore(helm): added action for helm release
  .github/workflows/helm-release.yaml
Labels: ci/skip-test, ci/skip-e2e-test

#9147 ci(distribute): prolong timeout on distribute
  .github/workflows/build-test-distribute.yaml
Labels: ci/skip-test

#9134 chore(deps): upgrade envoy to v1.29.0
  tools/releases/version.sh
Labels: ci/run-full-matrix

#9146 docs(UPGRADE.md): clarify changes in policies sorting
  UPGRADE.md
Labels: ci/skip-test

#9190 test(e2e): use `kumactl get meshes` to check on kuma health
  test/framework/k8s_controlplane.go
  test/framework/universal_cluster.go
Labels: ci/run-full-matrix

#9222 chore(deps): upgrade envoy to v1.29.1
  tools/releases/version.sh
Labels: ci/run-full-matrix, master

#9218 chore(deps): upgrade envoy to v1.28.1
  tools/releases/version.sh
Labels: ci/run-full-matrix, release-2.6

#9220 chore(deps): upgrade envoy to v1.27.3
  tools/releases/version.sh
Labels: ci/run-full-matrix, release-2.4

#9219 chore(deps): upgrade envoy to v1.28.1
  tools/releases/version.sh
Labels: ci/run-full-matrix, release-2.5

#9221 chore(deps): upgrade envoy to v1.26.7
  tools/releases/version.sh
Labels: ci/run-full-matrix, release-2.3

#9228 fix(gatewayapi): don't add HTTPRoute status if Kuma isn't the controller
  pkg/plugins/runtime/k8s/controllers/gatewayapi/http_route_controller.go
Labels: backport

#9225 chore(logging): do not log proxy object
  pkg/xds/server/v3/reconcile.go
Labels: ci/skip-test

#9254 fix(kuma-cp): copy annotations when adding/update k8s object
  pkg/plugins/resources/k8s/store.go
Labels: backport

#9259 fix(kuma-cp): kds sync on upgrade doubles the number of policies
  pkg/api-server/api_server_suite_test.go
  pkg/api-server/circuit_breaker_endpoints_test.go
  pkg/api-server/fault_injection_endpoints_test.go
  pkg/api-server/global_secret_endpoints_test.go
  pkg/api-server/health_check_endpoints_test.go
  pkg/api-server/resource_endpoints.go
  pkg/api-server/resource_endpoints_test.go
  pkg/api-server/secret_endpoints_test.go
  pkg/api-server/testdata/resource_400onNoOriginLabel.golden.json
  pkg/api-server/traffic_route_endpoints_test.go
  pkg/api-server/traffic_trace_endpoints_test.go
  pkg/core/resources/model/resource.go
  pkg/kds/context/context.go
  pkg/plugins/runtime/k8s/plugin.go
  pkg/plugins/runtime/k8s/webhooks/defaulter.go
  pkg/plugins/runtime/k8s/webhooks/defaulter_test.go
  pkg/plugins/runtime/k8s/webhooks/resourceadmissionchecker.go
  pkg/plugins/runtime/k8s/webhooks/validation.go
  pkg/plugins/runtime/k8s/webhooks/validation_test.go
  test/e2e/helm/kuma_helm_upgrade_multizone.go
Labels: backport

#9276 chore(e2e): try to move some tests to another job
  .github/workflows/build-test-distribute.yaml
  .github/workflows/e2e.yaml
  test/e2e/bootstrap/e2e_suite_test.go
  test/e2e/cni/e2e_suite_test.go
  test/e2e/externalservices/e2e_suite_test.go
  test/e2e/federation/federation_suite_test.go
  test/e2e/federation/federation_universal.go
  test/e2e/helm/e2e_suite_test.go
  test/e2e/reachableservices/auto_reachable_services_k8s.go
  test/e2e/reachableservices/e2e_suite_test.go
  test/e2e/trafficpermission/kubernetes/e2e_suite_test.go
  test/e2e/virtualoutbound/e2e_suite_test.go
  test/e2e/virtualoutbound/virtualoutbound_k8s.go
  test/e2e_env/kubernetes/meshproxypatch/meshproxypatch.go
  test/e2e_env/multizone/meshhttproute/test.go
Labels: ci/run-full-matrix

#9328 ci(release): add concurrency group
  .github/workflows/release.yaml
Labels: ci/skip-test

#9335 ci(.github): fix schedule for release.yaml (backport #6487)
  .github/workflows/release.yaml
Labels: ci/skip-test

#9338 test(e2e): remove legacy KDS job
  .circleci/config.yml
  .github/workflows/build-test-distribute.yaml
  .github/workflows/e2e.yaml
  test/e2e_env/multizone/meshtimeout/meshtimeout.go
  test/e2e_env/multizone/sync/sync.go
  test/framework/config.go
Labels: ci/run-full-matrix

#9339 chore(kind): remove unused variable and rename file
  mk/kind.mk
  test/kind/cluster-ipv6-kuma.yaml
  test/kind/cluster-kuma.yaml
Labels: ci/run-full-matrix

#9370 ci(gh-action/check): increase check job timeout to 15 minutes
  .github/workflows/build-test-distribute.yaml
  .github/workflows/check.yaml
Labels: backport

#9362 test(meshtimeout): fix test route matching
  pkg/plugins/policies/meshtimeout/plugin/testdata/outbound_listener_with_different_timeouts_per_route.yaml
  pkg/plugins/policies/meshtimeout/plugin/v1alpha1/plugin_test.go
Labels: ci/skip-e2e-test

#9392 Revert "ci(e2e): upload junit results to gh artifacts (#9354)"
  .github/workflows/e2e.yaml
  mk/test.mk
Labels: ci/skip-test

#9350 ci(e2e): disable flaking tests
  test/e2e_env/kubernetes/gateway/delegated/meshproxypatch.go
  test/e2e_env/multizone/meshhttproute/test.go
  test/e2e_env/multizone/resilience/resilience_multizone_universal_postgres.go
  test/e2e_env/universal/reachableservices/reachableservices.go
Labels: ci/skip-test

#9430 ci(gh-actions): pin versions in commitlint deps for "Lint PRs" workflow
  .github/workflows/check.yaml
Labels: ci/skip-test, backport

#8654 docs(MADR): internal listener naming
  docs/madr/decisions/036-internal-listeners.md
Labels: ci/skip-test

#9441 ci(github): add SBOM from project
  .github/workflows/_build.yaml
  .github/workflows/_publish.yaml
  .github/workflows/build-test-distribute.yaml
  .syft.yaml
Labels: ci/skip-test
