Repository kumahq/kuma, pull requests merged in 2025-04, with the labels that each got.

#13279 chore(codeql): ignore security warning in test file
  .github/codeql/codeql-config.yml
Labels: ci/skip-test, ci/skip-e2e-test

#13290 test(unit): remove skipped MeshCircuitBreaker tests
  pkg/plugins/policies/meshcircuitbreaker/api/v1alpha1/validator_test.go
  pkg/plugins/policies/meshcircuitbreaker/plugin/v1alpha1/plugin_test.go
Labels: ci/skip-e2e-test

#13292 test(unit): remove skipped MeshLoadBalancingPolicy
  pkg/plugins/policies/meshloadbalancingstrategy/api/v1alpha1/validator_test.go
  pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/plugin_test.go
  pkg/test/resources/validators/validation.go
Labels: ci/skip-e2e-test

#13293 test(unit): remove skipped MeshHealthCheck test
  pkg/plugins/policies/meshhealthcheck/api/v1alpha1/validator_test.go
  pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/plugin_test.go
Labels: ci/skip-e2e-test

#13314 ci(deps): add retry to downloading envoy and coredns
  mk/build.mk
Labels: ci/skip-test

#13262 docs(MADR): reworking transparent proxy config with ConfigMaps
  docs/madr/decisions/071-transparent-proxy-config-map-handling-outside-the-control-plane.md
Labels: kind/docs, ci/skip-test

#13124 feat(dns): embedded DNS server instead of coreDNS
  .github/workflows/_e2e.yaml
  .github/workflows/_test.yaml
  app/kuma-dp/cmd/context.go
  app/kuma-dp/cmd/run.go
  app/kuma-dp/cmd/run_test.go
  app/kuma-dp/pkg/dataplane/configfetcher/component.go
  app/kuma-dp/pkg/dataplane/configfetcher/metrics.go
  app/kuma-dp/pkg/dataplane/dnsproxy/component.go
  app/kuma-dp/pkg/dataplane/dnsproxy/component_test.go
  app/kuma-dp/pkg/dataplane/dnsproxy/metrics.go
  app/kuma-dp/pkg/dataplane/dnsproxy/suite_test.go
  app/kuma-dp/pkg/dataplane/envoy/remote_bootstrap.go
  app/kuma-dp/pkg/dataplane/envoy/remote_bootstrap_test.go
  app/kuma-dp/pkg/dataplane/envoy/testdata/bootstrap-request-0.golden.json
  app/kuma-dp/pkg/dataplane/envoy/testdata/bootstrap-request-1.golden.json
  app/kuma-dp/pkg/dataplane/envoy/testdata/bootstrap-request-2.golden.json
  app/kuma-dp/pkg/dataplane/envoy/testdata/bootstrap-request-3.golden.json
  app/kuma-dp/pkg/dataplane/meshmetrics/component.go
  pkg/config/app/kuma-dp/config.go
  pkg/config/app/kuma-dp/testdata/default-config.golden.yaml
  pkg/config/loader_test.go
  pkg/config/plugins/runtime/k8s/config.go
  pkg/core/xds/features.go
  pkg/dns/dpapi/api.go
  pkg/plugins/policies/meshmetric/dpapi/api.go
  pkg/plugins/policies/meshmetric/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshmetric/plugin/v1alpha1/testdata/basic.listeners.golden.yaml
  pkg/plugins/policies/meshmetric/plugin/v1alpha1/testdata/default.listeners.golden.yaml
  pkg/plugins/policies/meshmetric/plugin/v1alpha1/testdata/multiple_otel.listeners.golden.yaml
  pkg/plugins/policies/meshmetric/plugin/v1alpha1/testdata/multiple_prometheus.listeners.golden.yaml
  pkg/plugins/policies/meshmetric/plugin/v1alpha1/testdata/openTelemetry.listeners.golden.yaml
  pkg/plugins/policies/meshmetric/plugin/v1alpha1/testdata/otel_and_prometheus.listeners.golden.yaml
  pkg/plugins/policies/meshmetric/plugin/v1alpha1/testdata/provided_tls.listeners.golden.yaml
  pkg/plugins/policies/meshmetric/plugin/xds/dpp_config_configurer.go
  pkg/plugins/runtime/k8s/containers/factory.go
  pkg/xds/dynconf/listener.go
  pkg/xds/generator/dns_generator.go
  pkg/xds/generator/dns_generator_test.go
  pkg/xds/generator/proxy_template_test.go
  pkg/xds/generator/testdata/dns/4-dataplane.input.yaml
  pkg/xds/generator/testdata/dns/4-envoy-config.golden.yaml
  test/e2e_env/kubernetes/gateway/delegated.go
  test/e2e_env/kubernetes/meshmetric/meshmetric.go
  test/framework/config.go
  test/framework/envs/kubernetes/env.go
  test/framework/universal_cluster.go
Labels: ci/run-full-matrix

#13352 chore(lint): add rule to deny `sigs.k8s.io/controller-runtime/pkg/log` usage
  .golangci.yml
  pkg/test/ginkgo.go
Labels: ci/skip-test

#12760 feat(kuma-cp): deduplicate dataplane inbounds by address and port combination
  pkg/plugins/runtime/k8s/controllers/inbound_converter.go
  pkg/plugins/runtime/k8s/controllers/pod_controller.go
  pkg/plugins/runtime/k8s/controllers/pod_controller_test.go
  pkg/plugins/runtime/k8s/controllers/pod_converter.go
  pkg/plugins/runtime/k8s/controllers/pod_converter_test.go
  pkg/plugins/runtime/k8s/controllers/testdata/18.services-for-pod.yaml
  pkg/plugins/runtime/k8s/controllers/testdata/duplicated-inbounds.dataplane.yaml
  pkg/plugins/runtime/k8s/controllers/testdata/duplicated-inbounds.pod.yaml
  pkg/plugins/runtime/k8s/controllers/testdata/duplicated-inbounds.services-for-pod.yaml
Labels: ci/run-full-matrix

#13383 fix(openapi): rename RSAbits to rsaBits
  api/mesh/v1alpha1/builtincertificateauthorityconfig/schema.yaml
  docs/generated/openapi.yaml
  tools/resource-gen/pkg/generator/main.go
Labels: ci/skip-e2e-test

#13301 test(framework): support running universal tests on remote host
  test/framework/deployments/docker.go
  test/framework/deployments/observability/universal.go
  test/framework/deployments/otelcollector/deployment.go
  test/framework/deployments/postgres/universal.go
  test/framework/docker.go
  test/framework/setup.go
  test/framework/ssh/host.go
  test/framework/ssh/portforward.go
  test/framework/universal/networking.go
  test/framework/universal_app.go
  test/framework/universal_cluster.go
Labels: ci/run-full-matrix

#13392 ci(ipv6): disable kind ip v6 because of a kernel bug
  .github/workflows/_e2e.yaml
Labels: ci/run-full-matrix

#13318 fix(kumactl): change mtls backend builtin to provided and skipvalidation
  app/kumactl/cmd/export/export.go
  app/kumactl/cmd/export/export_test.go
  app/kumactl/cmd/export/testdata/export-federation-with-policies.golden.yaml
  app/kumactl/cmd/export/testdata/export-kube.golden.yaml
  app/kumactl/cmd/export/testdata/export-uni.golden.yaml
  app/kumactl/cmd/export/testdata/kube-input.Mesh.mesh-with-mtls.json
  app/kumactl/cmd/export/testdata/kube-input.Secret.mesh-with-mtls.ca-builtin-cert-ca-1.json
  app/kumactl/cmd/export/testdata/kube-input.Secret.mesh-with-mtls.ca-builtin-key-ca-1.json
  pkg/core/resources/apis/system/constants.go
  pkg/core/resources/model/utils.go
  pkg/plugins/ca/builtin/manager.go
  pkg/test/resources/samples/secret_samples.go
  pkg/util/proto/proto.go
  test/e2e/federation/federation_suite_test.go
Labels: ci/run-full-matrix

#13405 ci(pr-comments): fix format comment
  .github/workflows/pr-comments.yaml
Labels: ci/skip-test, ci/skip-e2e-test

#13409 feat(kuma-dp): add support for dynamic transparent proxy config
  app/kuma-dp/cmd/run.go
  app/kuma-dp/pkg/dataplane/envoy/remote_bootstrap.go
  app/kumactl/cmd/install/install_transparent_proxy.go
  pkg/config/app/kuma-dp/config.go
  pkg/config/loader.go
  pkg/core/resources/apis/mesh/dataplane_helpers.go
  pkg/core/resources/apis/mesh/dataplane_helpers_test.go
  pkg/core/xds/metadata.go
  pkg/core/xds/types.go
  pkg/core/xds/types/features.go
  pkg/hds/tracker/healthcheck_generator.go
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/listeners.go
  pkg/plugins/policies/meshtcproute/plugin/v1alpha1/listeners.go
  pkg/plugins/policies/meshtls/plugin/v1alpha1/plugin.go
  pkg/transparentproxy/config/config.go
  pkg/transparentproxy/config/dataplane/config_dataplane.go
  pkg/transparentproxy/config/dataplane/config_dataplane_suite_test.go
  pkg/transparentproxy/config/dataplane/config_dataplane_test.go
  pkg/xds/bootstrap/generator.go
  pkg/xds/bootstrap/generator_test.go
  pkg/xds/bootstrap/handler.go
  pkg/xds/bootstrap/parameters.go
  pkg/xds/bootstrap/template_v3.go
  pkg/xds/bootstrap/types/bootstrap_request.go
  pkg/xds/bootstrap/types/bootstrap_response.go
  pkg/xds/envoy/listeners/listener_configurers.go
  pkg/xds/envoy/listeners/v3/http_access_log_configurer_test.go
  pkg/xds/envoy/listeners/v3/network_access_log_configurer_test.go
  pkg/xds/envoy/listeners/v3/transparent_proxying_configurer_test.go
  pkg/xds/generator/direct_access_proxy_generator.go
  pkg/xds/generator/dns_generator.go
  pkg/xds/generator/inbound_proxy_generator.go
  pkg/xds/generator/outbound_proxy_generator.go
  pkg/xds/generator/outbound_proxy_generator_test.go
  pkg/xds/generator/probe_generator.go
  pkg/xds/generator/transparent_proxy_generator.go
Labels: ci/run-full-matrix

#13410 fix(util): fix bad sanitization of report entry names
  test/framework/report/report.go
Labels: ci/skip-test

#13336 chore(logs): add more info to kuma-validation failure logs
  pkg/transparentproxy/validate/validator.go
Labels: ci/skip-test

#13316 chore(debug): add dump report to e2e tests
  test/e2e/bootstrap/corefile_template.go
  test/e2e/bootstrap/e2e_suite_test.go
  test/e2e/cni/e2e_suite_test.go
  test/e2e/cni/exclude_outbound_port.go
  test/e2e/cni/taint_controller_race.go
  test/e2e/compatibility/cp_compatibility_kubernetes_multizone.go
  test/e2e/compatibility/e2e_suite_test.go
  test/e2e/externalservices/e2e_suite_test.go
  test/e2e/externalservices/externalservices_kubernetes_without_egress.go
  test/e2e/federation/federation_universal.go
  test/e2e/helm/kuma_helm_deploy_global_and_zone_universal_mode.go
  test/e2e/helm/kuma_helm_deploy_global_universal_mode_and_zone.go
  test/e2e/helm/kuma_helm_deploy_global_zone.go
  test/e2e/helm/kuma_helm_upgrade_multizone.go
  test/e2e/helm/kuma_helm_upgrade_standalone.go
  test/e2e/reachableservices/auto_reachable_mesh_services_k8s.go
  test/e2e/reachableservices/auto_reachable_services_k8s.go
  test/e2e/reachableservices/e2e_suite_test.go
  test/e2e/resilience/e2e_suite_test.go
  test/e2e/resilience/resilience_multizone_k8s.go
  test/e2e/trafficpermission/kubernetes/e2e_suite_test.go
  test/e2e/trafficpermission/kubernetes/traffic_permission_k8s.go
  test/e2e/zoneegress/externalservices/e2e_suite_test.go
  test/e2e/zoneegress/externalservices/zoneegress_externalservices_hybrid.go
Labels: ci/run-full-matrix

#13428 refactor(kuma-dp): remove `BootstrapParams` to simplify bootstrap config fetch
  app/kuma-dp/cmd/context.go
  app/kuma-dp/cmd/run.go
  app/kuma-dp/cmd/run_test.go
  app/kuma-dp/pkg/dataplane/envoy/envoy.go
  app/kuma-dp/pkg/dataplane/envoy/remote_bootstrap.go
  app/kuma-dp/pkg/dataplane/envoy/remote_bootstrap_test.go
  app/kuma-dp/pkg/dataplane/envoy/testdata/bootstrap-request-0.golden.json
  app/kuma-dp/pkg/dataplane/envoy/testdata/bootstrap-request-metrics-metadata.golden.json
  app/kuma-dp/pkg/dataplane/envoy/testdata/bootstrap-request-token-path.golden.json
  app/kuma-dp/pkg/dataplane/envoy/testdata/bootstrap-request-transparent-proxy.golden.json
Labels: ci/run-full-matrix

#13438 chore(deps): upgrade envoy version from v1.33.2 to v1.34.0
  mk/dependencies/deps.lock
  mk/dev.mk
Labels: dependencies

#13445 Revert "ci(ipv6): disable kind ip v6 because of a kernel bug (#13392)"
  .github/workflows/_e2e.yaml
Labels: ci/run-full-matrix

#13450 Reapply "ci(ipv6): disable kind ip v6 because of a kernel bug (#13392…)" (#13445)
  .github/workflows/_e2e.yaml
Labels: ci/skip-test

#13458 docs(MADR): update resource identifier format limitations
  docs/madr/decisions/070-resource-identifier.md
Labels: ci/skip-test

#13479 feat(oapi): add dataplane openapi spec
  api/mesh/v1alpha1/dataplane/rest.yaml
  api/mesh/v1alpha1/dataplane/schema.yaml
  docs/generated/openapi.yaml
  tools/resource-gen/pkg/generator/main.go
Labels: ci/skip-e2e-test

#13355 docs(MADR): update MADR template to our current workflow
  docs/madr/decisions/000-template.md
Labels: ci/skip-test

#13483 feat(oapi): add missing dataplane overview andpoints and fix casing
  api/mesh/v1alpha1/dataplane/schema.yaml
  api/mesh/v1alpha1/dataplaneoverview/schema.yaml
  api/mesh/v1alpha1/meshgateway/schema.yaml
  api/openapi/specs/api.yaml
  docs/generated/openapi.yaml
  tools/resource-gen/pkg/generator/main.go
Labels: ci/skip-e2e-test
