Repository kumahq/kuma, pull requests merged in 2025-02, with the labels that each got.

#12704 test(e2e): increase time and use correct option
  test/e2e/federation/federation_kubernetes.go
Labels: release-2.7

#12747 fix(api): mark warnings as read-only
  api/mesh/v1alpha1/mesh/rest.yaml
  api/mesh/v1alpha1/meshgateway/rest.yaml
  docs/generated/openapi.yaml
  pkg/core/resources/apis/hostnamegenerator/api/v1alpha1/rest.yaml
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/rest.yaml
  pkg/core/resources/apis/meshmultizoneservice/api/v1alpha1/rest.yaml
  pkg/core/resources/apis/meshservice/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshaccesslog/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshcircuitbreaker/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshfaultinjection/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshhealthcheck/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshhttproute/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshloadbalancingstrategy/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshmetric/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshpassthrough/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshproxypatch/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshratelimit/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshretry/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtcproute/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtimeout/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtls/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtrace/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtrafficpermission/api/v1alpha1/rest.yaml
  tools/openapi/templates/endpoints.yaml
Labels: ci/skip-e2e-test

#12714 chore(cleanup): remove deprecated code
  UPGRADE.md
  app/kuma-dp/cmd/dataplane.go
  app/kumactl/cmd/apply/apply.go
  pkg/api-server/resource_endpoints.go
  pkg/core/resources/apis/mesh/meta_validator.go
  pkg/core/resources/apis/mesh/meta_validator_test.go
  test/e2e_env/multizone/localityawarelb/locality_aware_multizone_hybrid.go
  test/e2e_env/multizone/localityawarelb/locality_aware_multizone_hybrid_egress.go
  test/e2e_env/multizone/localityawarelb/locality_aware_multizone_hybrid_gateway.go
  test/framework/setup.go
Labels: ci/run-full-matrix

#12728 fix(meshtimeout): set default inbound timeouts correctly (backport of #12692)
  pkg/plugins/policies/meshtimeout/plugin/testdata/basic_without_defaults_inbound_cluster.golden.yaml
  pkg/plugins/policies/meshtimeout/plugin/testdata/basic_without_defaults_inbound_listener.golden.yaml
  pkg/plugins/policies/meshtimeout/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshtimeout/plugin/xds/configurer.go
Labels: release-2.9

#12693 fix(watchdog): wait for the first tick
  pkg/util/watchdog/watchdog_test.go
Labels: ci/skip-e2e-test

#12783 feat(kuma-cp): inbound name should be taken from pod instead of service
  pkg/plugins/runtime/k8s/controllers/inbound_converter.go
  pkg/plugins/runtime/k8s/controllers/pod_controller_test.go
  pkg/plugins/runtime/k8s/controllers/testdata/01.dataplane.yaml
  pkg/plugins/runtime/k8s/util/util.go
  pkg/plugins/runtime/k8s/util/util_test.go
Labels: ci/run-full-matrix

#12826 test(e2e): fix calico installation
  mk/k3d.mk
Labels: ci/run-full-matrix

#12827 test(unit): use eventually for watchdog channel check
  pkg/util/watchdog/watchdog_test.go
Labels: ci/skip-e2e-test

#12832 fix(xds): only auth once per xds gRPC stream in kuma-cp (backport of #12788)
  pkg/xds/auth/callbacks.go
  pkg/xds/auth/k8s/authenticator.go
  test/e2e_env/universal/auth/dp_auth.go
Labels: release-2.9

#12841 fix(xds): only auth once per xds gRPC stream in kuma-cp (backport of #12788)
  pkg/xds/auth/callbacks.go
  pkg/xds/auth/k8s/authenticator.go
  test/e2e_env/universal/auth/dp_auth.go
Labels: release-2.8

#12854 ci(lint): fix the linter by fixing the build
  pkg/plugins/policies/meshaccesslog/api/v1alpha1/deprecated.go
  pkg/plugins/policies/meshcircuitbreaker/api/v1alpha1/deprecated.go
  pkg/plugins/policies/meshratelimit/api/v1alpha1/deprecated.go
  pkg/plugins/policies/meshtimeout/api/v1alpha1/deprecated.go
  pkg/plugins/policies/meshtls/api/v1alpha1/deprecated.go
Labels: ci/skip-test

#12855 fix(kds): add all valid resources and skip only not valid (backport #12776)
  pkg/core/resources/model/resource.go
  pkg/kds/v2/client/kds_client.go
  pkg/kds/v2/client/stream.go
  pkg/kds/v2/store/sync.go
  pkg/kds/v2/store/sync_test.go
  pkg/util/xds/logging_callbacks.go
Labels: release-2.9

#12859 fix(merging): fix merging pointers to slices of struct
  pkg/plugins/policies/core/rules/merge/merge.go
  pkg/plugins/policies/core/rules/merge/merge_test.go
Labels: ci/skip-e2e-test

#12857 fix(kds): add all valid resources and skip only not valid (backport #12776)
  pkg/core/resources/model/resource.go
  pkg/kds/v2/client/kds_client.go
  pkg/kds/v2/client/stream.go
  pkg/kds/v2/store/sync.go
  pkg/kds/v2/store/sync_test.go
  pkg/util/xds/logging_callbacks.go
Labels: release-2.7

#12856 fix(kds): add all valid resources and skip only not valid (backport #12776)
  pkg/core/resources/model/resource.go
  pkg/kds/v2/client/kds_client.go
  pkg/kds/v2/client/stream.go
  pkg/kds/v2/store/sync.go
  pkg/kds/v2/store/sync_test.go
  pkg/util/xds/logging_callbacks.go
Labels: release-2.8

#12862 feat(kumactl): update install observability components
  app/kumactl/cmd/install/testdata/install-observability.defaults.golden.yaml
  app/kumactl/cmd/install/testdata/install-observability.no-grafana.golden.yaml
  app/kumactl/cmd/install/testdata/install-observability.no-jaeger.golden.yaml
  app/kumactl/cmd/install/testdata/install-observability.no-loki.golden.yaml
  app/kumactl/cmd/install/testdata/install-observability.no-prometheus.golden.yaml
  app/kumactl/cmd/install/testdata/install-observability.overrides.golden.yaml
  app/kumactl/data/install/k8s/logging/loki/loki.yaml
  app/kumactl/data/install/k8s/metrics/prometheus/kube-stats-metrics.yaml
  app/kumactl/data/install/k8s/metrics/prometheus/server.yaml
Labels: area/observability

#12897 chore(gha): added a workflow to trigger build on master branch
  .github/workflows/ci-stability-master.yaml
  .github/workflows/ci-stability.yaml
Labels: ci/skip-test, ci/skip-e2e-test

#12898 chore(helm): fix CNI tolerations
  app/kumactl/cmd/install/testdata/install-control-plane.dump-values.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/fix12847.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/fix12847.values.yaml
  deployments/charts/kuma/README.md
  deployments/charts/kuma/templates/cni-daemonset.yaml
  deployments/charts/kuma/values.yaml
  docs/generated/raw/helm-values.yaml
Labels: ci/skip-e2e-test

#12842 fix(xds): only auth once per xds gRPC stream in kuma-cp (backport of #12788)
  pkg/xds/auth/callbacks.go
  pkg/xds/auth/k8s/authenticator.go
  test/e2e_env/universal/auth/dp_auth.go
Labels: release-2.7

#12828 docs(upgrade.md): add doc for dataplane token revocation changes on Universal
  UPGRADE.md
Labels: ci/skip-test

#12915 chore(lint): fix api lint path
  mk/check.mk
Labels: ci/skip-test

#12936 fix(oapi): fix default in size query parameter
  api/mesh/v1alpha1/mesh/rest.yaml
  api/mesh/v1alpha1/meshgateway/rest.yaml
  docs/generated/openapi.yaml
  pkg/core/resources/apis/hostnamegenerator/api/v1alpha1/rest.yaml
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/rest.yaml
  pkg/core/resources/apis/meshmultizoneservice/api/v1alpha1/rest.yaml
  pkg/core/resources/apis/meshservice/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshaccesslog/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshcircuitbreaker/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshfaultinjection/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshhealthcheck/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshhttproute/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshloadbalancingstrategy/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshmetric/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshpassthrough/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshproxypatch/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshratelimit/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshretry/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtcproute/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtimeout/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtls/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtrace/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtrafficpermission/api/v1alpha1/rest.yaml
  tools/openapi/templates/endpoints.yaml
Labels: ci/skip-e2e-test

#12921 fix(kuma-cp): clone labels (backport #12908)
  pkg/core/resources/model/resource.go
Labels: release-2.9

#12941 fix(kuma-dp): prevent watchers from being cleaned up unexpectedly (backport of #12886)
  pkg/xds/server/callbacks/dataplane_callbacks.go
  pkg/xds/server/callbacks/dataplane_callbacks_test.go
  pkg/xds/server/callbacks/dataplane_lifecycle.go
  pkg/xds/server/callbacks/dataplane_metadata_tracker.go
  pkg/xds/server/callbacks/dataplane_sync_tracker.go
  pkg/xds/server/callbacks/dataplane_sync_tracker_test.go
Labels: release-2.9

#12932 test(unit): increase unit test timeout
  .github/workflows/_test.yaml
Labels: ci/skip-e2e-test

#12966 fix(kuma-dp): prevent watchers from being cleaned up unexpectedly (backport of #12886)
  pkg/xds/server/callbacks/dataplane_callbacks.go
  pkg/xds/server/callbacks/dataplane_callbacks_test.go
  pkg/xds/server/callbacks/dataplane_lifecycle.go
  pkg/xds/server/callbacks/dataplane_metadata_tracker.go
  pkg/xds/server/callbacks/dataplane_sync_tracker.go
  pkg/xds/server/callbacks/dataplane_sync_tracker_test.go
Labels: release-2.7

#12965 fix(kuma-dp): prevent watchers from being cleaned up unexpectedly (backport of #12886)
  pkg/xds/server/callbacks/dataplane_callbacks.go
  pkg/xds/server/callbacks/dataplane_callbacks_test.go
  pkg/xds/server/callbacks/dataplane_lifecycle.go
  pkg/xds/server/callbacks/dataplane_metadata_tracker.go
  pkg/xds/server/callbacks/dataplane_sync_tracker.go
  pkg/xds/server/callbacks/dataplane_sync_tracker_test.go
Labels: release-2.8

#12968 chore(deps): bump golangci-lint to v1.60.3 (backport of #11362)
  .github/workflows/build-test-distribute.yaml
  .golangci.yml
  app/kumactl/cmd/get/get_resources.go
  mk/dependencies/deps.lock
  mk/dev.mk
  pkg/transparentproxy/ebpf/programs/amd64/programs.go
  pkg/transparentproxy/ebpf/programs/arm64/programs.go
  test/framework/kumactl/kumactl.go
  test/framework/setup.go
  test/framework/universal_app.go
Labels: release-2.7

#12970 test(unit): check correctly active watchdogs (backport of #12948)
  pkg/xds/server/callbacks/dataplane_sync_tracker_test.go
Labels: ci/skip-test, release-2.7

#12971 test(unit): check correctly active watchdogs (backport of #12948)
  pkg/xds/server/callbacks/dataplane_sync_tracker_test.go
Labels: ci/skip-test, release-2.8

#12972 test(unit): check correctly active watchdogs (backport of #12948)
  pkg/xds/server/callbacks/dataplane_sync_tracker_test.go
Labels: ci/skip-test, release-2.9

#12960 test(e2e): use manifest instead of operator to install calico
  mk/k3d.mk
Labels: ci/run-full-matrix
