Repository kumahq/kuma, pull requests merged in 2025-08, with the labels that each got.

#14111 feat(kuma-cp): update golden files for proxyResourceName
  pkg/api-server/testdata/resources/inspect/dataplanes/_layout/empty_reachable_backend.golden.json
  pkg/api-server/testdata/resources/inspect/dataplanes/_layout/missing_reachable_backend.golden.json
  pkg/api-server/testdata/resources/inspect/dataplanes/_layout/multiple_mixed_destinations.golden.json
  pkg/api-server/testdata/resources/inspect/dataplanes/_layout/multiple_ms_destinations.golden.json
  pkg/api-server/testdata/resources/inspect/dataplanes/_layout/multiple_ms_destinations_reachable_backend.golden.json
  pkg/api-server/testdata/resources/inspect/dataplanes/_layout/single_dp.golden.json
  pkg/api-server/testdata/resources/inspect/dataplanes/_layout/single_ms_destination.golden.json
Labels: ci/skip-e2e-test

#14103 ci(linter): fix linter not going through all properties
  api/common/v1alpha1/header.go
  api/common/v1alpha1/jsonpatch.go
  api/common/v1alpha1/targetref.go
  mk/generate.mk
  pkg/core/resources/apis/hostnamegenerator/api/v1alpha1/hostnamegenerator.go
  pkg/plugins/policies/meshproxypatch/api/v1alpha1/meshproxypatch.go
  tools/ci/api-linter/linter/api-linter.go
  tools/ci/api-linter/linter/testdata/src/invalid_mergeable/testpolicy.go
  tools/ci/api-linter/linter/testdata/src/valid/testpolicy.go
  tools/ci/api-linter/main.go
Labels: ci/skip-e2e-test

#14112 fix(helm): properly set addresses when a list is provided
  app/kumactl/cmd/install/testdata/install-cp-helm/ingressLbService.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/ingressLbService.values.yaml
  deployments/charts/kuma/templates/ingress-service.yaml
Labels: ci/skip-e2e-test

#14139 chore(deps/dev): bump hadolint to 2.12.1-beta to fix macOS crash
  mise.toml
Labels: ci/skip-test

#14140 chore(mise): adjust make targets and gha after migration to mise
  .github/workflows/helm-release.yaml
  mk/dev.mk
  mk/k3d.mk
Labels: ci/skip-test

#14158 ci(container-structure-tests): add missing platform flag
  mk/test-container-structure.mk
Labels: ci/skip-test

#14128 refactor(KRI): replace `*kri.Identifier` with value-based identifiers in policy logic
  pkg/api-server/dataplane_layout_endpoint.go
  pkg/api-server/resource_endpoints.go
  pkg/core/kri/kri.go
  pkg/core/resources/apis/core/destinationname/destinationname.go
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/helpers.go
  pkg/core/resources/apis/meshmultizoneservice/api/v1alpha1/helpers.go
  pkg/core/resources/apis/meshmultizoneservice/status_updater.go
  pkg/core/resources/apis/meshservice/api/v1alpha1/helpers.go
  pkg/core/xds/resource.go
  pkg/core/xds/types.go
  pkg/core/xds/types/outbound.go
  pkg/kds/context/context.go
  pkg/plugins/policies/core/matchers/dataplane.go
  pkg/plugins/policies/core/rules/outbound/context.go
  pkg/plugins/policies/core/rules/outbound/context_test.go
  pkg/plugins/policies/core/rules/outbound/resourcerules.go
  pkg/plugins/policies/core/rules/resolve/backendref.go
  pkg/plugins/policies/core/rules/resolve/targetref.go
  pkg/plugins/policies/core/xds/meshroute/clusters.go
  pkg/plugins/policies/core/xds/meshroute/endpoints.go
  pkg/plugins/policies/core/xds/meshroute/listeners.go
  pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/plugin_test.go
  pkg/plugins/policies/meshcircuitbreaker/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshcircuitbreaker/plugin/v1alpha1/plugin_test.go
  pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/gateway_routes.go
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/listeners.go
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/plugin_test.go
  pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/plugin_test.go
  pkg/plugins/policies/meshmetric/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshretry/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshretry/plugin/v1alpha1/plugin_test.go
  pkg/plugins/policies/meshtcproute/plugin/v1alpha1/gateway.go
  pkg/plugins/policies/meshtcproute/plugin/v1alpha1/listeners_backendrefs.go
  pkg/plugins/policies/meshtcproute/plugin/v1alpha1/plugin_test.go
  pkg/plugins/policies/meshtimeout/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshtimeout/plugin/v1alpha1/plugin_test.go
  pkg/plugins/policies/meshtls/plugin/v1alpha1/plugin_test.go
  pkg/plugins/policies/meshtrace/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshtrace/plugin/v1alpha1/plugin_test.go
  pkg/plugins/policies/meshtrafficpermission/graph/backends/reachable_backend_refs_graph.go
  pkg/plugins/policies/meshtrafficpermission/graph/reachable_backend_refs_graph_test.go
  pkg/xds/context/context.go
  pkg/xds/context/destination_index.go
  pkg/xds/context/resources.go
  pkg/xds/generator/zoneproxy/destinations.go
  pkg/xds/sync/dataplane_proxy_builder.go
  pkg/xds/topology/outbound.go
  pkg/xds/topology/outbound_test.go
Labels: ci/run-full-matrix

#14160 feat(xds): support unified naming in for MeshHTTPRoute and MeshTCPRoute
  pkg/api-server/dataplane_layout_endpoint.go
  pkg/api-server/testdata/resources/inspect/dataplanes/_layout/multiple_mixed_destinations.golden.json
  pkg/api-server/testdata/resources/inspect/dataplanes/_layout/multiple_ms_destinations.golden.json
  pkg/api-server/testdata/resources/inspect/dataplanes/_layout/multiple_ms_destinations_reachable_backend.golden.json
  pkg/api-server/testdata/resources/inspect/dataplanes/_layout/single_ms_destination.golden.json
  pkg/api-server/testdata/resources/inspect/dataplanes/_layout/single_universal_outbound.golden.json
  pkg/api-server/testdata/resources/inspect/dataplanes/_layout/single_universal_outbound_with_labels.golden.json
  pkg/plugins/policies/core/xds/meshroute/listeners.go
  pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/plugin_test.go
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/listeners.go
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/plugin_test.go
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/basic-real-meshservice-and-mzms-labels-unified-naming.clusters.golden.yaml
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/basic-real-meshservice-and-mzms-labels-unified-naming.endpoints.golden.yaml
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/basic-real-meshservice-and-mzms-labels-unified-naming.listeners.golden.yaml
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/basic-real-meshservice-and-mzms-labels-unified-naming.routes.golden.yaml
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/basic-real-meshservice-and-mzms-labels-unified-naming.secrets.golden.yaml
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/default-meshservice-unified-naming.clusters.golden.yaml
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/default-meshservice-unified-naming.endpoints.golden.yaml
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/default-meshservice-unified-naming.listeners.golden.yaml
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/default-meshservice-unified-naming.routes.golden.yaml
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/default-meshservice-unified-naming.secrets.golden.yaml
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/meshexternalservice-with-tls-and-custom-settings-unified-naming.clusters.golden.yaml
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/meshexternalservice-with-tls-and-custom-settings-unified-naming.endpoints.golden.yaml
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/meshexternalservice-with-tls-and-custom-settings-unified-naming.listeners.golden.yaml
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/meshexternalservice-with-tls-and-custom-settings-unified-naming.routes.golden.yaml
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/meshexternalservice-with-tls-and-custom-settings-unified-naming.secrets.golden.yaml
  pkg/plugins/policies/meshtcproute/plugin/v1alpha1/gateway.go
  pkg/plugins/policies/meshtcproute/plugin/v1alpha1/listeners.go
  pkg/plugins/policies/meshtcproute/plugin/v1alpha1/listeners_backendrefs.go
Labels: ci/run-full-matrix

#14152 feat(api): add method to read DataSource on control-plane
  api/common/v1alpha1/datasource/datasource.go
Labels: ci/skip-test, ci/skip-e2e-test

#14198 Revert "chore(deps): bump actions/create-github-app-token from v2.0.6 to v2.1.0"
  .github/workflows/_build_publish.yaml
  .github/workflows/auto-merge.yaml
  .github/workflows/ci-stability.yaml
  .github/workflows/merge-release-to-master.yaml
  .github/workflows/pr-comments.yaml
  .github/workflows/release.yaml
  .github/workflows/update-docs.yaml
  .github/workflows/update-insecure-dependencies.yaml
Labels: ci/skip-test

#14204 chore(helm): add v prefix to the kubectl image tag for consistency
  app/kumactl/cmd/install/testdata/install-control-plane.dump-values.yaml
  deployments/charts/kuma/README.md
  deployments/charts/kuma/values.yaml
  docs/generated/raw/helm-values.yaml
Labels: ci/skip-test, master

#14203 chore(helm): switch kubectl image to rancher and bump patch
  app/kumactl/cmd/install/testdata/install-control-plane.dump-values.yaml
  deployments/charts/kuma/README.md
  deployments/charts/kuma/values.yaml
  docs/generated/raw/helm-values.yaml
Labels: release-2.7

#14201 chore(helm): switch kubectl image to rancher and bump patch
  app/kumactl/cmd/install/testdata/install-control-plane.dump-values.yaml
  deployments/charts/kuma/README.md
  deployments/charts/kuma/values.yaml
  docs/generated/raw/helm-values.yaml
Labels: release-2.10

#14202 chore(helm): switch kubectl image to rancher and bump patch
  app/kumactl/cmd/install/testdata/install-control-plane.dump-values.yaml
  deployments/charts/kuma/README.md
  deployments/charts/kuma/values.yaml
  docs/generated/raw/helm-values.yaml
Labels: release-2.9

#14199 feat(kuma-cp): fix missing unified naming for secret resources
  pkg/plugins/policies/core/xds/meshroute/clusters.go
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/basic-real-meshservice-and-mzms-labels-unified-naming.clusters.golden.yaml
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/default-meshservice-unified-naming.clusters.golden.yaml
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/testdata/meshexternalservice-with-tls-and-custom-settings-unified-naming.clusters.golden.yaml
  pkg/plugins/policies/meshtrafficpermission/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshtrafficpermission/plugin/v1alpha1/plugin_test.go
  pkg/plugins/runtime/gateway/cluster_generator.go
  pkg/plugins/runtime/gateway/filter_chain_generator.go
  pkg/xds/envoy/clusters/configurers.go
  pkg/xds/envoy/listeners/filter_chain_configurers.go
  pkg/xds/envoy/listeners/v3/server_mtls_configurer.go
  pkg/xds/envoy/listeners/v3/server_mtls_configurer_test.go
  pkg/xds/envoy/tls/v3/tls.go
  pkg/xds/envoy/tls/v3/tls_test.go
  pkg/xds/generator/egress/external_services_generator.go
  pkg/xds/generator/inbound_proxy_generator.go
  pkg/xds/generator/outbound_proxy_generator.go
  pkg/xds/generator/prometheus_endpoint_generator.go
  pkg/xds/generator/testdata/profile-source/5-envoy-config.golden.yaml
Labels: ci/run-full-matrix

#14205 fix(kuma-cp): initialiaze map if it's nil
  pkg/plugins/policies/meshtrafficpermission/graph/backends/reachable_backend_refs_graph.go
  pkg/plugins/policies/meshtrafficpermission/graph/services/reachable_services_graph.go
Labels: backport

#14079 chore(deps): bump envoy from v1.31.10 to v1.32.9
  mk/dev.mk
Labels: dependencies, release-2.7

#14211 test(transparentproxy): changed back to %s since %q doesn't work
  test/transparentproxy/transparentproxy_test.go
Labels: ci/skip-test, ci/skip-e2e-test

#14023 docs(CONTRIBUTING.md): update backport instructions
  CONTRIBUTING.md
Labels: kind/docs, ci/skip-test

#14226 chore(deps): bump openapi-tool to v1.1.6
  docs/generated/openapi.yaml
  mk/docs.mk
Labels: ci/skip-test

#14227 chore(deps): automatically bump openapi-tool when a new release is out
  mk/docs.mk
Labels: ci/skip-test

#14225 chore(oapi): get rid of duplicated entry
  api/openapi/specs/api.yaml
  api/openapi/types/zz_generated.api.go
  docs/generated/openapi.yaml
Labels: ci/skip-test

#14262 refactor(xds): rework outbound route API, add SNI, helpers
  pkg/core/naming/contextual.go
  pkg/core/naming/naming.go
  pkg/core/naming/naming_test.go
  pkg/plugins/policies/core/xds/cluster.go
  pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/plugin_test.go
  pkg/xds/envoy/clusters/cluster_builder.go
  pkg/xds/envoy/listeners/filter_chain_builder.go
  pkg/xds/envoy/listeners/filter_chain_configurers.go
  pkg/xds/envoy/listeners/v3/http_outbound_route_configurer.go
  pkg/xds/envoy/listeners/v3/http_outbound_route_configurer_test.go
  pkg/xds/envoy/listeners/v3/http_route_configurer.go
  pkg/xds/envoy/listeners/v3/util.go
  pkg/xds/envoy/routes/v3/retry_configurer_test.go
  pkg/xds/envoy/types.go
  pkg/xds/envoy/virtualhosts/routes_configurer.go
  pkg/xds/generator/egress/external_services_generator.go
  pkg/xds/generator/egress/internal_services_generator.go
  pkg/xds/generator/outbound_proxy_generator.go
Labels: ci/run-full-matrix

#14280 feat(kuma-cp): support unified naming in zone proxies
  api/common/v1alpha1/targetref.go
  pkg/api-server/testdata/resources/inspect/dataplanes/_layout/multiple_mixed_destinations.golden.json
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/helpers.go
  pkg/plugins/policies/core/rules/outbound/resourcerules.go
  pkg/plugins/policies/core/rules/resolve/backendref.go
  pkg/xds/generator/egress/external_services_generator.go
  pkg/xds/generator/egress/generator.go
  pkg/xds/generator/egress/generator_test.go
  pkg/xds/generator/egress/internal_services_generator.go
  pkg/xds/generator/egress/testdata/04.mixed-services-custom-trafficroute.golden.yaml
  pkg/xds/generator/egress/testdata/06.mixed-services-with-external-in-other-zone.golden.yaml
  pkg/xds/generator/ingress_generator.go
  pkg/xds/generator/proxy_template.go
  pkg/xds/generator/secrets/generator.go
  pkg/xds/generator/testdata/ingress/mesh-service.envoy.golden.yaml
  pkg/xds/generator/zoneproxy/generator.go
Labels: ci/run-full-matrix

#14300 feat(helm): switch kubectl image to `registry.k8s.io`
  app/kumactl/cmd/install/testdata/install-control-plane.dump-values.yaml
  deployments/charts/kuma/README.md
  deployments/charts/kuma/values.yaml
  docs/generated/raw/helm-values.yaml
Labels: ci/run-full-matrix, release-2.9

#14317 chore(kuma-cp): add helper to check if unified naming enabled
  pkg/core/naming/unified-naming/unified_naming.go
Labels: ci/skip-test

#14321 chore(xds): mesh-aware (meshServices mode) unified naming switch in user resources
  pkg/plugins/policies/core/xds/meshroute/clusters.go
  pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/plugin_test.go
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/listeners.go
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/plugin_test.go
  pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/plugin_test.go
  pkg/plugins/policies/meshpassthrough/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshtcproute/plugin/v1alpha1/listeners.go
  pkg/plugins/policies/meshtls/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshtrafficpermission/plugin/v1alpha1/plugin.go
  pkg/plugins/runtime/gateway/cluster_generator.go
  pkg/xds/generator/egress/external_services_generator.go
  pkg/xds/generator/egress/generator.go
  pkg/xds/generator/egress/internal_services_generator.go
  pkg/xds/generator/inbound_proxy_generator.go
  pkg/xds/generator/inbound_proxy_generator_test.go
  pkg/xds/generator/ingress_generator.go
  pkg/xds/generator/outbound_proxy_generator.go
  pkg/xds/generator/prometheus_endpoint_generator.go
  pkg/xds/generator/proxy_template_profile_source_test.go
  pkg/xds/generator/transparent_proxy_generator.go
  pkg/xds/generator/transparent_proxy_generator_test.go
  pkg/xds/generator/zoneproxy/generator.go
Labels: ci/run-full-matrix

#14337 ci(helm): revert helm-cr bump from v1.3.0 to v1.7.0
  mise.toml
Labels: release-2.10

#14336 ci(helm): revert helm-cr bump from v1.3.0 to v1.7.0
  mise.toml
Labels: release-2.7

#14355 feat(kuma-cp): add validation on resourceType
  tools/policy-gen/generator/cmd/core_resource.go
Labels: ci/skip-test

#14361 test(framework): migrate to `portforward` API and add `ConfigDump` support
  test/e2e_env/kubernetes/meshidentity/spire.go
  test/e2e_env/multizone/meshservice/policies.go
  test/e2e_env/multizone/meshtimeout/meshtimeout.go
  test/framework/envoy_admin/config_dump/config_dump.go
  test/framework/envoy_admin/interface.go
  test/framework/envoy_admin/tunnel/k8s.go
  test/framework/envoy_admin/tunnel/universal.go
  test/framework/envs/kubernetes/env.go
  test/framework/envs/multizone/env.go
  test/framework/k8s_cluster.go
  test/framework/k8s_controlplane.go
  test/framework/portforward/portforward.go
Labels: ci/run-full-matrix

#14363 feat(kuma-cp): rename access log sink system resource to follow unified naming format
  pkg/xds/bootstrap/generator.go
  pkg/xds/bootstrap/generator_test.go
  pkg/xds/bootstrap/template_v3.go
  pkg/xds/bootstrap/template_v3_test.go
  pkg/xds/bootstrap/testdata/generator.custom-config-minimal-request-with-unified-resource-naming-feature-flag.golden.yaml
Labels: ci/run-full-matrix
