Repository kumahq/kuma, pull requests merged in 2025-01, with the labels that each got.

#12402 chore(deps): bump kind from 0.11.1 to 0.24.0
  mk/dependencies/deps.lock
  mk/dependencies/kind.sh
Labels: ci/run-full-matrix

#12424 ci(github): use `on.push` to notify about updates
  .github/workflows/pr-merged.yaml
Labels: ci/skip-test

#12423 ci(github): remove backport and checklist comment
  .github/workflows/backport.yaml
  .github/workflows/check.yaml
  .github/workflows/pr-modification.yaml
Labels: ci/skip-test

#12442 ci(.github): remove unecessary workflow file from release-2.5
  .github/workflows/pr-merged.yaml
Labels: ci/skip-test

#12441 ci(.github): remove unecessary workflow file from release-2.4
  .github/workflows/pr-merged.yaml
Labels: ci/skip-test

#12443 ci(.github): remove unecessary workflow file from release-2.3
  .github/workflows/pr-merged.yaml
Labels: ci/skip-test

#12440 ci(.github): remove unecessary workflow file from release-2.2
  .github/workflows/pr-merged.yaml
Labels: ci/skip-test

#12433 ci(.github): remove unecessary workflow file from release-1.4
  .github/workflows/pr-merged.yaml
Labels: ci/skip-test

#12439 ci(.github): remove unecessary workflow file from release-2.1
  .github/workflows/pr-merged.yaml
Labels: ci/skip-test

#12438 ci(.github): remove unecessary workflow file from release-2.0
  .github/workflows/pr-merged.yaml
Labels: ci/skip-test

#12437 ci(.github): remove unecessary workflow file from release-1.8
  .github/workflows/pr-merged.yaml
Labels: ci/skip-test

#12436 ci(.github): remove unecessary workflow file from release-1.7
  .github/workflows/pr-merged.yaml
Labels: ci/skip-test

#12435 ci(.github): remove unecessary workflow file from release-1.6
  .github/workflows/pr-merged.yaml
Labels: ci/skip-test

#12434 ci(.github): remove unecessary workflow file from release-1.5
  .github/workflows/pr-merged.yaml
Labels: ci/skip-test

#12446 ci(github): use on.push to notify about updates (backport of #12424)
  .github/workflows/pr-merged.yaml
Labels: ci/skip-test

#12447 ci(github): use on.push to notify about updates (backport of #12424)
  .github/workflows/pr-merged.yaml
Labels: ci/skip-test

#12445 ci(github): use on.push to notify about updates (backport of #12424)
  .github/workflows/pr-merged.yaml
Labels: ci/skip-test

#12449 ci(github): fix PR comment action
  .github/workflows/pr-modification.yaml
Labels: ci/skip-test

#12451 Revert "chore(sync): sync errors schema"
  api/openapi/specs/api.yaml
  api/openapi/specs/common/error_schema.yaml
  docs/generated/openapi.yaml
Labels: ci/skip-test

#12456 chore(oapi): move global inisight schema to separate object
  api/openapi/specs/api.yaml
  api/openapi/types/zz_generated.api.go
  docs/generated/openapi.yaml
Labels: ci/skip-test

#12454 chore(deps): upgrade envoy from v1.29.11 to v1.29.12
  tools/releases/version.sh
Labels: release-2.6

#12459 chore(deps): pin distroless-iptables image
  tools/releases/dockerfiles/kuma-init.Dockerfile
Labels: ci/skip-e2e-test

#12460 chore(deps): upgrade envoy to v1.30.9
  mk/dependencies/deps.lock
  mk/dev.mk
Labels: release-2.8

#12455 chore(deps): upgrade envoy from v1.29.11 to v1.29.12
  mk/dependencies/deps.lock
  mk/dev.mk
Labels: release-2.7

#12467 chore(oapi): rename resources to responses
  api/openapi/specs/api.yaml
  docs/generated/openapi.yaml
Labels: ci/skip-test

#12468 ci(github): use include in pr-modification.yaml
  .github/workflows/pr-modification.yaml
Labels: ci/skip-test

#12466 ci(security): resolve security alerts
  .github/workflows/_e2e.yaml
  .github/workflows/ci-stability.yaml
  .github/workflows/codeql.yaml
  .github/workflows/scorecard.yml
  mk/dependencies/deps.lock
  mk/dependencies/golangci-lint.sh
  mk/dependencies/helm.sh
  mk/dependencies/k3d.sh
Labels: ci/skip-test

#12471 chore(oapi): rename InternalServerError to Internal
  api/openapi/specs/api.yaml
  api/openapi/types/zz_generated.api.go
  docs/generated/openapi.yaml
Labels: ci/skip-test

#12472 chore(deps): bump coredns from v1.11.4 to v1.12.0
  mk/build.mk
Labels: master

#12473 chore(deps): bump coredns from v1.11.3 to v1.12.0
  mk/build.mk
Labels: release-2.9

#12474 chore(deps): bump coredns from v1.11.3 to v1.12.0
  mk/build.mk
Labels: release-2.8

#12476 chore(deps): bump coredns from v1.11.3 to v1.12.0
  mk/build.mk
Labels: release-2.6

#12475 chore(deps): bump coredns from v1.11.3 to v1.12.0
  mk/build.mk
Labels: release-2.7

#12477 ci(gha): reduce permissions in workflows based on scorecard alerts
  .github/workflows/_build_publish.yaml
  .github/workflows/_provenance.yaml
  .github/workflows/build-test-distribute.yaml
  .github/workflows/ci-stability.yaml
Labels: area/ci-cd, ci/skip-test, ci/force-publish

#12480 ci(gha): add back contents: read permission to check job
  .github/workflows/build-test-distribute.yaml
Labels: area/ci-cd, ci/skip-test

#12483 ci(hadolint): make hadolint fail if there aren't any dockerfiles found
  mk/check.mk
Labels: ci/skip-test

#12478 chore(gha): add read pull requests permissions
  .github/workflows/pr-modification.yaml
Labels: ci/skip-test, ci/skip-e2e-test

#12485 chore(deps): upgrade actions/cache from v4.1.0 to v4.2.0
  .github/workflows/_build_publish.yaml
  .github/workflows/_e2e.yaml
  .github/workflows/_test.yaml
  .github/workflows/build-test-distribute.yaml
  .github/workflows/helm-release.yaml
  .github/workflows/pr-comments.yaml
  .github/workflows/transparentproxy-tests.yaml
Labels: ci/skip-test, ci/skip-e2e-test, backport, release-2.9

#12491 ci(check): fix hadolint make target
  mk/check.mk
Labels: ci/skip-test

#12492 ci(security): resolve security alerts from scorecard
  .github/workflows/_build_publish.yaml
  .github/workflows/_e2e.yaml
  .github/workflows/_provenance.yaml
  .github/workflows/build-test-distribute.yaml
  .github/workflows/ci-stability.yaml
  .github/workflows/codeql.yaml
  .github/workflows/scorecard.yml
  mk/dependencies/deps.lock
  mk/dependencies/golangci-lint.sh
  mk/dependencies/helm.sh
  mk/dependencies/k3d.sh
Labels: area/ci-cd, release-2.9

#12495 ci(security): resolve security alerts from scorecard
  .github/workflows/_build_publish.yaml
  .github/workflows/_e2e.yaml
  .github/workflows/_provenance.yaml
  .github/workflows/build-test-distribute.yaml
  .github/workflows/codeql.yaml
  .github/workflows/scorecard.yml
  mk/dependencies/deps.lock
  mk/dependencies/golangci-lint.sh
  mk/dependencies/helm.sh
  mk/dependencies/k3d.sh
Labels: area/ci-cd, ci/skip-test, release-2.7

#12494 ci(security): resolve security alerts from scorecard
  .github/workflows/_build_publish.yaml
  .github/workflows/_e2e.yaml
  .github/workflows/_provenance.yaml
  .github/workflows/build-test-distribute.yaml
  .github/workflows/codeql.yaml
  .github/workflows/scorecard.yml
  mk/dependencies/deps.lock
  mk/dependencies/golangci-lint.sh
  mk/dependencies/helm.sh
  mk/dependencies/k3d.sh
Labels: area/ci-cd, ci/skip-test, release-2.8

#12496 ci(security): resolve security alerts (backport #12466)
  .github/workflows/codeql.yaml
  .github/workflows/e2e.yaml
  .github/workflows/scorecard.yml
  mk/dependencies/deps.lock
  mk/dependencies/golangci-lint.sh
  mk/dependencies/helm.sh
  mk/dependencies/k3d.sh
Labels: area/ci-cd, release-2.6

#12489 test(framework): replace bitnami helm chart with oci one
  test/framework/deployments/postgres/kubernetes.go
Labels: ci/run-full-matrix, backport

#12340 fix(policy): use new compute for rules and fix rules intersect
  pkg/core/xds/inspect/rules.go
  pkg/plugins/policies/core/rules/rules.go
  pkg/plugins/policies/core/rules/rules_test.go
  pkg/plugins/policies/core/rules/testdata/rules/from/06.golden.yaml
  pkg/plugins/policies/core/rules/testdata/rules/from/06.input.yaml
  pkg/plugins/policies/core/rules/testdata/rules/from/07.golden.yaml
  pkg/plugins/policies/core/rules/testdata/rules/from/07.input.yaml
  pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshcircuitbreaker/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/listeners.go
  pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshproxypatch/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshratelimit/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshratelimit/plugin/xds/configurer.go
  pkg/plugins/policies/meshretry/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshretry/plugin/xds/configurer.go
  pkg/plugins/policies/meshtcproute/plugin/v1alpha1/listeners_backendrefs.go
  pkg/plugins/policies/meshtimeout/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshtimeout/plugin/xds/configurer.go
  pkg/plugins/policies/meshtls/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshtrafficpermission/graph/reachable_graph.go
Labels: ci/run-full-matrix

#12498 chore(action): move permissions to specific job
  .github/workflows/pr-modification.yaml
Labels: ci/skip-test, ci/skip-e2e-test

#12504 chore(action): set default permissions to none for pr-modification
  .github/workflows/pr-modification.yaml
Labels: ci/skip-test, ci/skip-e2e-test

#12501 test(framework): replace bitnami helm chart with oci one (backport #12489)
  test/framework/deployments/postgres/kubernetes.go
Labels: release-2.9

#12502 test(framework): replace bitnami helm chart with oci one (backport #12489)
  test/framework/deployments/postgres/kubernetes.go
Labels: release-2.8

#12505 test(framework): replace bitnami helm chart with oci one (backport #12489)
  test/framework/deployments/postgres/kubernetes.go
Labels: release-2.6

#12497 fix(oapi): add missing bits to fix validation errors in parent project
  api/mesh/v1alpha1/mesh.pb.go
  api/mesh/v1alpha1/mesh.proto
  api/mesh/v1alpha1/mesh/rest.yaml
  api/mesh/v1alpha1/meshgateway/rest.yaml
  api/openapi/specs/api.yaml
  api/openapi/specs/common/error_schema.yaml
  api/openapi/specs/common/jsonpatch.yaml
  api/openapi/specs/common/resource.yaml
  api/openapi/types/common/zz_generated.error_schema.go
  api/openapi/types/common/zz_generated.jsonpatch.go
  api/openapi/types/common/zz_generated.resource.go
  app/kumactl/cmd/install/testdata/install-control-plane.defaults.golden.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.gateway-api-present.yaml
  app/kumactl/cmd/install/testdata/install-control-plane.with-helm-set.yaml
  app/kumactl/cmd/install/testdata/install-crds.all.golden.yaml
  deployments/charts/kuma/crds/kuma.io_meshes.yaml
  docs/generated/openapi.yaml
  docs/generated/raw/crds/kuma.io_meshes.yaml
  pkg/core/resources/apis/hostnamegenerator/api/v1alpha1/rest.yaml
  pkg/core/resources/apis/mesh/zz_generated.resources.go
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/rest.yaml
  pkg/core/resources/apis/meshmultizoneservice/api/v1alpha1/rest.yaml
  pkg/core/resources/apis/meshservice/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshaccesslog/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshcircuitbreaker/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshfaultinjection/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshhealthcheck/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshhttproute/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshloadbalancingstrategy/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshmetric/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshpassthrough/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshproxypatch/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshratelimit/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshretry/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtcproute/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtimeout/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtls/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtrace/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtrafficpermission/api/v1alpha1/rest.yaml
  pkg/plugins/resources/k8s/native/api/v1alpha1/zz_generated.mesh.go
  tools/openapi/templates/endpoints.yaml
  tools/resource-gen/main.go
Labels: ci/skip-e2e-test

#12512 ci(github): add read content permissions to build-images
  .github/workflows/_build_publish.yaml
Labels: ci/skip-test

#12506 ci(gha): update codeql workflow to set checks during scheduled runs
  .github/workflows/codeql.yaml
Labels: area/ci-cd, ci/skip-test, backport

#12515 fix(policy): use new compute for rules and fix rules intersect (backport of #12340)
  pkg/core/xds/inspect/rules.go
  pkg/plugins/policies/core/rules/rules.go
  pkg/plugins/policies/core/rules/rules_test.go
  pkg/plugins/policies/core/rules/testdata/rules/from/06.golden.yaml
  pkg/plugins/policies/core/rules/testdata/rules/from/06.input.yaml
  pkg/plugins/policies/core/rules/testdata/rules/from/07.golden.yaml
  pkg/plugins/policies/core/rules/testdata/rules/from/07.input.yaml
  pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshcircuitbreaker/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/listeners.go
  pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshproxypatch/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshratelimit/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshratelimit/plugin/xds/configurer.go
  pkg/plugins/policies/meshretry/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshretry/plugin/xds/configurer.go
  pkg/plugins/policies/meshtcproute/plugin/v1alpha1/listeners_backendrefs.go
  pkg/plugins/policies/meshtimeout/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshtimeout/plugin/xds/configurer.go
  pkg/plugins/policies/meshtls/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshtrafficpermission/graph/reachable_graph.go
Labels: release-2.9

#12516 fix(policy): use new compute for rules and fix rules intersect (backport of #12340)
  pkg/core/xds/inspect/rules.go
  pkg/plugins/policies/core/rules/rules.go
  pkg/plugins/policies/core/rules/rules_test.go
  pkg/plugins/policies/core/rules/testdata/rules/from/06.golden.yaml
  pkg/plugins/policies/core/rules/testdata/rules/from/06.input.yaml
  pkg/plugins/policies/core/rules/testdata/rules/from/07.golden.yaml
  pkg/plugins/policies/core/rules/testdata/rules/from/07.input.yaml
  pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshcircuitbreaker/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/listeners.go
  pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshproxypatch/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshratelimit/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshratelimit/plugin/xds/configurer.go
  pkg/plugins/policies/meshretry/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshretry/plugin/xds/configurer.go
  pkg/plugins/policies/meshtcproute/plugin/v1alpha1/listeners_backendrefs.go
  pkg/plugins/policies/meshtimeout/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshtimeout/plugin/xds/configurer.go
  pkg/plugins/policies/meshtrafficpermission/graph/reachable_services_graph.go
Labels: release-2.8

#12517 fix(policy): use new compute for rules and fix rules intersect (backport of #12340)
  pkg/core/xds/inspect/rules.go
  pkg/plugins/policies/core/rules/rules.go
  pkg/plugins/policies/core/rules/rules_test.go
  pkg/plugins/policies/core/rules/testdata/rules/from/06.golden.yaml
  pkg/plugins/policies/core/rules/testdata/rules/from/06.input.yaml
  pkg/plugins/policies/core/rules/testdata/rules/from/07.golden.yaml
  pkg/plugins/policies/core/rules/testdata/rules/from/07.input.yaml
  pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshcircuitbreaker/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/listeners.go
  pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshproxypatch/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshratelimit/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshratelimit/plugin/xds/configurer.go
  pkg/plugins/policies/meshretry/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshretry/plugin/xds/configurer.go
  pkg/plugins/policies/meshtcproute/plugin/v1alpha1/listeners_backendrefs.go
  pkg/plugins/policies/meshtimeout/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshtimeout/plugin/xds/configurer.go
  pkg/plugins/policies/meshtrafficpermission/graph/reachable_services_graph.go
Labels: release-2.7

#12519 ci(gha): remove unnecessary permissions from check.yaml workflow
  .github/workflows/check.yaml
Labels: area/ci-cd, ci/skip-test

#12532 chore(images): add permissions for build-images
  .github/workflows/_build_publish.yaml
Labels: ci/skip-test, ci/skip-e2e-test, release-2.7

#12531 chore(images): add permissions for build-images
  .github/workflows/_build_publish.yaml
Labels: ci/skip-test, ci/skip-e2e-test, release-2.8

#12530 chore(images): add permissions for build-images
  .github/workflows/_build_publish.yaml
Labels: ci/skip-test, ci/skip-e2e-test, release-2.9

#12535 test(e2e): avoid name conflict and simplfy logic (backport #11524)
  test/e2e_env/kubernetes/externalservices/externalservices.go
  test/e2e_env/kubernetes/meshtcproute/test.go
Labels: release-2.7

#12534 test(e2e): avoid name conflict and simplfy logic (backport #11524)
  test/e2e_env/kubernetes/externalservices/externalservices.go
  test/e2e_env/kubernetes/meshtcproute/test.go
Labels: release-2.8

#12540 chore(deps): upgrade security-actions/sign-docker-image to v4.0.1
  .github/workflows/_build_publish.yaml
Labels: ci/skip-test, ci/skip-e2e-test

#12544 chore(deps): upgrade security-actions/sign-docker-image to v4.0.1
  .github/workflows/_build_publish.yaml
Labels: ci/skip-test, ci/skip-e2e-test, release-2.8

#12543 chore(deps): upgrade security-actions/sign-docker-image to v4.0.1
  .github/workflows/_build_publish.yaml
Labels: ci/skip-test, ci/skip-e2e-test, release-2.9

#12545 chore(deps): upgrade security-actions/sign-docker-image to v4.0.1
  .github/workflows/_build_publish.yaml
Labels: ci/skip-test, ci/skip-e2e-test, release-2.7

#12546 ci(renovate): add initial renovate.json configuration file
  renovate.json
Labels: area/ci-cd, ci/skip-test

#12552 ci(renovatae): set PR title semmantic type to be always "chore"
  renovate.json
Labels: area/ci-cd, ci/skip-test

#12554 chore(deps): upgrade release-tool from v1.0.0 to v1.1.0
  .github/workflows/release.yaml
Labels: ci/skip-test, ci/skip-e2e-test

#12562 chore(oapi): add x-speakeasy-entity-operation to all operations
  api/mesh/v1alpha1/mesh/rest.yaml
  api/mesh/v1alpha1/meshgateway/rest.yaml
  docs/generated/openapi.yaml
  pkg/core/resources/apis/hostnamegenerator/api/v1alpha1/rest.yaml
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/rest.yaml
  pkg/core/resources/apis/meshmultizoneservice/api/v1alpha1/rest.yaml
  pkg/core/resources/apis/meshservice/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshaccesslog/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshcircuitbreaker/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshfaultinjection/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshhealthcheck/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshhttproute/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshloadbalancingstrategy/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshmetric/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshpassthrough/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshproxypatch/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshratelimit/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshretry/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtcproute/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtimeout/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtls/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtrace/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtrafficpermission/api/v1alpha1/rest.yaml
  tools/openapi/templates/endpoints.yaml
Labels: ci/skip-test

#12563 ci(renovate): configure renovate so it can upgrade `Kong/public-shared-actions`
  renovate.json
  renovate.json5
Labels: area/ci-cd, ci/skip-test

#12565 fix(distributions): exclude group and passwd from packaged binaries
  mk/distribution.mk
Labels: ci/skip-test

#12568 Revert "chore(oapi): add x-speakeasy-entity-operation to all operations"
  api/mesh/v1alpha1/mesh/rest.yaml
  api/mesh/v1alpha1/meshgateway/rest.yaml
  docs/generated/openapi.yaml
  pkg/core/resources/apis/hostnamegenerator/api/v1alpha1/rest.yaml
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/rest.yaml
  pkg/core/resources/apis/meshmultizoneservice/api/v1alpha1/rest.yaml
  pkg/core/resources/apis/meshservice/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshaccesslog/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshcircuitbreaker/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshfaultinjection/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshhealthcheck/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshhttproute/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshloadbalancingstrategy/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshmetric/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshpassthrough/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshproxypatch/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshratelimit/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshretry/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtcproute/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtimeout/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtls/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtrace/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtrafficpermission/api/v1alpha1/rest.yaml
  tools/openapi/templates/endpoints.yaml
Labels: ci/skip-test

#12569 ci(renovate): fix config to properly update Kong/public-shared-actions versions
  .github/workflows/lifecycle.yml
  renovate.json5
Labels: area/ci-cd, ci/skip-test

#12572 ci(renovate): match by depType to skip tests for GitHub Actions updates
  renovate.json5
Labels: area/ci-cd, ci/skip-test

#12574 ci(renovate): support updates for public-shared-actions without digests
  renovate.json5
Labels: area/ci-cd, ci/skip-test

#12576 chore(oapi): update oapi tool
  docs/generated/openapi.yaml
  mk/docs.mk
Labels: ci/skip-test

#12578 chore(deps): bump golang from 1.22.10 to 1.22.11
  go.mod
Labels: release-2.6

#12580 chore(deps): bump golang from 1.22.10 to 1.22.11
  go.mod
Labels: release-2.8

#12581 chore(deps): bump golang from 1.23.4 to 1.23.5
  go.mod
Labels: release-2.9

#12585 test(e2e): disable flaking federation tests
  test/e2e/federation/federation_suite_test.go
Labels: area/ci-cd, ci/skip-test, kind/ci-flake

#12587 fix(k8s): always authenticate with latest service account token (backport #11399)
  pkg/config/dp-server/config.go
  pkg/xds/bootstrap/components.go
Labels: release-2.7

#12588 fix(k8s): always authenticate with latest service account token (backport #11399)
  pkg/config/dp-server/config.go
  pkg/xds/bootstrap/components.go
Labels: release-2.6

#12586 fix(k8s): always authenticate with latest service account token (backport #11399)
  pkg/config/dp-server/config.go
  pkg/xds/bootstrap/components.go
Labels: release-2.8

#12536 chore(k8s): validate kuma on k8s v1.30
  .github/workflows/_test.yaml
  mk/dependencies/deps.lock
  mk/dev.mk
Labels: ci/run-full-matrix, release-2.7

#12601 ci(gha): fix pr-modifications workflow to skip dependabot and renovate PRs
  .github/workflows/pr-modification.yaml
Labels: area/ci-cd, ci/skip-test

#12590 refactor(cni): cni installer logic refactoring
  app/cni/cmd/install/main.go
  app/cni/pkg/install/installer_config.go
  app/cni/pkg/install/installer_config_test.go
  app/cni/pkg/install/main.go
  app/cni/pkg/install/main_test.go
  app/cni/pkg/install/testdata/prepare-chained-kuma-config/10-calico.conflist
  app/cni/pkg/install/testdata/prepare-chained-kuma-config/10-calico.conflist.golden
  app/cni/pkg/install/testdata/prepare-standalone-kuma-config/kuma-cni.conf
  app/cni/pkg/install/testdata/prepare-standalone-kuma-config/kuma-cni.conf.golden
  app/cni/pkg/install/validation.go
  app/cni/pkg/install/validation_test.go
Labels: ci/run-full-matrix

#12602 Revert "chore(oapi): move CreateOrUpdateSuccessResponse under `components.responses`"
  api/mesh/v1alpha1/mesh/rest.yaml
  api/mesh/v1alpha1/meshgateway/rest.yaml
  docs/generated/openapi.yaml
  pkg/core/resources/apis/hostnamegenerator/api/v1alpha1/rest.yaml
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/rest.yaml
  pkg/core/resources/apis/meshmultizoneservice/api/v1alpha1/rest.yaml
  pkg/core/resources/apis/meshservice/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshaccesslog/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshcircuitbreaker/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshfaultinjection/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshhealthcheck/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshhttproute/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshloadbalancingstrategy/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshmetric/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshpassthrough/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshproxypatch/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshratelimit/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshretry/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtcproute/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtimeout/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtls/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtrace/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtrafficpermission/api/v1alpha1/rest.yaml
  tools/openapi/templates/endpoints.yaml
Labels: ci/skip-test

#12610 ci(renovate): enable dockerfile manager and clear ignorePaths
  renovate.json
Labels: area/ci-cd, ci/skip-test

#12623 fix(cni): support bound service account token by reloading periodically (backport of #12592)
  app/cni/pkg/install/installer_config.go
  app/cni/pkg/install/main.go
Labels: release-2.9

#12625 fix(cni): support bound service account token by reloading periodically (backport of #12592)
  app/cni/pkg/install/installer_config.go
  app/cni/pkg/install/main.go
Labels: release-2.7

#12631 ci(gha): remove reference link from reviewers checklist comment
  .github/workflows/pr-modification.yaml
Labels: area/ci-cd, ci/skip-test

#12636 ci(gha): exclude kumahq bot PRs from adding reviewer checklist comment
  .github/workflows/pr-modification.yaml
Labels: area/ci-cd, ci/skip-test

#12637 chore(cleanup): remove outdated tools/e2e/ directory
  tools/e2e/examples/docker-compose/README.md
  tools/e2e/examples/docker-compose/backend.yaml
  tools/e2e/examples/docker-compose/certs/README.md
  tools/e2e/examples/docker-compose/certs/client/cert.key
  tools/e2e/examples/docker-compose/certs/client/cert.pem
  tools/e2e/examples/docker-compose/certs/server/cert.pem
  tools/e2e/examples/docker-compose/certs/server/key.pem
  tools/e2e/examples/docker-compose/docker-compose.yaml
  tools/e2e/examples/docker-compose/kuma-example-installer.sh
  tools/e2e/examples/docker-compose/policies/everyone-to-everyone.traffic-permission.yaml
  tools/e2e/examples/docker-compose/policies/mtls.yaml
  tools/e2e/examples/docker-compose/policies/no-mtls.yaml
  tools/e2e/examples/docker-compose/policies/web-to-backend.traffic-route.yaml
Labels: kind/cleanup, ci/skip-test

#12639 chore(kumactl): upgrade grafana/loki to 3.3.2 in observability manifests
  app/kumactl/cmd/install/testdata/install-observability.defaults.golden.yaml
  app/kumactl/cmd/install/testdata/install-observability.no-grafana.golden.yaml
  app/kumactl/cmd/install/testdata/install-observability.no-jaeger.golden.yaml
  app/kumactl/cmd/install/testdata/install-observability.no-prometheus.golden.yaml
  app/kumactl/cmd/install/testdata/install-observability.overrides.golden.yaml
  app/kumactl/data/install/k8s/logging/loki/loki.yaml
Labels: area/observability

#12641 chore(kumactl): upgrade grafana/grafana to 11.4.0 in observability manifests
  app/kumactl/cmd/install/testdata/install-observability.defaults.golden.yaml
  app/kumactl/cmd/install/testdata/install-observability.no-jaeger.golden.yaml
  app/kumactl/cmd/install/testdata/install-observability.no-loki.golden.yaml
  app/kumactl/cmd/install/testdata/install-observability.no-prometheus.golden.yaml
  app/kumactl/cmd/install/testdata/install-observability.overrides.golden.yaml
  app/kumactl/data/install/k8s/metrics/grafana/grafana.yaml
Labels: area/observability

#12647 chore(kumactl): upgrade grafana/promtail to 3.3.2 in observability manifests
  app/kumactl/cmd/install/testdata/install-observability.defaults.golden.yaml
  app/kumactl/cmd/install/testdata/install-observability.no-grafana.golden.yaml
  app/kumactl/cmd/install/testdata/install-observability.no-jaeger.golden.yaml
  app/kumactl/cmd/install/testdata/install-observability.no-loki.golden.yaml
  app/kumactl/cmd/install/testdata/install-observability.no-prometheus.golden.yaml
  app/kumactl/cmd/install/testdata/install-observability.overrides.golden.yaml
  app/kumactl/data/install/k8s/logging/loki/loki.yaml
  app/kumactl/data/install/k8s/metrics/grafana/grafana.yaml
Labels: area/observability

#12654 chore(deps): upgrade go-control-plane to v0.13.4
  go.mod
  go.sum
  pkg/xds/envoy/imports.go
Labels: ci/run-full-matrix

#12665 feat(oapi): properly map proto types likes DoubleValue
  api/mesh/v1alpha1/mesh/schema.yaml
  docs/generated/openapi.yaml
  tools/resource-gen/main.go
Labels: ci/skip-e2e-test

#12666 feat(oapi): add a possible 404 to get on resources
  api/mesh/v1alpha1/mesh/rest.yaml
  api/mesh/v1alpha1/meshgateway/rest.yaml
  docs/generated/openapi.yaml
  pkg/core/resources/apis/hostnamegenerator/api/v1alpha1/rest.yaml
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/rest.yaml
  pkg/core/resources/apis/meshmultizoneservice/api/v1alpha1/rest.yaml
  pkg/core/resources/apis/meshservice/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshaccesslog/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshcircuitbreaker/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshfaultinjection/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshhealthcheck/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshhttproute/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshloadbalancingstrategy/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshmetric/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshpassthrough/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshproxypatch/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshratelimit/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshretry/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtcproute/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtimeout/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtls/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtrace/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtrafficpermission/api/v1alpha1/rest.yaml
  tools/openapi/templates/endpoints.yaml
Labels: ci/skip-e2e-test

#12669 feat(api): return empty json on successful delete response
  UPGRADE.md
  api/mesh/v1alpha1/mesh/rest.yaml
  api/mesh/v1alpha1/meshgateway/rest.yaml
  docs/generated/openapi.yaml
  pkg/api-server/resource_endpoints.go
  pkg/api-server/testdata/resources/crud/delete_dataplanes_01.golden.json
  pkg/api-server/testdata/resources/crud/delete_meshes_01.golden.json
  pkg/api-server/types/resources.go
  pkg/core/resources/apis/hostnamegenerator/api/v1alpha1/rest.yaml
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/rest.yaml
  pkg/core/resources/apis/meshmultizoneservice/api/v1alpha1/rest.yaml
  pkg/core/resources/apis/meshservice/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshaccesslog/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshcircuitbreaker/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshfaultinjection/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshhealthcheck/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshhttproute/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshloadbalancingstrategy/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshmetric/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshpassthrough/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshproxypatch/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshratelimit/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshretry/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtcproute/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtimeout/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtls/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtrace/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtrafficpermission/api/v1alpha1/rest.yaml
  tools/openapi/templates/endpoints.yaml
Labels: ci/skip-e2e-test

#12697 feat(oapi): add docs prerequisite
  mk/docs.mk
Labels: ci/skip-test

#12692 fix(meshtimeout): set default inbound timeouts correctly
  pkg/plugins/policies/meshtimeout/plugin/testdata/basic_without_defaults_inbound_cluster.golden.yaml
  pkg/plugins/policies/meshtimeout/plugin/testdata/basic_without_defaults_inbound_listener.golden.yaml
  pkg/plugins/policies/meshtimeout/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshtimeout/plugin/xds/configurer.go
  test/e2e_env/universal/envoyconfig/testdata/meshtimeout/inbound.demo-client.golden.json
  test/e2e_env/universal/envoyconfig/testdata/meshtimeout/inbound.test-server.golden.json
  test/e2e_env/universal/envoyconfig/testdata/meshtimeout/outbound.demo-client.golden.json
  test/e2e_env/universal/envoyconfig/testdata/meshtimeout/outbound.test-server.golden.json
Labels: backport
