Repository kumahq/kuma, pull requests merged in 2025-05, with the labels that each got.

#13513 chore(deps): bump envoy from v1.34.0 to v1.34.1
  mk/dependencies/deps.lock
  mk/dev.mk
Labels: dependencies, master

#13514 chore(deps): bump envoy from v1.32.5 to v1.32.6
  mk/dependencies/deps.lock
  mk/dev.mk
Labels: dependencies, release-2.10

#13515 chore(deps): bump envoy from v1.30.11 to v1.31.8
  mk/dependencies/deps.lock
  mk/dev.mk
Labels: dependencies, release-2.9

#13516 chore(deps): bump envoy from v1.30.11 to v1.31.8
  mk/dependencies/deps.lock
  mk/dev.mk
Labels: dependencies, release-2.8

#13517 chore(deps): bump envoy from v1.30.11 to v1.31.8
  mk/dependencies/deps.lock
  mk/dev.mk
Labels: dependencies, release-2.7

#13522 feat(kuma-cp): add metadata field to DataplaneInsight for storing XDS metadata
  api/mesh/v1alpha1/dataplane_insight.pb.go
  api/mesh/v1alpha1/dataplane_insight.proto
  api/mesh/v1alpha1/dataplaneoverview/schema.yaml
  docs/generated/openapi.yaml
  docs/generated/raw/protos/DataplaneInsight.json
  docs/generated/raw/protos/DataplaneOverview.json
  pkg/xds/server/callbacks/dataplane_status_sink.go
  pkg/xds/server/callbacks/dataplane_status_sink_test.go
  pkg/xds/server/callbacks/dataplane_status_tracker.go
  pkg/xds/server/callbacks/dataplane_status_tracker_test.go
  pkg/xds/server/v3/components.go
Labels: ci/run-full-matrix

#13535 ci(ipv6): revert skip ipv6
  .github/workflows/_e2e.yaml
Labels: ci/run-full-matrix

#13542 chore(oapi): bump version to 3.1.0
  api/mesh/v1alpha1/builtincertificateauthorityconfig/schema.yaml
  api/mesh/v1alpha1/datadogtracingbackendconfig/schema.yaml
  api/mesh/v1alpha1/dataplane/rest.yaml
  api/mesh/v1alpha1/dataplaneoverview/schema.yaml
  api/mesh/v1alpha1/fileloggingbackendconfig/schema.yaml
  api/mesh/v1alpha1/mesh/rest.yaml
  api/mesh/v1alpha1/meshgateway/rest.yaml
  api/mesh/v1alpha1/prometheusmetricsbackendconfig/schema.yaml
  api/mesh/v1alpha1/providedcertificateauthorityconfig/schema.yaml
  api/mesh/v1alpha1/tcploggingbackendconfig/schema.yaml
  api/mesh/v1alpha1/zipkintracingbackendconfig/schema.yaml
  api/openapi/specs/api.yaml
  docs/generated/openapi.yaml
  pkg/core/resources/apis/hostnamegenerator/api/v1alpha1/rest.yaml
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/rest.yaml
  pkg/core/resources/apis/meshmultizoneservice/api/v1alpha1/rest.yaml
  pkg/core/resources/apis/meshservice/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshaccesslog/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshcircuitbreaker/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshfaultinjection/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshhealthcheck/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshhttproute/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshloadbalancingstrategy/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshmetric/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshpassthrough/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshproxypatch/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshratelimit/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshretry/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtcproute/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtimeout/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtls/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtrace/api/v1alpha1/rest.yaml
  pkg/plugins/policies/meshtrafficpermission/api/v1alpha1/rest.yaml
  tools/openapi/templates/endpoints.yaml
  tools/resource-gen/pkg/generator/main.go
Labels: ci/skip-e2e-test

#13544 chore(oapi): ignore structpb.Struct from oas generation
  api/mesh/v1alpha1/dataplaneoverview/schema.yaml
  docs/generated/openapi.yaml
  tools/resource-gen/pkg/generator/main.go
Labels: ci/skip-e2e-test

#13507 docs(MADR): update MeshHTTPRoute matching MADR with more details on policy's role
  docs/madr/decisions/060-rework-mesh-routes-matching.md
Labels: ci/skip-test

#13500 docs(MADR): computed endpoints
  docs/madr/decisions/072-computed-api-endpoints.md
Labels: ci/skip-test

#13552 feat(dns): use embedded dns by default instead of coredns
  .github/workflows/_e2e.yaml
  .github/workflows/_test.yaml
  UPGRADE.md
  app/kuma-dp/cmd/run.go
  docs/generated/raw/kuma-cp.yaml
  pkg/config/app/kuma-cp/kuma-cp.defaults.yaml
  pkg/config/loader_test.go
  pkg/config/plugins/runtime/k8s/config.go
  pkg/config/plugins/runtime/k8s/testdata/default-config.golden.yaml
  test/e2e_env/kubernetes/meshmetric/meshmetric.go
  test/framework/config.go
  test/framework/envs/kubernetes/env.go
  test/framework/universal_cluster.go
Labels: ci/run-full-matrix

#13588 ci(github): increase build timeout from 50 to 70 minutes
  .github/workflows/_build_publish.yaml
Labels: ci/skip-test

#13610 chore(renovate): restrict go-control-plane replace to kong-specific builds
  .renovate/go-control-plane.json
Labels: ci/skip-test

#13630 ci(backport): use env.USE_APP_TOKEN variable everywhere
  .github/workflows/backport.yaml
Labels: ci/skip-test

#13616 fix(autoreachableservices): fix nil pointer by skipping policies with targetRef.kind Dataplane
  pkg/plugins/policies/meshtrafficpermission/graph/util/rule_builder.go
Labels: backport

#13640 chore(note): add note about syncing computed labels with speakeasy
  pkg/core/resources/model/labels/labels.go
Labels: ci/skip-test
