Repository kumahq/kuma, pull requests merged in 2025-06, with the labels that each got.

#13676 chore(UPGRADE.md): minor enhancement to UPGRADE.md
  UPGRADE.md
Labels: ci/skip-test, release-2.11

#13678 fix(vip): don't fail once previous address is out of range of new range
  pkg/dns/vips/global_view.go
  pkg/dns/vips/global_view_test.go
Labels: release-2.11

#13700 ci(helm): fix release/helm.sh to properly find helm package
  tools/releases/helm.sh
Labels: ci/skip-test

#13701 fix(actions): pin actions to sha
  .github/workflows/backport.yaml
  .github/workflows/build-test-distribute.yaml
  .github/workflows/lifecycle.yml
Labels: ci/skip-test, release-2.7

#13704 chore(deps): bump lifecycle to 2e670e4083642dfa8f047fab84c6436d28ef81a4
  .github/workflows/lifecycle.yml
Labels: ci/skip-test

#13708 chore(make/k3d): support project name override and stderr output for old targets
  mk/k3d.mk
Labels: ci/skip-test

#13748 fix(oapi): fix generation of oapi schema by skipping not yaml files
  mk/generate.mk
Labels: ci/skip-test

#13727 docs(MADR): move `hashPolicies` field out of the LB specific struct in MLBS
  docs/madr/decisions/074-mlbs-hash-policies.md
Labels: ci/skip-test

#13757 feat(oapi): add zone proto to oas
  api/mesh/v1alpha1/zone/schema.yaml
  docs/generated/openapi.yaml
  tools/resource-gen/pkg/generator/main.go
Labels: ci/skip-test

#13762 chore(deps): upgrade golang version from 1.23.8 to 1.23.10
  go.mod
Labels: release-2.8

#13761 chore(deps): upgrade golang version from 1.23.8 to 1.23.10
  go.mod
Labels: release-2.7

#13764 feat(skaffold): speedup redeploying kuma with Skaffold
  skaffold.yaml
Labels: ci/skip-test
