Repository kumahq/kuma, pull requests merged in 2025-03, with the labels that each got.

#12984 ci(.github): fix the provenance workflow
  .github/workflows/_provenance.yaml
Labels: ci/skip-test

#13002 fix(secrets): return properky typed errors on conflict
  pkg/plugins/config/k8s/store.go
  test/e2e/federation/federation_kubernetes.go
  test/e2e/federation/federation_suite_test.go
  test/e2e/federation/federation_universal.go
Labels: ci/run-full-matrix

#13008 feat(kds): add support for kuma.io/kds-sync label
  api/mesh/v1alpha1/dataplane_helpers.go
  pkg/core/resources/model/resource.go
  pkg/kds/context/context.go
  pkg/kds/context/full_sync_test.go
  pkg/kds/context/testdata/full_sync/mesh-only/global.golden.yaml
  pkg/kds/context/testdata/full_sync/mesh-only/global.input.yaml
  pkg/kds/context/testdata/full_sync/mesh-only/zone-1.golden.yaml
  pkg/kds/context/testdata/full_sync/mesh-only/zone-1.input.yaml
  pkg/kds/context/testdata/full_sync/mesh-only/zone-2.golden.yaml
  pkg/kds/context/testdata/full_sync/mesh-only/zone-2.input.yaml
  pkg/kds/context/testdata/full_sync/policy-simple/global.golden.yaml
  pkg/kds/context/testdata/full_sync/policy-simple/global.input.yaml
  pkg/kds/context/testdata/full_sync/policy-simple/zone-1.golden.yaml
  pkg/kds/context/testdata/full_sync/policy-simple/zone-1.input.yaml
  pkg/kds/context/testdata/full_sync/policy-simple/zone-2.golden.yaml
  pkg/kds/context/testdata/full_sync/policy-simple/zone-2.input.yaml
  pkg/kds/context/testdata/full_sync/policy-with-kds-disabled/global.golden.yaml
  pkg/kds/context/testdata/full_sync/policy-with-kds-disabled/global.input.yaml
  pkg/kds/context/testdata/full_sync/policy-with-kds-disabled/zone-1.golden.yaml
  pkg/kds/context/testdata/full_sync/policy-with-kds-disabled/zone-1.input.yaml
  pkg/kds/context/testdata/full_sync/policy-with-kds-disabled/zone-2.golden.yaml
  pkg/kds/context/testdata/full_sync/policy-with-kds-disabled/zone-2.input.yaml
  pkg/test/ginkgo.go
  pkg/test/kds/setup/server.go
  pkg/test/store/load.go
  pkg/util/files/files.go
  test/framework/debug.go
  test/framework/ssh/ssh.go
Labels: release-2.10

#13028 fix(resource): use kuma.io/display-name instead of name
  pkg/api-server/testdata/resources/crud/put_meshes_04.golden.json
  pkg/api-server/testdata/resources/crud/put_meshexternalservice_01.golden.json
  pkg/api-server/testdata/resources/crud/put_meshexternalservice_02.golden.json
  pkg/api-server/testdata/resources/crud/put_meshmultizoneservice_01.golden.json
  pkg/api-server/testdata/resources/crud/put_meshmultizoneservice_02.golden.json
  pkg/api-server/testdata/resources/crud/put_meshservice_02.golden.json
  pkg/core/resources/apis/mesh/deprecated.go
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/deprecated.go
  pkg/core/resources/apis/meshmultizoneservice/api/v1alpha1/deprecated.go
  pkg/core/resources/apis/meshservice/api/v1alpha1/deprecated.go
  pkg/core/resources/apis/system/deprecated.go
  pkg/plugins/runtime/k8s/webhooks/testdata/validation/cp-user_create_mes.federated.golden.yaml
  pkg/plugins/runtime/k8s/webhooks/testdata/validation/cp-user_create_mes.global.golden.yaml
  pkg/plugins/runtime/k8s/webhooks/testdata/validation/cp-user_create_mes.input.yaml
  pkg/plugins/runtime/k8s/webhooks/testdata/validation/cp-user_create_mes.non-federated.golden.yaml
Labels: release-2.10

#13014 fix(meshservice): enhance the validation of kuma.io/service name for meshservice generation
  UPGRADE.md
  pkg/core/resources/apis/meshservice/generate/generator.go
  pkg/core/resources/apis/meshservice/generate/generator_test.go
Labels: release-2.10

#13052 feat(renovate): add custom manager for go-control-plane and update config
  .renovate/go-control-plane.json
  renovate.json
Labels: area/ci-cd, ci/skip-test

#13005 chore(dev): add notes for debugging E2E in IDE
  DEVELOPER.md
Labels: ci/skip-test

#13046 chore(upgrade.md): improve wording
  UPGRADE.md
Labels: ci/skip-test

#13069 chore(test/unit): fix order in golden files for kds context sync tests
  pkg/kds/context/testdata/full_sync/mesh-only/global.golden.yaml
  pkg/kds/context/testdata/full_sync/policy-simple/zone-1.golden.yaml
  pkg/test/store/load.go
Labels: ci/skip-e2e-test, release-2.10

#13071 chore(renovate): group kumactl install k8s container images
  renovate.json
Labels: area/ci-cd, ci/skip-test

#13056 chore(api): export all computed labels to be used in another project
  pkg/core/resources/model/labels/labels.go
  pkg/core/resources/model/resource.go
Labels: release-2.10

#13077 chore(git): fix improperly pushed commits
  renovate.json
  test/e2e_env/kubernetes/gateway/delegated/meshtrace.go
  test/e2e_env/kubernetes/observability/meshtrace.go
  test/e2e_env/kubernetes/observability/tracing.go
  test/e2e_env/universal/observability/meshtrace.go
  test/e2e_env/universal/observability/tracing.go
Labels: ci/skip-test

#13051 fix(kuma-cp): change usage of deprecated global_downstream_max_connections
  pkg/xds/bootstrap/template_v3.go
  pkg/xds/bootstrap/testdata/bootstrap.gateway.golden.yaml
  pkg/xds/bootstrap/testdata/generator.gateway.golden.yaml
Labels: release-2.10

#13081 feat(renovate): improve go-control-plane updates and grouping
  .renovate/go-control-plane.json
Labels: ci/skip-test

#12940 ci(.github): add a workflow to backport PRs manually
  .github/workflows/backport.yaml
Labels: ci/skip-test

#13100 test(kds): increase wait time in full sync test to reduce flakiness
  pkg/kds/context/full_sync_test.go
Labels: ci/skip-e2e-test, release-2.10

#13080 feat(helm): expose CNI affinity setting
  app/kumactl/cmd/install/testdata/install-control-plane.dump-values.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/fix13029.golden.yaml
  app/kumactl/cmd/install/testdata/install-cp-helm/fix13029.values.yaml
  deployments/charts/kuma/README.md
  deployments/charts/kuma/templates/cni-daemonset.yaml
  deployments/charts/kuma/values.yaml
  docs/generated/raw/helm-values.yaml
Labels: release-2.10

#13105 test(unit): compare file content instead of yaml
  pkg/kds/context/full_sync_test.go
  pkg/kds/context/testdata/full_sync/policy-with-kds-disabled/global.golden.yaml
Labels: ci/skip-e2e-test, release-2.10

#13108 fix(meshservice): fix inbound port selecting logic on MeshService
  pkg/core/resources/apis/meshservice/match.go
  pkg/core/resources/apis/meshservice/status/updater.go
  pkg/core/resources/apis/meshservice/status/updater_test.go
  pkg/xds/topology/outbound.go
Labels: release-2.10

#13127 chore(renovate): unify commit messages to match dependabot for changelog automation
  .renovate/go-control-plane.json
  renovate.json
Labels: ci/skip-test

#13131 test(gatewayapi): allow secrets in all namespaces
  test/e2e_env/gatewayapi/conformance_test.go
Labels: ci/run-full-matrix

#13136 chore(deps): bump release-tool from v1.1.4 to v1.1.5
  .github/workflows/release.yaml
Labels: ci/skip-test

#13146 chore(renovate): upgrade backend preset to 1.4.0 and reuse GitHub Actions preset
  .renovate/github-actions.json
  renovate.json
Labels: ci/skip-test

#13150 feat(kubernetes): verify against kubernetes 1.31
  .github/workflows/_test.yaml
  mk/dependencies/deps.lock
  mk/dependencies/k3d.sh
  mk/dev.mk
Labels: ci/run-full-matrix, release-2.7

#13159 chore(deps): upgrade envoy version from v1.32.3 to v.1.32.4
  mk/dependencies/deps.lock
  mk/dev.mk
Labels: dependencies, release-2.10

#13161 chore(deps): upgrade envoy version from v1.30.9 to v1.30.10
  mk/dependencies/deps.lock
  mk/dev.mk
Labels: dependencies, release-2.8

#13162 chore(deps): upgrade envoy version from v1.29.12 to v1.30.10
  mk/dependencies/deps.lock
  mk/dev.mk
Labels: dependencies, release-2.7

#12756 docs(MADR): resource identifier format
  docs/madr/decisions/070-resource-identifier.md
Labels: ci/skip-test

#13200 feat(docs): add information about new rules api and dataplane kind in upgrade md
  UPGRADE.md
Labels: ci/skip-test

#13191 chore(e2e): rewrite e2e config init
  pkg/test/ginkgo.go
  test/e2e_env/gatewayapi/conformance_test.go
  test/framework/config.go
Labels: ci/run-full-matrix

#13216 refactor(e2e): remove unnecessary GinkgoHelper call in meshhttproute test
  test/e2e_env/multizone/meshhttproute/test.go
Labels: ci/skip-test

#13218 ci(flake): skip federation kube flaky test
  test/e2e/federation/federation_suite_test.go
Labels: ci/skip-test

#13221 ci(publish): change timeout of build_publish to 50 min from 40 min
  .github/workflows/_build_publish.yaml
Labels: ci/skip-test

#13238 chore(deps): upgrade envoy version from v1.30.10 to v1.30.11
  mk/dependencies/deps.lock
  mk/dev.mk
Labels: dependencies, release-2.7

#13239 chore(deps): upgrade envoy version from v1.30.10 to v1.30.11
  mk/dependencies/deps.lock
  mk/dev.mk
Labels: dependencies, release-2.8

#13240 chore(deps): upgrade envoy version from v1.30.10 to v1.30.11
  mk/dependencies/deps.lock
  mk/dev.mk
Labels: dependencies, release-2.9

#13241 chore(deps): upgrade envoy version from v1.32.4 to v1.32.5
  mk/dependencies/deps.lock
  mk/dev.mk
Labels: dependencies, release-2.10

#13242 chore(deps): upgrade envoy version from v1.33.1 to v1.33.2
  mk/dependencies/deps.lock
  mk/dev.mk
Labels: dependencies, master

#13245 chore(deps): upgrade golang version from 1.23.6 to 1.23.7
  go.mod
Labels: dependencies, release-2.8

#13244 chore(deps): upgrade golang version from 1.23.6 to 1.23.7
  go.mod
Labels: dependencies, release-2.7

#13246 chore(deps): upgrade golang version from 1.23.6 to 1.23.7
  go.mod
Labels: dependencies, release-2.9

#13247 chore(deps): upgrade golang version from 1.23.6 to 1.23.7
  go.mod
Labels: dependencies, release-2.10

#13254 refactor(make): refactor k3d deploy targets
  DEVELOPER.md
  mk/k3d.mk
Labels: ci/skip-test
