Repository kumahq/kuma, pull requests merged in 2025-10, with the labels that each got.

#14571 docs(MADR): record decision to add KRI to REST API resources
  docs/madr/decisions/084-add-kri-to-rest-api-resources.md
Labels: ci/skip-test

#14557 fix(dns): allow DNS traffic over TCP to bypass the mesh DNS
  app/kumactl/cmd/install/testdata/install-transparent-proxy.dns.no-conntrack.golden.txt
  pkg/transparentproxy/iptables/builder/builder_table_nat.go
Labels: ci/run-full-matrix

#14572 docs(MADR): document switch to Renovate preset for active branches
  docs/madr/decisions/085-active-branches-renovate-preset.md
Labels: ci/skip-test

#14590 feat(kumactl): switch from Bitnami to registry.k8s.io and pin
  app/kumactl/cmd/install/testdata/install-observability.defaults.golden.yaml
  app/kumactl/cmd/install/testdata/install-observability.no-grafana.golden.yaml
  app/kumactl/cmd/install/testdata/install-observability.no-jaeger.golden.yaml
  app/kumactl/cmd/install/testdata/install-observability.no-loki.golden.yaml
  app/kumactl/cmd/install/testdata/install-observability.overrides.golden.yaml
  app/kumactl/data/install/k8s/metrics/prometheus/kube-stats-metrics.yaml
Labels: ci/skip-test, release-2.7

#14591 feat(kumactl): switch from Bitnami to registry.k8s.io and pin
  app/kumactl/cmd/install/testdata/install-observability.defaults.golden.yaml
  app/kumactl/cmd/install/testdata/install-observability.no-grafana.golden.yaml
  app/kumactl/cmd/install/testdata/install-observability.no-jaeger.golden.yaml
  app/kumactl/cmd/install/testdata/install-observability.no-loki.golden.yaml
  app/kumactl/cmd/install/testdata/install-observability.overrides.golden.yaml
  app/kumactl/data/install/k8s/metrics/prometheus/kube-stats-metrics.yaml
Labels: ci/skip-test, release-2.9

#14593 feat(kumactl): switch kube-state-metrics to upstream image
  app/kumactl/cmd/install/testdata/install-observability.defaults.golden.yaml
  app/kumactl/cmd/install/testdata/install-observability.no-grafana.golden.yaml
  app/kumactl/cmd/install/testdata/install-observability.no-jaeger.golden.yaml
  app/kumactl/cmd/install/testdata/install-observability.no-loki.golden.yaml
  app/kumactl/cmd/install/testdata/install-observability.overrides.golden.yaml
  app/kumactl/data/install/k8s/metrics/prometheus/kube-stats-metrics.yaml
Labels: ci/skip-test, release-2.11

#14595 test(postgres): pin CNPG Helm charts by digest only for CI stability
  test/framework/deployments/postgres/kubernetes.go
Labels: backport

#14602 test(postgres): pin image, update to 18.0, fix legacy e2e secrets
  test/e2e/helm/kuma_helm_deploy_global_and_zone_universal_mode.go
  test/e2e/helm/kuma_helm_deploy_global_universal_mode_and_zone.go
  test/framework/deployments/postgres/deployment.go
  test/framework/deployments/postgres/kubernetes.go
Labels: ci/run-full-matrix, backport

#14581 fix(envoy-naming): rename inbound Envoy resource names and stats to use `sectionName` instead of port value when using unified naming
  api/mesh/v1alpha1/dataplane_helpers.go
  api/mesh/v1alpha1/dataplane_helpers_test.go
  pkg/core/faultinjections/matcher_test.go
  pkg/core/permissions/matcher_test.go
  pkg/core/ratelimits/matcher_test.go
  pkg/core/xds/inspect/attachments_test.go
  pkg/plugins/policies/meshratelimit/plugin/v1alpha1/plugin_test.go
  pkg/plugins/policies/meshtls/plugin/v1alpha1/plugin.go
  pkg/xds/generator/inbound_proxy_generator.go
  pkg/xds/generator/inbound_proxy_generator_test.go
  pkg/xds/generator/testdata/inbound-proxy/8-envoy-config.golden.yaml
  pkg/xds/generator/testdata/profile-source/5-envoy-config.golden.yaml
Labels: ci/run-full-matrix

#14616 chore(tooling): bump Helm to 3.18.1 to include upstream bugfix
  mise.toml
Labels: ci/skip-test

#14603 test(helm): skip upgrade suites that use unsupported images and versions
  test/e2e/helm/e2e_suite_test.go
Labels: ci/run-full-matrix

#14641 test(e2e/helm): fix upgrade test registry logic after `bitnami` changes
  test/e2e/helm/kuma_helm_upgrade_multizone.go
  test/e2e/helm/kuma_helm_upgrade_standalone.go
  test/framework/config.go
  test/framework/ginkgo.go
  versions.yml
Labels: ci/run-full-matrix, release-2.9

#14642 test(e2e/helm): fix upgrade test registry logic after `bitnami` changes
  test/e2e/helm/kuma_helm_upgrade_multizone.go
  test/e2e/helm/kuma_helm_upgrade_standalone.go
  test/framework/config.go
  test/framework/ginkgo.go
  versions.yml
Labels: ci/run-full-matrix, release-2.10
