Repository kumahq/kuma, pull requests merged in 2025-07, with the labels that each got.

#13833 ci(gha): remove tag pushing triggering behavior for docs updating
  .github/workflows/update-docs.yaml
Labels: ci/skip-test, backport

#13884 docs(MADR): fix wording, formatting, and examples in MADR-077 after merge
  docs/madr/decisions/077-migrating-to-consistent-and-well-defined-naming-for-non-system-envoy-resources-and-stats.md
Labels: ci/skip-test

#13879 docs(MADR): MeshTrafficPermission Is a Special Case of Inbound Policies and Requires a Custom Matching Algorithm
  docs/madr/decisions/078-special-mtp-algo.md
Labels: ci/skip-test

#13783 docs(MADR): naming system envoy resources
  docs/madr/decisions/036-internal-listeners.md
  docs/madr/decisions/076-naming-system-envoy-resources.md
Labels: ci/skip-test

#13853 fix(dynconfig): change the direct response body size dynamically
  pkg/plugins/policies/meshmetric/plugin/v1alpha1/testdata/basic.listeners.golden.yaml
  pkg/plugins/policies/meshmetric/plugin/v1alpha1/testdata/default.listeners.golden.yaml
  pkg/plugins/policies/meshmetric/plugin/v1alpha1/testdata/multiple_otel.listeners.golden.yaml
  pkg/plugins/policies/meshmetric/plugin/v1alpha1/testdata/multiple_prometheus.listeners.golden.yaml
  pkg/plugins/policies/meshmetric/plugin/v1alpha1/testdata/openTelemetry.listeners.golden.yaml
  pkg/plugins/policies/meshmetric/plugin/v1alpha1/testdata/otel_and_prometheus.listeners.golden.yaml
  pkg/plugins/policies/meshmetric/plugin/v1alpha1/testdata/provided_tls.listeners.golden.yaml
  pkg/xds/dynconf/dynconf_suite_test.go
  pkg/xds/dynconf/listener.go
  pkg/xds/dynconf/listener_test.go
  pkg/xds/generator/testdata/dns/4-envoy-config.golden.yaml
Labels: backport

#13943 chore(deps): bump envoy from v1.31.8 to v1.31.9
  mk/dependencies/deps.lock
  mk/dev.mk
Labels: dependencies, release-2.7

#13950 test(transparentproxy): add missing files
  test/transparentproxy/testdata/debian-13-default.ip6tables.golden
  test/transparentproxy/testdata/debian-13-with-multiple-config-flags.ip6tables.golden
  test/transparentproxy/testdata/debian-13-with-multiple-flags.ip6tables.golden
Labels: ci/skip-test, ci/skip-e2e-test

#13953 test(transparentproxy): add missing files
  test/transparentproxy/testdata/debian-13-default.ip6tables-nft.golden
  test/transparentproxy/testdata/debian-13-with-multiple-config-flags.ip6tables-nft.golden
  test/transparentproxy/testdata/debian-13-with-multiple-flags.ip6tables-nft.golden
Labels: ci/skip-test, ci/skip-e2e-test

#13956 chore(deps): upgrade golangci-lint from v2.1.6 to v2.2.2
  .github/workflows/build-test-distribute.yaml
  mk/dependencies/deps.lock
  mk/dev.mk
Labels: dependencies, ci/skip-test, ci/skip-e2e-test

#13977 chore(deps): bump CoreDNS to v1.12.2
  mk/build.mk
Labels: dependencies, release-2.9

#13979 chore(deps): bump CoreDNS to v1.12.2
  mk/build.mk
Labels: dependencies, release-2.11

#13848 docs(MADR): SPIFFE ID matches for MeshTrafficPermission
  docs/madr/decisions/080-inbound-policies-matches.md
Labels: ci/skip-test

#14017 chore(deps): bump envoy from v1.31.9 to v1.31.10
  mk/dependencies/deps.lock
  mk/dev.mk
Labels: dependencies, release-2.9

#14012 feat(tools): move clang-format from `make check` to action
  .github/workflows/build-test-distribute.yaml
  mk/check.mk
Labels: ci/skip-test

#13910 docs(MADR): introduction of common DataSource struct
  docs/madr/decisions/081-datasource-api.md
Labels: ci/skip-test, ci/skip-e2e-test

#14038 feat(kuma-cp/xds): enable unified resource naming for MeshHTTPRoute listeners
  pkg/core/resources/apis/core/destinationname/destinationname.go
  pkg/core/resources/apis/core/interfaces.go
  pkg/core/resources/apis/meshexternalservice/api/v1alpha1/helpers.go
  pkg/core/resources/apis/meshmultizoneservice/api/v1alpha1/helpers.go
  pkg/core/resources/apis/meshservice/api/v1alpha1/helpers.go
  pkg/core/xds/types/outbound.go
  pkg/plugins/policies/core/rules/subsetutils/subset.go
  pkg/plugins/policies/core/xds/meshroute/listeners.go
  pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshaccesslog/plugin/v1alpha1/plugin_test.go
  pkg/plugins/policies/meshcircuitbreaker/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshhealthcheck/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/gateway_routes.go
  pkg/plugins/policies/meshhttproute/plugin/v1alpha1/listeners.go
  pkg/plugins/policies/meshhttproute/xds/builder.go
  pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/plugin_test.go
  pkg/plugins/policies/meshratelimit/plugin/v1alpha1/plugin_test.go
  pkg/plugins/policies/meshretry/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshtcproute/plugin/v1alpha1/gateway.go
  pkg/plugins/policies/meshtcproute/plugin/v1alpha1/listeners.go
  pkg/plugins/policies/meshtcproute/plugin/v1alpha1/listeners_backendrefs.go
  pkg/plugins/policies/meshtimeout/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshtrace/plugin/v1alpha1/plugin.go
  pkg/plugins/policies/meshtrafficpermission/plugin/v1alpha1/plugin.go
  pkg/plugins/runtime/gateway/cluster_generator.go
  pkg/test/resources/samples/meshhttproute_samples.go
  pkg/xds/envoy/listeners/listener_configurers.go
  pkg/xds/envoy/listeners/v3/stat_prefix_configurer.go
  pkg/xds/envoy/listeners/v3/stat_prefix_configurer_test.go
  pkg/xds/generator/zoneproxy/destinations.go
  pkg/xds/topology/outbound.go
Labels: ci/run-full-matrix

#14055 ci(lint): set smaller gomemlimit to combat OOMs
  .github/workflows/build-test-distribute.yaml
Labels: ci/skip-test

#14067 ci(gha): update disabled tool name in mise action to match full registry name
  .github/workflows/_e2e.yaml
  mise.toml
Labels: ci/skip-test

#14071 test(flake): disable `requests should be routed directly through local sidecar when zone egress disabled` flaky test
  test/e2e_env/multizone/localityawarelb/locality_multizone_hybrid.go
Labels: ci/skip-test

#14077 chore(deps): bump envoy from v1.32.8 to v1.32.9
  mk/dependencies/deps.lock
  mk/dev.mk
Labels: dependencies, release-2.10

#14085 ci(renovate): add Makefile preset and simplify mise config
  .renovate/makefile.json
  .renovate/mise.json
  mk/dev.mk
  renovate.json
Labels: ci/skip-test
